<div class="container-fluid ">
<?php  $url = '/static/frontend/Smartwave/porto_child/en_US/Consultera_Ambasdor/images/background-ambasdor-new.png';?>
    <div class="row  m-2 ambasdor-row-1" style="background-image: url('<?php echo $url ?>'); background-repeat:no-repeat; ">
     <div class="container">
		<div class="row">
			<div class="col-md-6  ambasdor-col-1">
						<h3 class="join-us"> Join with us!</h3>
						<h1 class="influencer">Become a valuable part of
							our influencer network!</h1>
							<span class="ambasdor-button py-5">
                                        <a href="/marketplace/"> <button class="btn btn-success btn-1 m-2"> Register </button></a> 
                                        <a href="#how-to-be-part">  <button class="btn btn-secondary  btn-2 m-2" > How It works </button></a> 
							</span>
			</div>
			<div class="col-md-5  ambasdor-col-2">
			<img src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/ambassador-header-image.png'); ?>" />
			</div>
		</div>
	 </div>
    </div>    
        
        <div class="container black-ambassador-section"  id="how-to-be-part" >
		<h2 class="py-3 text-center part-of-us">How to be a part of us?</h2>
		<div class="row py-5  ambassador-row ambasdor-row-2" >
						<div class="row">
                        <div class="col-md-4 ambasdor-col-3">
                                    <div class="card">
                                       
                                       <img  src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/ambassador.svg'); ?>"  class="card-img-top"/>
                                       
                                       
                                        <div class="card-body">
                                                    <h4 class="card-title mt-5">Register as ambassador</h4>
                                                    <p class="card-text" >
                                                    Join tens of thousands of creators, publishers and bloggers who are earning with the EnjoyP Associates Program.
                                                </p> 
                                                <img  src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/arrow-down.png'); ?>"  class="mobile"/>
                                        </div>
                                    </div>
                        </div>
                        <div class="col-md-4 ambasdor-col-4">
                                    <div class="card">
                                    <img  class="desktop" src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/arrow.png'); ?>"  style="text-center;"/>
                                    <img src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/product.svg'); ?>"  class="card-img-top"/>
                                        <div class="card-body">
                                                <h4 class="card-title  mt-5">Recommend our products</h4>
                                                <p class="card-text" >
                                                Share millions of products with your audience. We have customized linking tools for large publishers, individual bloggers and social media influencers.
                                            </p> 
                                            <img  src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/arrow-down.png'); ?>"  class="mobile"/>
                                        </div>
                                       
                                    </div>
                        </div>
                        <div class="col-md-4 ambasdor-col-5">
                                    <div class="card">
                                        <img  class="desktop " src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/arrow.png'); ?>"  />

                                        <img src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/point.svg'); ?>"  class="card-img-top"/>
                                        
                                        <div class="card-body">
                                                <h4 class="card-title  mt-5">Earn Wageb points</h4>
                                                <p class="card-text" >
                                                Support our initiativ and earn points that you can convert in products. Wageb is an initiative to strengthen the Palestinian identity.
                                                </p> 
                                    
                                        </div>
                                    </div>
                        </div>
                        </div>    
                        <div class="col-sm-12 text-center m-5 join-us">
                            <a href="#join-us">  
                                <button class="btn btn-success  center-btn" > Join Us </button>
                            </a> 
                        </div>


		</div>
    <div class="row py-5 mt-4 ambassador-row ambasdor-row-3"  style="background:black;">
                  <div class="col-sm-6 ambasdor-col-6">
                  <img src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/social-media-reels.png'); ?>" />
                </div>
                <div class="col-sm-6 ambasdor-col-7">
                  <h1 class="share-product">Share products on your social media reel</h1>
                  <p class="share-product-text">Create a Reel that shows off the most important features of your product in a way that's visually engaging and easy to 
                     understand. Join us as a social media 
                     reel sharing partner, to join first you need to fill up a form then we contact with you and make a business deal with you.</p>
                    <span class="join-us-btn">
                    <a href="#join-us">  
                        <button class="btn btn-success btn-1 ml-3"> Join Us </button>
                    </a> 
                   </span>
                </div>


   </div>     
   <div class="row py-5  mt-4 ambassador-row ambasdor-row-4"  style="background:black;">
                  <div class="col-sm-6 ambasdor-col-8">
                  <img src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/influencer.png'); ?>" />
                </div>
                <div class="col-sm-6 ambasdor-col-9">
                  <h1 class="become-influencer">Become an influencer of our products</h1>
                  <p class="become-influencer-text">Create a Reel that shows off the most important features of your product in a way that's visually engaging and easy to understand. Join us as a social 
                     media reel sharing partner, to join first you need to fill up a form then we contact with you and make a business deal with you.</p>
                     <span class="join-us-btn">
                    <a href="#join-us" >  
                        <button class="btn btn-success btn-1 ml-3"> Join Us </button>
                    </a> 
                   </span>
                </div>
    </div>     
    <div class="row py-5  mt-4 ambassador-row ambasdor-row-5" style="background:black;">
                  <div class="col-sm-6 ambasdor-col-10">
                  <img src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/affiliate.png'); ?>" />
                </div>
                <div class="col-sm-6 ambasdor-col-11">
                  <h1 class="become-affliate">Become an affiliate and get  percentage from sell</h1>
                  <p class="become-affliate-text">Create a Reel that shows off the most important features of your product in a way that's visually engaging and easy to 
                     understand. Join us as a social media 
                     reel sharing partner, to join first you need to fill up a form then we contact with you and make a business deal with you.</p>
                     <span class="join-us-btn">
                    <a href="#join-us">  
                        <button class="btn btn-success btn-1 ml-3"> Join Us </button>
                    </a> 
                   </span>
                </div>
    </div>     
                  
    <div class="row py-5  mt-4 ambassador-row ambasdor-row-6"  style="background: #F2F6F5;">
            <!-- <div class="col-sm-12 ambasdor-center  d-none d-lg-block" >-->
                  <div class="col-sm-12 ambasdor-center"  id="join-us" >
                     <h3 class="text-center join-of-us">Join with us</h3>
                               
                    <!-- <span class="choose-btn ">
                    <button type="button"> <input type="radio" id="one" name="first_item" value="1" /> <label for="one">I will share reel</label></button>
                    <button type="button"><input type="radio" id="two" name="first_item" value="1" />  <label for="two">I’m an Influencer</label></button>
                    <button type="button"> <input type="radio" id="three" name="first_item" value="1" /><label for="one">I’m an Affiliate</label></button>
                    </span> -->
           </div>
           <!-- <div class="col-sm-12 ambasdor-center  d-block d-lg-none" id="join-us" >
                     <h2 class="text-center join-of-us">Join with us</h2> -->
                               
                    <!-- <div class="choose-btn">
                    <button type="button"> <input type="radio" id="one" name="first_item" value="1" /> <label for="one">I will share reel</label></button>
                    <button type="button"><input type="radio" id="two" name="first_item" value="1" />  <label for="two">I’m an Influencer</label></button>
                    <button type="button"> <input type="radio" id="three" name="first_item" value="1" /><label for="one">I’m an Affiliate</label></button>
                    </div> -->
           <!-- </div> -->
                    
            <div class="col-sm-5 py-5 ambasdor-col-12 d-none d-lg-flex" >
                    <img src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/join-us-ambasdor.png'); ?>" />
            </div>
            <div class="col-sm-6 py-5 ambasdor-col-13">
                 <?php echo $this->getLayout()->createBlock('Consultera\Ambasdor\Block\Form\Register')->setTemplate('Consultera_Ambasdor::form/register.phtml')->toHtml(); ?>
            </div>
             

    </div> 
    <div class="row py-5  mt-4 ambassador-row ambasdor-row-7" style="background:black;" >
         <div class="col-sm-4 p-2">
         <img  class="ceo" src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/ambasdor-ceo.png'); ?>" /><br>
           <strong class="ambasdor-ceo-title">Leslie Alexander</strong><br>
           <strong class="follower"> 432K followers</strong>
            
           
          </div>

        <div class="col-sm-7 p-3">
               <div class="text">
              
              <p class="ambasdor-text" style="background: #E6FCF4;"> <img  class="comma" src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/comma.png'); ?>"  style="max-width:25px;"/>
              B2B e-commerce platforms like Wholesale Channel, Technology Manager, and B2B Self Service Portal offer powerful tools to increase 
               efficiency and  ultimately lead to greater success. These platforms are essential for sellers to transact with buyers and access a vast pool of potential customers.</p>
                       <div class="arrow"  style="display:flex;">
                          <a href=" "> <img src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/backword.png'); ?>" /></a> 
                           <a href=" "> <img src="<?php echo $this->getViewFileUrl('Consultera_Ambasdor::images/forward.png'); ?>" /></a> 
                          
                </div>         
                        </div>
        </div>
                      

    </div>
</div>      



</div>


<style>

    /*  To disbale the click of arrow at bottom */
    main#maincontent .col-sm-7.p-3 .text .arrow {
    pointer-events: none;
}
p.card-text {
    color: #4B5565;
}
#maincontent .arrow img {
    width: 38px;
    height: auto;
}
#maincontent .arrow img:hover {
	width: 48px;
    height: auto;
}
#maincontent .text .arrow {
    margin-top: 30px;
}
label.radio-inline {
    background: #FFFFFF;
    border: 1px solid #D0D5DD;
    width: max-content;
    height: 60px;
    display: inline-block;
    padding: 15px 20px 15px 15px;
}
.choose-btn {
    display: none;
}
.col-sm-6.py-5.ambasdor-col-13 .radio-btn label.radio-inline {
    margin-right: 72px;
	font-size: 20px;
    line-height: 24px;
    color: #4B5565;
}
   .row.py-5.mt-4.ambasdor-row-7 .col-sm-4.p-2 img.ceo {
    margin: 0 0 15px 0;
}
strong.ambasdor-ceo-title {
    margin-left: 65px;
    font-size: 29px;
    font-weight: 600;
    line-height: 32px;
    font-family: 'POPPINS';
    font-style: normal;
}
.col-sm-7.p-3 p.ambasdor-text {
    margin-top: 144px;
    background: #E6FCF4;
    font-weight: 400;
    font-size: 16px;
    line-height: 28px;
    color: #222529;
    margin-left: 0;
    font-family: 'Poppins';
    font-style: normal;
    padding: 15px;
}
#maincontent .text .comma {
	max-width: 100%!important;
    position: absolute;
    top: -16px;
    left: 10px;
    width: 40px;
	margin-top:0;
}
.text {position:relative;}
.text p.ambasdor-text img.comma {
    margin-top: -61px;
}
.col-sm-4.p-2 strong.follower {
    margin-left: 0;
    font-size: 21px;
    font-weight: 400;
    font-family: 'Poppins';
    font-style: normal;
    line-height: 21px;
	color:#fff;
}
p.card-text {
    color: #4B5565;
}
.col-sm-12.ambasdor-center span.choose-btn button:hover {
    color: unset!important;
    background-color: unset!important;
    border-color: #046F4F;
}
.ambasdor-index-index main#maincontent {
    max-width: 100%;
	padding-top:0;
}
.card img.desktop {
    position: absolute;
    left: -27px;
    top: 70px;
}
#maincontent .fieldset > .field .label {
	font-weight: 500;
    font-size: 14px;
    line-height: 20px;
    margin-bottom: 6px;
	color: #222529
}
#maincontent .form.create.account .actions-toolbar > .primary .action {
	padding:0;
	background: #046F4F;
	font-weight: 500;
	font-size: 16px;
	line-height: 26px;
	text-align: center;
	color: #FFFFFF;
	padding:13px 61px;
	text-transform:none;
	letter-spacing:0
}
#maincontent .form.create.account .actions-toolbar {padding:0;}
.join-us {margin-bottom:16px;}
#maincontent .btn {
	font-weight: 500;
    font-size: 16px;
    padding: 13px 52px;
    line-height: 26px;
    text-transform: none;
    letter-spacing: 0;
	margin: 0!important;
    margin-right: 15px!important;
}
#maincontent .btn.btn-secondary {
    background: transparent;
    color: #046F4F;
    border-color: #046F4F;
}
#maincontent .row.py-5.mt-4.ambassador-row.ambasdor-row-6 {margin-top:120px!important; margin-bottom:120px!important;}
#maincontent.row.m-2.ambasdor-row-1 .col-md-6.ambasdor-col-1 {padding-left: 0;}
#maincontent .ambasdor-col-1 h1.influencer {font-weight: 600; font-size: 50px;  line-height: 120%; color: #222529;}
.ambasdor-row-1 {background-size:100vw 65vh; margin: 0!important;}
.ambasdor-index-index .container-fluid {padding-left:0; padding-right:0;}
.text .arrow {
    display: flex;
    justify-content: space-around;
    margin-top: 65px;
}
#maincontent strong.ambasdor-ceo-title {
    margin-left: 0;
	color: #fff;
}

    @media only screen and (min-width: 992px) {
  span.earnb img.dollor{
    border-radius: 50%;
    width: 23px;
    height: 23px;
    margin-left: -17px;
    border: 2px solid red;
}

span.ambasdor-button.py-5 button.btn.btn-success.btn-1.m-2 {
    background: #046F4F;
    color: white;
    min-width: 170px;
}
span.ambasdor-button.py-5 button.btn.btn-secondary.btn-2.m-2 {
    background: #046F4F;
    color: white;
}
.row.m-2.ambasdor-row-1 .col-md-6.ambasdor-col-1 {
    padding-left: 0;
    padding-top: 102px;
}
.col-sm-5.ambasdor-col-2 img {
    min-width: 520px;
    min-height: 462px;
}
.col-sm-6.ambasdor-col-1 h3.join-us {
    font-size: 24px;
    line-height: 32px;
    font-weight: 500;
    font-family: 'Poppins';
    font-style: normal;
}
.col-sm-6.ambasdor-col-1 h1.influencer {
    font-size: 31px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    line-height: 120%;
}

h2.py-3.text-center.part-of-us {
    font-size: 40px;
    font-weight: 600;
    line-height: 48px;
    font-family: 'Poppins';
    font-style: normal;
    margin-top: 48px;
}
.row.py-5.ambasdor-row-2 h4.card-title.mt-5 {
    font-size: 24px;
    line-height: 32px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
}
.row.py-5.ambasdor-row-2 p.card-text {
    font-size: 16px;
    font-weight: 400;
    line-height: 24px;
    font-family: 'Poppins';
    font-style: normal;
}


.col-sm-12.text-center.m-5.join-us a button.btn.btn-success.center-btn {
    background: #046F4F;
    min-width: 200px;
    color: white;
    font-size: 16px;
    line-height: 16px;
    font-family: 'POPPINS';
    font-style: normal;
}
.col-sm-6.ambasdor-col-7 h1.share-product {
    font-size: 36px;
    line-height: 48px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    color: #E3E8EF;
	max-width:530px;
	margin-bottom:20px;
}
span.join-us-btn button.btn.btn-success.btn-1.ml-3 {
    background: #046F4F;
    color: #E3E8EF;
}
#maincontent .ambassador-row {padding:60px 0px!important;}
.col-sm-6.ambasdor-col-7 p.share-product-text {
    font-size: 16px;
    line-height: 24px;
    font-family: 'POPPINS';
    font-style: normal;
    font-weight: 400;
    color: #CDD5DF;
	margin-bottom:32px;
}
#maincontent span.join-us-btn .btn {
    border: 1px solid #046F4F;
}
.col-sm-6.ambasdor-col-7 {
    padding: 51px;
}
.col-sm-6.ambasdor-col-9 {
    padding: 51px;
}

.col-sm-6.ambasdor-col-9 h1.become-influencer{
    font-size: 36px;
    line-height: 48px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    color: #E3E8EF;

}
.col-sm-6.ambasdor-col-9 p.become-influencer-text{
   font-size: 16px;
    line-height: 24px;
    font-family: 'POPPINS';
    font-style: normal;
    font-weight: 400;
    color: #CDD5DF;
	margin-bottom:32px;
}
.col-sm-6.ambasdor-col-11
{
 padding: 51px;
}

.col-sm-6.ambasdor-col-11 h1.become-affliate
{
 font-size: 36px;
    line-height: 48px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    color: #E3E8EF;
}

.col-sm-6.ambasdor-col-11 p.become-affliate-text{
 font-size: 16px;
    line-height: 24px;
    font-family: 'POPPINS';
    font-style: normal;
    font-weight: 400;
    color: #CDD5DF;
	margin-bottom:32px;
}
.col-sm-12.ambasdor-center span.choose-btn {
    margin-left: 297px;
    margin-top: 20px;
}
.col-sm-6.py-5.ambasdor-col-13 .fieldset > .field input.input-text {height:48px;}
#maincontent .col-sm-6.py-5.ambasdor-col-13 fieldset.fieldset.create.info {
	margin-top: -45px;
	padding:0;
}
#maincontent .col-sm-6.py-5.ambasdor-col-13 fieldset.fieldset.create.account {padding:0;}
.create.info .field-name-firstname, .create.info .field-name-lastname {
    width: 48%;
    display: inline-block;
    margin-bottom: 0;
}
.create.info .field-name-firstname {
    margin-right: 4%;
}
.form-create-account .radio-btn {	
    position: absolute;
    top: -75px;
    width: max-content;
    left: -370px;
    margin: 0;
}
.ambasdor-center span.choose-btn {
    display: none;
}
   .col-sm-6.py-5.ambasdor-col-13 div#fullAddress {
    display: flex;
    justify-content: space-between;
   
}
.col-sm-6.py-5.ambasdor-col-13 div#fullname {
    display: flex;
    justify-content: space-between;
}
.col-sm-6.py-5.ambasdor-col-13 div#socialaddress {
    display: flex;
    justify-content: space-between;
}
.col-sm-6.py-5.ambasdor-col-13 button.btn.btn-success.center-form-btn {
    
    margin-top: 33px;
    margin-left: 204px;
    width: 201px;
    background: #046F4F;
    color: white;
}
.col-sm-6.py-5.ambasdor-col-13 input.form-control.form-control-lg.phoneno {
    width: 643px;
    font-size: 20px;
}
.col-sm-12.ambasdor-center h3.text-center.join-of-us {
    font-size: 40px;
    line-height: 48px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
}
.ambasdor-center.d-none.d-lg-block {margin-bottom:120px;}
.col-sm-12.ambasdor-center span.choose-btn button {
    font-size: 18px;
    font-weight: 400;
    font-style: normal;
    line-height: 16px;
}
.col-sm-4.ambasdor-col-3 .card img.card-img-top {
    margin-left: 54px;
}
.col-sm-4.ambasdor-col-5 .card img.arrowtwo {
    margin-right: 36px;
}
.col-sm-4.ambasdor-col-3 .card img.arrowone {
    margin-left: 280px;
}
span.choose-btn input {
    margin-bottom: -5px;
}
.row.py-5.ambasdor-row-2 img.mobile {
 display: none;

}
.row.py-5.ambasdor-row-2 img.desktop {
    margin-right: 52px;
 
}
.col-sm-6.py-5.ambasdor-col-13 .radio-btn {
    margin-left: 20px;
    margin-bottom: 20px;
}
.col-sm-6.py-5.ambasdor-col-13 .radio-btn input[type='radio'] {
    margin-bottom: -6px;
    margin-right: 8px;
    background: #FFFFFF;
    border: 2px solid #D0D5DD;
    width: 24px;
    height: 24px
}
input[type="radio"]:checked {
      border-color: #046F4F!important;
    }
div#join-us h3.text-center.join-of-us {
    margin-bottom: 113px;
}

    }
    @media only screen and (max-width: 600px) { 

   .col-sm-6.py-5.ambasdor-col-13 .radio-btn label.radio-inline {
    margin-right: 13px;
        }
        .col-sm-6.py-5.ambasdor-col-13 .radio-btn input[type='radio'] {
             margin-bottom: -5px;
        }
    .col-sm-6.ambasdor-col-1 h3.join-us {
    flex-flow: 1;
    font-size: 14px;
    font-style: normal;
    font-family: 'Poppins';
    line-height: 32px;
    display: flex;
    margin-top: 40px;
}
.col-sm-6.ambasdor-col-1 h1.influencer {
    font-size: 27px;
    line-height: 130%;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    margin-top: -32px;
}
span.ambasdor-button.py-5 {
    margin-top: -67px;
}
span.ambasdor-button.py-5 button.btn.btn-success.btn-1.m-2 {
    width: 130px;
    font-size: 10px;
    background: #046F4F;
    color: white;
}
span.ambasdor-button.py-5 button.btn.btn-secondary.btn-2.m-2 {
    width: 130px;
    font-size: 10px;
    background: border-box;
    color: #046F4F;
}
h2.py-3.text-center.part-of-us {
    font-size: 24px;
    line-height: 32px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;

    margin-top: 20px;
}
.col-sm-6.ambasdor-col-6 img {
    height: 140px;
    width: 140px;
}
.col-sm-6.ambasdor-col-7 h1.share-product {
    font-size: 20px;
    line-height: 28px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    color: #E3E8EF;
    margin-top:20px;
}
.col-sm-6.ambasdor-col-7 p.share-product-text {
    font-size: 14px;
    font-weight: 400;
    font-family: 'Poppins';
    font-style: normal;
    line-height: 20px;
    color: #CDD5DF;
}
span.join-us-btn {
    margin-left: -8px;
}
span.join-us-btn button.btn.btn-success.btn-1.ml-3 {
    background: #046F4F;
    color: white;
    
}

.col-sm-6.ambasdor-col-8 img {
    width: 140px;
    height: 140px;
}
.col-sm-6.ambasdor-col-9 h1.become-influencer {

    font-size: 20px;
    line-height: 28px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    color: #E3E8EF;
	margin-top:20px;
	}
	
	.col-sm-6.ambasdor-col-9 p.become-influencer-text
	{
	 font-size: 14px;
    font-weight: 400;
    font-family: 'Poppins';
    font-style: normal;
    line-height: 20px;
    color: #CDD5DF;
	}
	
	.col-sm-6.ambasdor-col-11 h1.become-affliate {
	  font-size: 20px;
    line-height: 28px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    color: #E3E8EF;
	margin-top:20px;
}

.col-sm-6.ambasdor-col-11 p.become-affliate-text
{
 font-size: 14px;
    font-weight: 400;
    font-family: 'Poppins';
    font-style: normal;
    line-height: 20px;
    color: #CDD5DF;

}
.choose-btn button {
    width: 100%;
    text-align: inherit;
}
.col-sm-12.ambasdor-center.d-block.d.lg-none h3.text-center.join-of-us {
    font-size: 24px;
    font-weight: 600;
    font-style: normal;
    line-height: 32px;
    font-family: 'Poppins';
    margin-top: -22px;
}
.col-sm-6.ambasdor-col-10 img {width: 140px; height: 140px;}
.row.py-5.ambasdor-row-2 img.desktop {display: none;}
.row.py-5.ambasdor-row-2 img.card-img-top {margin-left: 93px;}
.row.py-5.ambasdor-row-2 img.mobile {margin-left: 100px; margin-bottom: 26px;}
.row.py-5.ambasdor-row-2 h4.card-title.mt-5 {
    font-size: 20px;
    line-height: 32px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
	 color: #222529;
}
.row.py-5.ambasdor-row-2 p.card-text {
    font-size: 14px;
    line-height: 20px;
    font-weight: 400;
    font-style: normal;
    font-family: 'Poppins';
    color: #4B5565;
}
.col-sm-12.text-center.m-5.join-us button.btn.btn-success.center-btn {
    background: #046F4F;
    color: white;
    font-size: 14px;
    line-height: 11px;
    font-style: normal;
    font-weight: 500;
    font-family: 'Poppins';
    }
.col-sm-6.py-5.ambasdor-col-13 button.btn.btn-success.center-form-btn {
    display: flex;
    margin-left: 97px;
    margin-top: 23px;
    margin-bottom: -66px;
    background: #046F4F;
    color: white;
}
.col-sm-4.p-2 img.ceo {
    width: 166px;
    height: 208px;
    margin: 15px;
}
.col-sm-4.p-2 strong.follower {
    font-size: 18px;
    line-height: 20px;
    font-weight: 300;
    font-family: 'Poppins';
    font-style: normal;
    margin-left: 0;
	margin-bottom:25px;
	display: inline-block;
	color:#F0F0F0;
}
.col-sm-4.p-2 strong.ambasdor-ceo-title {
    font-size: 18px;
    line-height: 20px;
    font-weight: 500;
    font-family: 'Poppins';
    font-style: normal;
    margin-left: 20px;
	color:#F0F0F0;
}
.text p.ambasdor-text {
    font-size: 14px;
    line-height: 21px;
    font-weight: 400;
    font-family: 'Poppins';
    font-style: normal;
	padding: 5px;
}
.text p.ambasdor-text img.comma {margin-top: -28px; margin-left: 12px;}

    }
@media only screen and (max-width: 992px) {
	.ambasdor-row-1 .col-md-6.ambasdor-col-1 {padding-top:60px;}
	#maincontent .ambasdor-col-1 h1.influencer {
		font-weight: 600;
		font-size: 28px;
		line-height: 130%;
		max-width: 343px;
	}
	span.ambasdor-button.py-5 button.btn.btn-success.btn-1.m-2 {background: #046F4F; color: white;}
	#maincontent .btn {padding: 9px 30px; font-size:14px;}
	.ambasdor-button button {padding: 9px 0px;}
	.ambasdor-row-1 {background-size: 100vw 100vh;}
	.col-sm-12.text-center.m-5.join-us a button.btn.btn-success.center-btn {background: #046F4F; color: white;}
	.card-body img.mobile {display: none;}
	body h2.py-3.text-center.part-of-us {margin-top: 50px;}
	#maincontent .row.py-5.mt-4.ambassador-row.ambasdor-row-6 {margin-top: 60px!important; margin-bottom: 60px!important; padding-bottom: 0!important;}
	#maincontent .ambassador-row h1, #maincontent .ambassador-row p {color:#fff;}
	#maincontent .ambassador-row .card-body p {color: #333;}
	.col-sm-6.py-5.ambasdor-col-13 {flex: 100%!important; max-width: 100%!important; padding-top: 0!important;}
	.col-sm-6.py-5.ambasdor-col-13 .radio-btn label.radio-inline {
		margin-right: 0;
		font-size: 16px;
		width: 100%;
		height: 50px;
		margin-bottom: 15px;
	}
	.col-sm-6.py-5.ambasdor-col-13 fieldset.fieldset.create.info {padding:0; margin-top:30px;}
	.col-sm-6.py-5.ambasdor-col-13 fieldset.fieldset.create.account {padding:0;}
	.form.create.account .actions-toolbar {text-align: center; margin: 0 auto;}
	.form.create.account .actions-toolbar > .primary {display:inline-block;}
	.col-sm-6.py-5.ambasdor-col-13 .radio-btn input[type='radio'] {margin-right:10px;}
	#maincontent .form.create.account .actions-toolbar > .primary .action {line-height:19px;}
	#maincontent .ambassador-row .ambasdor-text {color: #333;}
	#maincontent span.join-us-btn .btn {border: 1px solid #046F4F;}
	#maincontent span.join-us-btn .btn-success {background: #046F4F; color: #E3E8EF;}
	#maincontent span.ambasdor-button .btn {padding: 9px 15px;}

}

@media only screen and (max-width:767px) {
	#maincontent .btn {padding: 9px 25px; max-width: 120px;}
	.join-us {font-size: 14px; margin: 0!important;}
	.ambasdor-col-2 {margin-top:30px;}
	.card-body img.mobile {display: block;}
	.card img.desktop {display:none;}
	.ambassador-row.ambasdor-row-2 {padding-top: 0!important;}
	.card-body h4 {margin-top:20px!important;}
	.card-body img.mobile {margin: 30px 0;}
	.row.py-5.ambasdor-row-2 p.card-text, .row.py-5.ambasdor-row-2 h4.card-title.mt-5 {text-align:center;}
	.row.py-5.ambasdor-row-2 img.card-img-top {margin:0 auto; display:block;}
	.row.py-5.ambasdor-row-2 img.mobile {margin:25px auto; display:block;}
	#maincontent .ambassador-row.ambasdor-row-2 .btn {padding: 8px 20px;}
	span.join-us-btn {margin-left:0;}
	.ambassador-row {padding-top: 20px!important;}
	#maincontent .ambassador-row h1 {margin-bottom:15px;}
	#maincontent .ambasdor-text {margin-top:0;}
	#maincontent .ambassador-row.ambasdor-row-7 .col-sm-7 {max-width: 100%; flex: 100%;}
	#maincontent .text .comma {left: 0;}
}
@media only screen and (max-width:601) {
	span.join-us-btn {margin-left: 0;}
}
    </style>