<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAdvancedBookingSystem
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?= /* @noEscape */ $block->getChildHtml("hotel-contact-info") ?>
<?= /* @noEscape */ $block->getChildHtml("hotel-booking-info") ?>
<?= /* @noEscape */ $block->getChildHtml("hotel-amenities-info") ?>
<?= /* @noEscape */ $block->getChildHtml("marketplace_product_add_configurable") ?>
<input type="hidden" name="configurable-matrix-serialized" value="1" />