<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpVendorAttributeManager
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    $myBlock = $block->getLayout()->createBlock(
        \Webkul\MpVendorAttributeManager\Block\Adminhtml\Group\Edit\Tab\Attributes::class
    );

    $gridJsObjectName = $myBlock->getJsObjectName();
    ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Webkul_MpVendorAttributeManager/js/group/assign-attributes": {
                "selectedAttributes": <?= /* @noEscape */ $myBlock->getSelectedAttrJson(); ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
