<?php
/**
 * Webkul Affiliate Banner template.
 * @category  Webkul
 * @package   Webkul_Affiliate
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$isAffiliate = $block->isAffiliate();
$affId = $isAffiliate['data']->getCustomerId();
$config = $block->getAffiliateConfig();
$block->getAllDetail($affId);

if ($isAffiliate && $config['enable']) {?>
    <fieldset class="info wk-affiliate-fieldset fieldset" id="affiliate-preferences">
       
        <form action="<?= /* @noEscape */  $block->getSaveAction() ?>" method="POST"  id="form-affiliate-prefer"
         data-mage-init='{"validation":{}}'>
        <?= /* @noEscape */  $block->getBlockHtml('formkey'); ?>
            <div class="fieldset form-list" id="cust">
                <div class="field">
                    <label class="label"><?= /* @noEscape */  __('Email Address')  ?>
                    <span style="color:red"> *</span> : </label>
                    <div class="control wk-width">
                        <textarea type="text" class="input-text required-entry multiple-emails" 
                        id="wk_emailcampaign_id" title="Email Address" name="email"></textarea>
                        <p><?= /* @noEscape */ __('add multiple email address using comma (,) separate')?></p>
                   </div>
                </div>
                <div class="field">
                    <label class="label"><?= /* @noEscape */  __('Subject') ?>
                    <span style="color:red"> *</span> : </label>
                    <div class="control wk-width">
                        <input type="text" class="input-text required-entry" title="Subject" name="subject">
                   </div>
                </div>
                <div class="field">
                    <label class="label"><?= /* @noEscape */  __('Message') ?>
                    <span style="color:red"> *</span> : </label>
                      <div class="control wk-width">
                        <textarea type="text" id="textshow" class="input-text required-entry email_message" 
                        title="Message" name="message"></textarea>
                   </div>
                       </div>
                </div>


            <div class="actions-toolbar showData">
                <div class="primary">
                    <button title="Save" id="show1" class="action save primary" type="submit">
                        <span><?= /* @noEscape */ __('Send mail')?></span>
                    </button>
                </div>
            </div>
        </form>
    </fieldset>
    <script type="text/x-magento-init">
    {
        "*": {
            "showAllData": {}
        }
    }
    </script>
<?php } ?>
