<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpVendorAttributeManager
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    $quickOrderBlock = $block->getLayout()->createBlock(
        \Webkul\B2BMarketplace\Block\Supplier\Profile\QuickOrder::class
    );
    $helper = $quickOrderBlock->helper('Webkul\B2BMarketplace\Helper\Data');
    $viewModel = $block->getViewModel();
    $passwordLength = $viewModel->getConfigPasswordLength() ?? '8';
    $charLength = $viewModel->getConfigCharLength() ?? '3';
    $baseUrl = $viewModel->getBaseUrl()."pub/media/b2b/";
    $url = '/static/frontend/Smartwave/porto_child/en_US/Webkul_B2BMarketplace/images/Registration.png';
    ?>
      <div class="container-fluid">
                <div class="row py-3">
                <div class="col-lg-6 col-md-12 col-sm-12 left-image register-page d-none d-lg-block" style="background-image: url('<?php echo $url ?>'); background-repeat:no-repeat;">
				<div class="vh-center">
				<div class="content">
				<img src="<?= /* @noEscape */ $block->getViewFileUrl( 'Webkul_B2BMarketplace/images/Logo-green.png') ?>" width="100px" height="100px" class="m-5" >
						<h1  class="m-3" style="color:white;"> Become  seller</h1>
						<h3 class="m-3"  style="color:white;">You will need only 3 things to start selling on Enjoyp</h3>
                                    <ul  style="color:white;">
                                    <li>GST details</li>
                                    <li>Pan details</li>
                                    <li>Active Bank Account</li>
                                    </ul> 
                            </h3>
                        </div>
					</div>						
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-12 right-form">
						<div class="page-title">
							<span class="base register-sign-in" data-ui-id="page-title-wrapper"><?= /* @noEscape */ __("Register as Supplier"); ?></span>
						</div>
					<form 
					method="post" 
					action="<?= /* @noEscape */ $quickOrderBlock->getUrl('b2bmarketplace/supplier/createPost'); ?>" 
					id="wk-supplier-create-form" enctype="multipart/form-data" data-mage-init='{"validation":{}}'
					>
					<?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
					<div class="wk-supplier-continer">
						<div class="wk-loading-mask wk-display-none">
							<div class="wk-loader"></div>
						</div>
						<div class="wk-signup-step-tab-container">
							<div class="wk-signup-step-tab wk-active-tab">
								<div class="wk-signup-step-tab-icon circle"">
									<img src="<?= /* @noEscape */ $block->getViewFileUrl(
										'Webkul_B2BMarketplace/images/account.png'
									) ?>" >
								</div>
								<span><?= /* @noEscape */ __("Accounts "); ?><?= /* @noEscape */ __("Information"); ?></span>
							</div>
							<div class="wk-signup-step-tab">
								<div class="wk-signup-step-tab-icon">
									<img class="wk-active-icon" src="<?= /* @noEscape */
									$block->getViewFileUrl('Webkul_B2BMarketplace/images/personal-info.png') ?>">
									<img class="wk-deactive-icon" src="<?= /* @noEscape */
									$block->getViewFileUrl('Webkul_B2BMarketplace/images/personal-info.png') ?>">
								</div>
								<span><?= /* @noEscape */ __("Personal "); ?><?= /* @noEscape */ __("Information"); ?></span>
							</div>
							<div class="wk-signup-step-tab wk-final-step-tab">
								<div class="wk-signup-step-tab-icon">
									<img class="wk-active-icon" src="<?= /* @noEscape */
									$block->getViewFileUrl('Webkul_B2BMarketplace/images/done.png') ?>">
									<img class="wk-deactive-icon" src="<?= /* @noEscape */
									$block->getViewFileUrl('Webkul_B2BMarketplace/images/done.png') ?>">
								</div>
								<span><?= /* @noEscape */ __("You are "); ?><?= /* @noEscape */ __("Done"); ?></span>
							</div>
						</div>
						<div class="wk-signup-step-panel-container">
							<div class="wk-signup-step-panel wk-signup-step-account-info">
								<fieldset class="fieldset">
									<div class="field required">
										<label class="label" for="supplier-email">
											<span><?= /* @noEscape */ __("Email Address"); ?></span>
										</label>
										<div class="control">
											<input type="email" data-validate="{required:true, 'validate-email':true}" 
											class="input-text required-entry" title="<?= /* @noEscape */ __("Email Address"); ?>" 
											id="supplier-email" name="email">
										</div>
									</div>
									<div class="field email required">
										<label for="supplier-password" class="label">
											<span><?= /* @noEscape */ __("Password"); ?></span>
										</label>
										<div class="control">
											<input type="password" 
											data-validate="{required:true, 'validate-customer-password':true}" 
											data-password-min-length="<?= /* @noEscape */ $passwordLength; ?>" 
											data-password-min-character-sets="<?= /* @noEscape */ $charLength; ?>" 
											title="<?= /* @noEscape */ __("Password"); ?>" class="input-text required-entry" 
											id="supplier-password" name="password">
										</div>
									</div>
									<div class="field email required">
										<label for="supplier-password" class="label">
											<span><?= /* @noEscape */ __("Confirm Password"); ?></span>
										</label>
										<div class="control">
											<input type="password" data-validate="{required:true, equalTo:'#supplier-password'}" 
											title="<?= /* @noEscape */ __("Confirm Password"); ?>" 
											class="input-text required-entry" 
											id="supplier-re-password" name="password_confirmation">
										</div>
									</div>
									<div class="actions-toolbar">
										<div class="primary">
											<button id="proceed" name="proceed" 
											class="wk-proceed-btn action login primary" type="button">
												<span><?= /* @noEscape */ __("Proceed"); ?></span>
											</button>
										</div>
									</div>
									<div class="secondary wk-secondary">
							
						  
										<span class="proceed-below  footer-reg" >
											<p class="already"> Already  register as supplier? </p><p class="wk-supplier-registration-link">
												<a href="<?= /* @noEscape */ $block->getUrl('b2bmarketplace/supplier/login')?>" class="sign-in">
													<?= /* @noEscape */ __(' Supplier Sign In')?>
												</a>
											</p>
										</span>
									  </div>
								</fieldset>
							</div>

							<div class="wk-signup-step-panel wk-signup-step-personal-info wk-display-none">
								<fieldset class="fieldset">
									<div class="field required">
										<label class="label" for="supplier-first-name">
											<span><?= /* @noEscape */ __("First Name"); ?></span>
										</label>
										<div class="control">
											<input type="text" data-validate="{required:true}" class="input-text required-entry" 
											title="<?= /* @noEscape */ __("First Name"); ?>" 
											id="supplier-first-name" name="firstname">
										</div>
									</div>
									<div class="field required">
										<label class="label" for="supplier-last-name">
											<span><?= /* @noEscape */ __("Last Name"); ?></span>
										</label>
										<div class="control">
											<input type="text" data-validate="{required:true}" 
											class="input-text required-entry" 
											title="<?= /* @noEscape */ __("Last Name"); ?>" 
											id="supplier-last-name" name="lastname">
										</div>
									</div>
									<div class="field required">
										<label class="label" for="supplier-phone">
											<span><?= /* @noEscape */ __("Phone"); ?></span>
										</label>
										<div class="control">
											<input type="text" data-validate="{required:true}" 
											class="input-text required-entry" 
											title="<?= /* @noEscape */ __("Phone"); ?>" 
											id="supplier-phone" name="telephone">
										</div>
									</div>
									<div class="field required">
										<label class="label" for="supplier-company"><span><?= /* @noEscape */
										__("Company Name"); ?></span>
										</label>
										<div class="control">
											<input type="text" data-validate="{required:true}" 
											class="input-text required-entry" 
											title="<?= /* @noEscape */ __("Company Name"); ?>" 
											id="supplier-company" name="company">
										</div>
									</div>
									<div class="field required">
										<label class="label" for="supplier-company-url">
											<span><?= /* @noEscape */ __("Company Url"); ?></span>
										</label>
										<div class="control" id="wk-mp-become-seller-box-wrapper" 
										data-role="wk-mp-become-seller-box-wrapper">
											<input type="text" data-validate="{required:true}" class="input-text required-entry" 
											title="<?= /* @noEscape */ __("Company Url"); ?>" id="supplier-company-url" 
											name="company_url">
											<div id="wk-load" class="no-display">
												<img height="16px" width="16px" src="<?= /* @noEscape */
												$quickOrderBlock->getViewFileUrl(
													'Webkul_Marketplace::images/ajax-loader-tr.gif'
												) ?>" />
											</div>
											<span> 
												(<?= /* @noEscape */ __('This will be used to display your public profile')?>)
											</span>
										</div>
									</div>
								</fieldset>
								<fieldset class="fieldset">
									<div class="wk-signup-step-sub-title"><?= /* @noEscape */
									__("Address Information"); ?></div>
									<div class="field required">
										<label class="label" for="supplier-country">
											<span><?= /* @noEscape */ __("Country"); ?></span>
										</label>
										<div class="control">
											<?= /* @noEscape */ $viewModel->getCountryHtmlSelect(); ?>
										</div>
									</div>
									<div class="field region required">
										<label class="label" for="region_id">
											<span><?= /* @noEscape */ $block->escapeHtml(__('State/Province')) ?></span>
										</label>
										<div class="control">
											<select id="region_id" name="region_id"
													title="<?= /* @noEscape */ $block->escapeHtmlAttr(__('State/Province')) ?>"
													class="validate-select" <?= /* @noEscape */
													!$helper->getConfig(
														'general/region/display_all'
													) ? ' disabled="disabled"' : '' ?>>
												<option value=""><?= /* @noEscape */
												$block->escapeHtml(__('Please select a region, state or province.')) ?></option>
											</select>
											<input type="text"
												id="region"
												name="region"
												value=""
												title="<?= /* @noEscape */ $block->escapeHtmlAttr(__('State/Province')) ?>"
												class="input-text <?= /* @noEscape */ $block->escapeHtmlAttr(
													$viewModel->helper(
														\Magento\Customer\Helper\Address::class
													)->getAttributeValidationClass('region')
												) ?>"<?=
													!$helper->getConfig(
														'general/region/display_all
														'
													) ? ' disabled="disabled"' : '' ?>/>
										</div>
									</div>
									<div class="field required">
										<label class="label" for="supplier-city">
											<span><?= /* @noEscape */ __("City"); ?></span>
										</label>
										<div class="control">
											<input type="text" data-validate="{required:true}" 
											class="input-text required-entry" 
											title="<?= /* @noEscape */ __("City"); ?>" 
											id="supplier-city" name="city">
										</div>
									</div>
									<div class="field required">
										<label class="label" for="supplier-address">
											<span><?= /* @noEscape */ __("Address Line"); ?></span>
										</label>
										<div class="control">
											<input type="text" data-validate="{required:true}" 
											class="input-text required-entry" 
											title="<?= /* @noEscape */ __("Address Line"); ?>" 
											id="supplier-address" name="street[]">
										</div>
									</div>
									<div class="field required">
										<label class="label" for="supplier-postcode">
											<span><?= /* @noEscape */ __("Zip/Postal Code"); ?></span>
										</label>
										<div class="control">
											<input type="text" data-validate="{required:true}" 
											class="input-text required-entry" 
											title="<?= /* @noEscape */ __("Zip/Postal Code"); ?>" 
											id="supplier-postcode" name="postcode">
										</div>
									</div>
									<?= $block->getChildHtml('mpgdpr.customer.agreement'); ?>
									<!-- Code for MpVendorAttributeManager module start -->
									<?= $block->getChildHtml('custom_vendor_attributes');?>
									<?= $block->getChildHtml('account_create_privacy_condition');?>
									<?= $block->getChildHtml('style_template');?>
									<!-- Code for MpVendorAttributeManager module end -->
									<div class="actions-toolbar">
										<div class="primary">
											<button id="register" name="register" 
											class="action login primary wk-register-btn" type="button">
												<span><?= /* @noEscape */ __("Register"); ?></span>
											</button>
										</div>
									</div>
								</fieldset>
							</div>

							<div class="wk-signup-step-panel wk-display-none wk-signup-step-final">
								<div class="wk-signup-complete">
									<div class="wk-signup-complete-logo"><img src="<?= /* @noEscape */ $block->getViewFileUrl(
													'Webkul_B2BMarketplace/images/check.png'
												) ?>"></div>
									<div class="wk-signup-complete-title"><?= /* @noEscape */__("Valid, Account Created!"); ?></div>
									<div class="wk-signup-complete-msg"><?= /* @noEscape */
									__("You have successfully registered as Supplier with us."); ?></div>
									<div class="wk-signup-complete-btn-container">
										<a href="<?= /* @noEscape */ $quickOrderBlock->getUrl(
											'b2bmarketplace/supplier/account'
										); ?>" 
										class="wk-signup-complete-dashboard-btn">
											<?= /* @noEscape */ __("Go to Dashboard"); ?>
										</a>
									</div>
									<div class="wk-supplier-feature-container">
										<div class="wk-supplier-feature">
											<div class="wk-supplier-feature-logo">
												<img src="<?= /* @noEscape */ $block->getViewFileUrl(
													'Webkul_B2BMarketplace/images/document.png'
												) ?>">
											</div>
											<div class="wk-supplier-feature-content">
												<div class="wk-supplier-feature-title"><?= /* @noEscape */ __(
													"Create a MicroSite"
												); ?></div>
												<div class="wk-supplier-feature-info">
													<?= /* @noEscape */ __(
														"You can setup and customize your very own MicroSite for free, ".
														"where you can showcase your information and products."
													); ?>
												</div>
											</div>
										</div>
										<div class="wk-supplier-feature">
											<div class="wk-supplier-feature-logo">
												<img src="<?= /* @noEscape */
												$block->getViewFileUrl('Webkul_B2BMarketplace/images/list.png') ?>">
											</div>
											<div class="wk-supplier-feature-content">
												<div class="wk-supplier-feature-title"><?= /* @noEscape */ __(
													"Choose Relevant Categories"
												); ?></div>
												<div class="wk-supplier-feature-info">
													<?= /* @noEscape */ __(
														"You can choose the categories you want to sell for".
														"and you will only receive relevant product quotations."
													); ?>
												</div>
											</div>
										</div>
										<div class="wk-supplier-feature">
											<div class="wk-supplier-feature-logo">
												<img src="<?= /* @noEscape */
												$block->getViewFileUrl('Webkul_B2BMarketplace/images/shield.png') ?>">
											</div>
											<div class="wk-supplier-feature-content">
												<div class="wk-supplier-feature-title"><?= /* @noEscape */ __(
													"Get Premium Badge"
												); ?></div>
												<div class="wk-supplier-feature-info">
													<?= /* @noEscape */ __(
														"You can verify your business and become a Preminum Supplier".
														"for free to receive relatively more quotations."
													); ?>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>


	</div>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */
                $viewModel->getConfigRegionDisplay() ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#supplier-postcode",
                "form": "#wk-supplier-create-form",
                "regionJson": <?= /* @noEscape */ $viewModel->helper(
                    \Magento\Directory\Helper\Data::class
                )->getRegionJson() ?>,
                "defaultRegion": "",
                "countriesWithOptionalZip": <?= /* @noEscape */ $viewModel->helper(
                    \Magento\Directory\Helper\Data::class
                )->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'Magento_Customer/js/customer-data',
        'mage/mage'
    ], function($, alertBox, customerData) {
        var warningLable = "Warning";
        $(document).ready(function() {
            $('body').delegate('#supplier-company-url', 'keyup', function () {
                var shopUrlVal = $(this).val();
                $('#supplier-company-url').val(shopUrlVal.replace(/[^a-z^A-Z^0-9\.\-]/g,''));
            });
            $('body').delegate('#supplier-company-url', 'change', function () {
                var self = this;
                var shopUrlVal = $('#supplier-company-url').val();
                $('.available').remove();
                $('.unavailable').remove();
                if (shopUrlVal) {
                    $('#wk-load').removeClass('no-display');
                    $.ajax({
                        type: "POST",
                        url: '<?= /* @noEscape */
                        $block->getUrl(
                            "marketplace/seller/usernameverify",
                            ["_secure" => $quickOrderBlock->getRequest()->isSecure()]
                        )?>',
                        data: {
                            profileurl: shopUrlVal
                        },
                        success: function (response) {
                            $('#wk-load').addClass('no-display');
                            if (response===0) {
                                $('[data-role="wk-mp-become-seller-box-wrapper"]').append(
                                    $('<div/>').addClass('available message success')
                                    .text('<?= /* @noEscape */ __("Congratulations! Shop name is available.") ?>')
                                );
                            } else {
                                $('#supplier-company-url').val('');
                                $('[data-role="wk-mp-become-seller-box-wrapper"]').append(
                                    $('<div/>').addClass('available message error')
                                    .text('<?= /* @noEscape */ __(
                                        "Sorry! But this shop name is not available, please set another shop name."
                                    ) ?>')
                                );
                            }
                        },
                        error: function (response) {
                            alertBox({
                                content: $t('There was error during verifying seller shop data')
                            });
                        }
                    });
                }
            });

            $(".wk-proceed-btn").click(function() {
                var dataForm = $('#wk-supplier-create-form');
                dataForm.mage('validation', {});
                if (dataForm.validation('isValid')) {
                    showLoader();
                    $.ajax({
                        url: "<?= /* @noEscape */ $quickOrderBlock->getUrl('b2bmarketplace/supplier/validate'); ?>",
                        type: 'POST',
                        data: { email : $("#supplier-email").val() },
                        dataType: 'json',
                        success: function (data) {
                            if (data.error) {
                                if (data.msg) {
                                    hideLoader();
                                    alertBox({
                                        title: warningLable,
                                        content: "<div class='wk-mprma-warning-content'>"+data.msg+"</div>",
                                        actions: {
                                            always: function () {
                                                if (data.reload) {
                                                    if (data.redirect) {
                                                        window.location = data.redirect;
                                                    } else {
                                                        location.reload(true);
                                                    }
                                                }
                                            }
                                        }
                                    });
                                }
                            } else {
                                customerData.reload([''], true);
                                $(".wk-signup-step-panel").removeClass("wk-display-none");
                                $(".wk-signup-step-panel").addClass("wk-display-none");
                                $(".wk-signup-step-personal-info").removeClass("wk-display-none");
                                $(".wk-signup-step-tab").addClass("wk-active-tab");
                                $(".wk-final-step-tab").removeClass("wk-active-tab");
                                hideLoader();
                            }
                        }
                    });
                } else {
                }
            });

            $(".wk-register-btn").click(function() {
                var dataForm = $('#wk-supplier-create-form');
                dataForm.mage('validation', {});
                if (dataForm.validation('isValid')) {
                    showLoader();
                    $.ajax({
                        url: "<?= /* @noEscape */ $quickOrderBlock->getUrl('b2bmarketplace/supplier/register'); ?>",
                        type: 'POST',
                        data: $('#wk-supplier-create-form').serialize(),
                        dataType: 'json',
                        success: function (data) {
                            if (data.error) {
                                hideLoader();
                                alertBox({
                                    title: warningLable,
                                    content: "<div class='wk-mprma-warning-content'>"+data.msg+"</div>",
                                    actions: {
                                        always: function () {
                                            if (data.reload) {
                                                location.reload(true);
                                            }
                                        }
                                    }
                                });
                            } else {
                                $(".wk-signup-step-panel").removeClass("wk-display-none");
                                $(".wk-signup-step-panel").addClass("wk-display-none");
                                $(".wk-signup-step-final").removeClass("wk-display-none");
                                $(".wk-signup-step-tab").addClass("wk-active-tab");
                                hideLoader();
                            }
                        }
                    });
                } else {
                }
            });
            
            $('body').on('keyup', '.wk-signup-step-panel input', function (e) {
                if (e.keyCode == 13) {
                    $(this).closest(".wk-signup-step-panel").find("button").trigger("click")
                }
            });
        });

        function showLoader() {
            $(".wk-loading-mask").removeClass("wk-display-none");
        }

        function hideLoader() {
            $(".wk-loading-mask").addClass("wk-display-none");
        }
    });
</script>
<style>
.layout-1220 .block.category.event, .layout-1220 .footer.content, .layout-1220 .header.content, .layout-1220 .navigation, 
.layout-1220 .page-main, .layout-1220 .page-wrapper>.breadcrumbs >ul, .layout-1220 .page-wrapper>.page-bottom, 
.layout-1220 .page-wrapper>.widget,.page-header.type15 .header-main .header.content {max-width: 100%;}
.container-fluid {padding:0;}
#maincontent {padding: 0;}
.m-2 {margin:0!important;}
.ml-5, .mx-5 {margin-left: 0!important;}
.pt-3, .py-3 {padding-top:0!important; padding-bottom:0!important;}
.page-header .header-main {max-width: 88%; margin: 0 auto;}
.left-image {padding-top: inherit!important; background-size: cover; height:120vh;}
.vh-center {
	display: -webkit-flexbox;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    -webkit-flex-align: center;
    -ms-flex-align: center;
    -webkit-align-items: center;
    align-items: center;
    justify-content: center;
    display: -webkit-box;
    -webkit-box-pack: center;
    -webkit-box-align: center;
	width: 100%;
    height: 100%;
}
.left-image img {margin: 0 0 30px 0!important;}
.left-image h1 {font-size:40px; line-height:normal;}
span.sign-in-as-supplier, span.base.register-sign-in {
	letter-spacing: -0.02em;
    color: #222529;
    font-size: 32px;
    line-height: 44px;
    display: block;
    margin: 0 auto;
    text-align: center;
}
.right-form {padding: 80px 60px 0 60px;}
#maincontent label {
	font-size: 14px;
    line-height: 20px;
    color: #222529;
    margin-bottom: 0;
}
#maincontent fieldset.wk-supplier-login input {
	height: 48px;
    background: #FFFFFF;
    border: 1px solid #D0D5DD;
    box-shadow: 0px 1px 2px rgba(16, 24, 40, 0.05);
}
#maincontent fieldset.wk-supplier-login .primary, #maincontent #wk-supplier-create-form .primary, #maincontent  #wk-supplier-create-form .actions-toolbar {margin: 0 auto; text-align: center; float: none;}
#maincontent fieldset.wk-supplier-login .actions-toolbar  {margin: 25px auto; text-align: center;}
#maincontent #wk-supplier-create-form .actions-toolbar {margin: 20px auto;}
#maincontent button.login {
	background: #046F4F;
    box-shadow: 0px 1px 2px rgba(16, 24, 40, 0.05);
    color: #fff;
    font-size: 16px;
    line-height: 24px;
    text-transform: none;
    letter-spacing: 0;
    padding: 14px 55px;
	margin-bottom: 30px;
}
.footer-reg {margin: 0 auto; text-align: center; display: block;}
.footer-reg p {
	font-size: 16px;
    line-height: 24px;
    display: inline-block;
    letter-spacing: -0.02em;
    color: #4B5565;
}
.fieldset.wk-supplier-login, .wk-supplier-continer {width:100%;}
.porto-block-html-top {display:none;}
footer .single-subscribe .newsletter .input-text {z-index:1!important;}
.wk-supplier-registration-link a:before {top:-1px;} 
.wk-signup-step-tab-icon {
	background: rgba(75, 85, 101, 0.16);
    width: 40px;
    height: 40px;
    padding: 6px;
    border-radius: 40px;
    text-align: center;
    margin: 0 auto;
}
.wk-signup-step-tab-icon  img {width:20px;}
.wk-signup-step-tab-container span {
	font-size: 16px;
    line-height: 24px;
    display: inline-block;
    align-items: center;
    letter-spacing: -0.02em;
    color: #4B5565;
    text-align: center;
    margin: 10px auto 0 auto;
}
.page-header.sticky-header .header-main {max-width:100%;}
.page-header.sticky-header .header-main .header.content {max-width: 88%;}
body #maincontent .bottom-section .wk-list-container-wrapper {
    width: 95%;
} 
@media only screen and (max-width: 1499px) {
	.wk-signup-step-tab-container span {height:50px;}
}
@media only screen and (max-width: 991px) {
	span.sign-in-as-supplier {font-size: 24px;line-height: 32px;}
	.right-form {padding:30px;}
	.wk-mp-login-container {border-top: 1px solid #E3E3E3;}
	span.sign-in-as-supplier, span.base.register-sign-in {font-size: 24px; line-height: 32px;}
	.wk-signup-step-tab-container span {font-size: 14px; line-height: 18px;}
} 
</style>
<style>
    
    </style>