<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAdvancedBookingSystem
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php $product = $block->getProduct(); ?>
<?php
$viewModel = $block->getBookingViewModel();
if ($viewModel === null) {
    $viewModel = $block->getLayout()->createBlock(
        \Webkul\MpAdvancedBookingSystem\Block\GetViewModel::class
    )->getBookingViewModel();
}

$productId = $product->getId();
$helper = $viewModel->getHelper();

$bookingInfo = $helper->getBookingInfo($productId);
$bookingType = $bookingInfo['type'];

$data = $viewModel->getDefaultBookingProductData($product);
?>
<?php if ($bookingType == 1 || $bookingType == 2): ?>
    <div class="wk-bg-container">
        <div class="wk-box-modal">
            <div class="wk-box-modal-bg">
                <div class="wk-loader"></div>
            </div>
            <div class="wk-modal-head">
                <div class="wk-close">X</div>
                <?= /* @noEscape */ __("Select Slot To Book"); ?>
            </div>
            <div class="wk-modal-body">
                <div class="wk-wrapper">
                    <div class="wk-calendar-container">
                        <div class="wk-booking-table wk-calendar-table">
                            <?= /* @noEscape */ $helper->getAllCalendars($productId); ?>
                        </div>
                    </div>
                    <div class="wk-day-container">
                        <div class="wk-booking-table">
                            <div class="wk-booking-table-head">
                                <div class="wk-selected-date-wrapper">
                                    <div class="wk-selected-date"></div>
                                    <div class="wk-selected-month-day">
                                        <div class="wk-month"></div>
                                        <div class="wk-selected-day"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="wk-booking-table-body">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="wk-modal-foot">
                <div class="wk-notation-wrapper">
                    <label class="label"><?= /* @noEscape */ __("Notation") ?></label>
                    <div class="noations-group">
                        <span class="available-slots notation-slots">
                            <?= /* @noEscape */ __("Available Slots") ?>
                        </span>
                        <span class="not-available-slots notation-slots">
                            <?= /* @noEscape */ __("Unavailable Slots") ?>
                        </span>
                        <span class="already-booked-slots notation-slots">
                            <?= /* @noEscape */ __("Booked Slots") ?>
                        </span>
                    </div>
                </div>
                <div class="wk-slots-summary-wrapper" style="display:none">
                    <div class="slots-summary">
                        <label class="label"><?= /* @noEscape */ __("Summary") ?></label>
                        <div class="booked-slot-summary"></div>
                    </div>
                    <div class="add cart button">
                        <button type="button" class="wk-book action tocart primary">
                            <?= /* @noEscape */ __("Book Now"); ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "body": {
            "Webkul_MpAdvancedBookingSystem/js/bookingsystem": <?= /* @noEscape */ $data ?>
        }
    }
</script>
