<?php
/**
 * Webkul Software
 *
 * @category  Webkul
 * @package   Webkul_Mpquotesystem
 * @author    Webkul
 * @copyright Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
if ($block->isQuoteProductInCart()) { ?>
    <div class="quote-pro-in-cart">
        <h4 class="wk_option_select_message">
            <?= $block->escapeHtml(__("Multi-Address checkout is not available for Quote Products"))?>
        </h4>
    </div>
<?php } ?>