<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Mpsplitorder
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div class="checkout-success">
    <?php if ($block->getOrderId()) { ?>
        <?php if (count($block->getOrderArray()) > 1) { ?>
            <p><?=$block->escapeHtml(__('Your orders # are:')); ?> </p> 
            <?php
            $flag = false;
            foreach ($block->getOrderArray() as $key => $orderValue) {
                if ($flag) {
                    echo ",";
                }
                $flag = true;
                if ($block->getCanViewOrder()) {  ?>
                    <a href="<?=$block->escapeHtml($orderValue['view_order_id']) ?>">
                    <?=$block->escapeHtml($orderValue['order_id']) ?> </a>
                <?php } else { ?>
                     <?=$block->escapeHtml($orderValue['order_id']) ?>
                <?php  }?>
            <?php }
        } else {
            if ($block->getCanViewOrder()) { ?>
<p><?=$block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number">
<strong>%s</strong>
</a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
            <?php } else { ?>        
            <p><?= $block->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php }?>
            
        <?php } ?>
<?php } ?><p>
<?=$block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')); ?>
</p>

    <?=$block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?=$block->escapeUrl($block->getUrl()); ?>">
            <span><?=$block->escapeHtml(__('Continue Shopping')); ?></span></a>
        </div>
    </div>
</div>
<?php $block->removeData(); ?>
