<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpVendorAttributeManager
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>

<script>
    require([
        'jquery',
        'mage/mage',
        'mage/translate'
    ], function($){
      $('body').on('click','.wk-ui-datepicker-trigger',function(){
          $(this).next().focus()
      });
    }
);
</script>
