<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAdvancedBookingSystem
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$product = $block->getProduct();
$helper = $this->helper(\Webkul\MpAdvancedBookingSystem\Helper\Data::class);
$bookingAvailableFrom = '';
$bookingAvailableTo = '';
$productSetId = '';
$bookingSlotData = $helper->getJsonEcodedString([]);

if (!empty($product) && !empty($product['entity_id'])) {
    if ($product['booking_available_from'] != 'Invalid date') {
        $bookingAvailableFrom = $product['booking_available_from'];
    }
    if ($product['booking_available_to'] != 'Invalid date') {
        $bookingAvailableTo = $product['booking_available_to'];
    }
    $bookingInfo = $helper->getBookingInfo($product->getId());
    if (!empty($bookingInfo['info'])) {
        $bookingSlotData = $bookingInfo['info'];
    }
    $productSetId = $product->getAttributeSetId();
    $appointmentType = $helper->getProductAttributeSetIdByLabel('Appointment Booking');
    if ($productSetId != $appointmentType) {
        $bookingSlotData = [];
        $bookingSlotData = $helper->getJsonEcodedString($bookingSlotData);
    }
} ?>
<div class="admin__field _required">
    <label class="admin__field-label" for="wk-slot-duration">
        <span data-config-scope="[GLOBAL]">
            <?= $block->escapeHtml(__('Slot Duration'))?> (<?= $block->escapeHtml(__('Mins'))?>)
        </span>
    </label>
    <div class="admin__field-control">
        <input class="admin__control-text required-entry validate-digits" type="text"
               data-form-part="product_form" name="product[slot_duration]"
               value="<?= $block->escapeHtml($product['slot_duration'])?>" id="wk-slot-duration">
    </div>
</div>
<div class="admin__field _required">
    <label class="admin__field-label" for="wk-break-time-bw-slot">
        <span data-config-scope="[GLOBAL]">
            <?= $block->escapeHtml(__('Break Time b/w Slots'))?> (<?= $block->escapeHtml(__('Mins'))?>)
        </span>
    </label>
    <div class="admin__field-control">
        <input class="admin__control-text required-entry validate-digits"
               type="text" data-form-part="product_form" name="product[break_time_bw_slot]"
               value="<?= $block->escapeHtml($product['break_time_bw_slot'])?>" id="wk-break-time-bw-slot">
    </div>
</div>
<div class="admin__field _required" data-index="show_contact_btn">
    <label class="admin__field-label" for="wk-prevent-scheduling-before">
        <span data-config-scope="[GLOBAL]">
            <?= $block->escapeHtml(__('Prevent Scheduling(Mins)'))?>
        </span>
    </label>
    <div class="admin__field-control">
        <input class="admin__control-text required-entry validate-digits"
               type="text" data-form-part="product_form" name="product[prevent_scheduling_before]"
               id="wk-prevent-scheduling-before"
               value="<?= $block->escapeHtml($product['prevent_scheduling_before'])?>">
    </div>
</div>
<div class="admin__field">
    <label class="admin__field-label" for="wk-available-every-week">
        <span data-config-scope="[GLOBAL]">
            <?= $block->escapeHtml(__('Available Every Week'))?>
        </span>
    </label>
    <div class="admin__field-control">
        <div class="admin__actions-switch" data-role="switcher">
            <input type="checkbox" class="admin__actions-switch-checkbox"
                   data-form-part="product_form" id="wk-available-every-week"
                   name="product[available_every_week]"
                   value="<?= $block->escapeHtml($product['available_every_week'])?>">
            <label class="admin__actions-switch-label" for="wk-available-every-week">
                <span class="admin__actions-switch-text" data-bind="
                    attr: {
                        'data-text-on': toggleLabels.on,
                        'data-text-off': toggleLabels.off
                    }" data-text-on="Yes" data-text-off="No"></span>
            </label>
        </div>
    </div>
</div>
<div class="admin__field _required wk-booking-date-block"
        <?php if ($product['available_every_week']) { ?>style="display: none;"<?php }?>>
    <label class="admin__field-label" for="wk-booking-available-from">
        <span data-config-scope="[GLOBAL]">
            <?= $block->escapeHtml(__('Available From'))?>
        </span>
    </label>
    <div class="admin__field-control admin__control-grouped-date admin__control-grouped">
        <div class="admin__field admin__field-date">
            <div class="admin__field-control">
                <input class="admin__control-text required-entry" data-form-part="product_form"
                       id="wk-booking-available-from" type="text" name="product[booking_available_from]"
                       value="<?= $block->escapeHtml($bookingAvailableFrom)?>" readonly/>
            </div>
        </div>
        <div class="admin__field admin__field-date">
            <label class="admin__field-label">
                <span><?= $block->escapeHtml(__('To'))?></span>
            </label>
            <div class="admin__field-control">
                <input class="admin__control-text required-entry" data-form-part="product_form"
                       id="wk-booking-available-to" type="text" name="product[booking_available_to]"
                       value="<?= $block->escapeHtml($bookingAvailableTo)?>" readonly/>
            </div>
        </div>
    </div>
</div>
<div class="admin__field">
    <label class="admin__field-label" for="wk-slot-all-days">
        <span data-config-scope="[GLOBAL]">
            <?= $block->escapeHtml(__('Same Slot for All Days'))?>
        </span>
    </label>
    <div class="admin__field-control">
        <div class="admin__actions-switch" data-role="switcher">
            <input type="checkbox" class="admin__actions-switch-checkbox"
                   data-form-part="product_form" id="wk-slot-all-days"
                   name="product[slot_for_all_days]"
                   value="<?= $block->escapeHtml($product['slot_for_all_days'])?>">
            <label class="admin__actions-switch-label" for="wk-slot-all-days">
                <span class="admin__actions-switch-text" data-bind="
                    attr: {
                        'data-text-on': toggleLabels.on,
                        'data-text-off': toggleLabels.off
                    }" data-text-on="Yes" data-text-off="No"></span>
            </label>
        </div>
    </div>
</div>
<div class="admin__field" id="wk-slot-has-quantity-row">
    <label class="admin__field-label" for="wk-slot-has-quantity">
        <span data-config-scope="[GLOBAL]">
            <?= $block->escapeHtml(__('Slot has Quantity'))?>
        </span>
    </label>
    <div class="admin__field-control">
        <div class="admin__actions-switch" data-role="switcher">
            <input type="checkbox" class="admin__actions-switch-checkbox"
                   data-form-part="product_form" id="wk-slot-has-quantity"
                   name="product[slot_has_quantity]"
                   value="<?= $block->escapeHtml($product['slot_has_quantity'])?>">
            <label class="admin__actions-switch-label" for="wk-slot-has-quantity">
                <span class="admin__actions-switch-text" data-bind="
                    attr: {
                        'data-text-on': toggleLabels.on,
                        'data-text-off': toggleLabels.off
                    }" data-text-on="Yes" data-text-off="No"></span>
            </label>
        </div>
    </div>
</div>
<script id="wk-booking-same-slot-container-template" type="text/x-magento-template">
    <div class="admin__field wk-booking-slot-row _show last">
        <label class="admin__field-label wk-booking-slot-container-label">
            <span>
                <?= $block->escapeHtml(__('Slot Information'))?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container wk-bk-hide" id="wk-bk-label-slot-box-container1">
        </div>
        <div class="admin__collapsible-content _show">
            <div class="wk-booking-slot-container" id="wk-booking-slot-container1">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn"
                        type="button" data-role="action" data-day-type="1">
                    <span><?= $block->escapeHtml(__('Add Slot'))?></span>
                </button>
            </div>
        </div>
    </div>
</script>
<script id="wk-booking-slot-container-template" type="text/x-magento-template">
    <div class="admin__field wk-booking-slot-row">
        <label class="admin__field-label wk-booking-slot-container-label">
            <span>
                <?= $block->escapeHtml(__('Monday'))?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container1">
        </div>
        <div class="admin__collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container" id="wk-booking-slot-container1">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn"
                        type="button" data-role="action" data-day-type="1">
                    <span><?= $block->escapeHtml(__('Add Slot'))?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="admin__field wk-booking-slot-row">
        <label class="admin__field-label wk-booking-slot-container-label">
            <span>
                <?= $block->escapeHtml(__('Tuesday'))?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container2">
        </div>
        <div class="admin__collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container" id="wk-booking-slot-container2">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn"
                        type="button" data-role="action" data-day-type="2">
                    <span><?= $block->escapeHtml(__('Add Slot'))?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="admin__field wk-booking-slot-row">
        <label class="admin__field-label wk-booking-slot-container-label">
            <span>
                <?= $block->escapeHtml(__('Wednesday'))?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container3">
        </div>
        <div class="admin__collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container" id="wk-booking-slot-container3">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn"
                        type="button" data-role="action" data-day-type="3">
                    <span><?= $block->escapeHtml(__('Add Slot'))?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="admin__field wk-booking-slot-row">
        <label class="admin__field-label wk-booking-slot-container-label">
            <span>
                <?= $block->escapeHtml(__('Thursday'))?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container4">
        </div>
        <div class="admin__collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container" id="wk-booking-slot-container4">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn"
                        type="button" data-role="action" data-day-type="4">
                    <span><?= $block->escapeHtml(__('Add Slot'))?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="admin__field wk-booking-slot-row">
        <label class="admin__field-label wk-booking-slot-container-label">
            <span>
                <?= $block->escapeHtml(__('Friday'))?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container5">
        </div>
        <div class="admin__collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container" id="wk-booking-slot-container5">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn"
                        type="button" data-role="action" data-day-type="5">
                    <span><?= $block->escapeHtml(__('Add Slot'))?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="admin__field wk-booking-slot-row">
        <label class="admin__field-label wk-booking-slot-container-label">
            <span>
                <?= $block->escapeHtml(__('Saturday'))?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container6">
        </div>
        <div class="admin__collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container" id="wk-booking-slot-container6">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn"
                        type="button" data-role="action" data-day-type="6">
                    <span><?= $block->escapeHtml(__('Add Slot'))?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="admin__field wk-booking-slot-row last">
        <label class="admin__field-label wk-booking-slot-container-label">
            <span>
                <?= $block->escapeHtml(__('Sunday'))?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container7">
        </div>
        <div class="admin__collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container" id="wk-booking-slot-container7">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn"
                        type="button" data-role="action" data-day-type="7">
                    <span><?= $block->escapeHtml(__('Add Slot'))?></span>
                </button>
            </div>
        </div>
    </div>
</script>
<script id="wk-booking-slot-template" type="text/x-magento-template">
    <div class="admin__field _required wk-booking-slot-block" id="wk-booking-slot-block<%- data.id %><%- data.index %>">
        <label class="admin__field-label">
            <span class="wk-booking-slot-label-span"><?= $block->escapeHtml(__('Slot Span'))?></span>
        </label>
        <div class="admin__field-control admin__control-grouped-date admin__control-grouped">
            <div class="admin__field admin__field-date">
                <div class="admin__field-control">
                    <input class="admin__control-text required-entry wk-booking-slot-picker"
                           data-form-part="product_form" type="text"
                           name="product[slot_data][<%- data.id %>][<%- data.index %>][from]"
                           value="<%- data.from %>" readonly>
                </div>
            </div>
            <div class="admin__field admin__field-date wk-booking-row-field-date">
                <label class="admin__field-label">
                    <span><?= $block->escapeHtml(__('To'))?></span>
                </label>
                <div class="admin__field-control">
                    <input class="admin__control-text required-entry wk-booking-slot-picker"
                           data-form-part="product_form" type="text"
                           name="product[slot_data][<%- data.id %>][<%- data.index %>][to]"
                           value="<%- data.to %>" readonly>
                </div>
            </div>
            <div class="admin__field admin__field-date wk-booking-row-field-date 
                    wk-booking-row-field-qty <%- data.qtyclass %>">
                <label class="admin__field-label">
                    <span><?= $block->escapeHtml(__('Qty'))?></span>
                </label>
                <div class="admin__field-control">
                    <input class="admin__control-text <%- data.qtyfieldclass %> wk-booking-qty-field"
                           data-form-part="product_form" type="text"
                           name="product[slot_data][<%- data.id %>][<%- data.index %>][qty]"
                           value="<%- data.qty %>">
                </div>
            </div>
            <div class="wk-booking-row-btn-container">
                <button type="button" class="action-basic wk-booking-row-remove-btn" data-index="button_related">
                    <span><?= $block->escapeHtml(__('Remove'))?></span>
                </button>
            </div>
        </div>
    </div>
</script>
<script id="wk-booking-label-slot-template" type="text/x-magento-template">
    <div class="wk-bk-label-slot-box" id="wk-bk-label-slot-box<%- data.id %><%- data.index %>">
        <%- data.from %> - <%- data.to %><span class="wk-span-label-qty">, QTY - <%- data.qty %></span>
        <span class="wk-bk-label-slot-box-close"></span>
    </div>
</script>
<?php
$jsData = [
    'slotDataType' => $product['slot_for_all_days'],
    'slotData' => $bookingSlotData,
    'availableEveryWeek' => $product['available_every_week'],
    'slotHasQuantity' => $product['slot_has_quantity']
];
$encodedJsData = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($jsData);
?>
<script type="text/x-magento-init">
    {
        "body": {
            "appointmentbooking": <?= /* @noEscape */ $encodedJsData; ?>
        }
    }
</script>
<script>
    jQuery('body').trigger('contentUpdated');
</script>
