<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAdvancedBookingSystem
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$viewModel = $block->getBookingViewModel();
if ($viewModel === null) {
    $viewModel = $block->getLayout()->createBlock(
        \Webkul\MpAdvancedBookingSystem\Block\GetViewModel::class
    )->getBookingViewModel();
}

$helper = $viewModel->getHelper();
$bookingAvailableFrom = '';
$bookingAvailableTo = '';
$productSetId = '';
$bookingSlotData = $helper->getJsonEcodedString([]);
$params = $block->getRequest()->getParams();
if (!empty($params['id'])) {
    $product = $block->getProduct($params['id']);
    if ($product['booking_available_from'] != 'Invalid date') {
        $bookingAvailableFrom = $product['booking_available_from'];
    }
    if ($product['booking_available_to'] != 'Invalid date') {
        $bookingAvailableTo = $product['booking_available_to'];
    }
    $bookingInfo = $helper->getBookingInfo($product->getId());
    if (!empty($bookingInfo['info'])) {
        $bookingSlotData = $bookingInfo['info'];
    }
    $productSetId = $product->getAttributeSetId();
    $appointmentType = $helper->getProductAttributeSetIdByLabel('Appointment Booking');
    if ($productSetId != $appointmentType) {
        $bookingSlotData = [];
        $bookingSlotData = $helper->getJsonEcodedString($bookingSlotData);
    }
} else {
    $product['slot_duration'] = "";
    $product['break_time_bw_slot'] = "";
    $product['prevent_scheduling_before'] = "";
    $product['available_every_week'] = 1;
    $product['slot_for_all_days'] = 1;
    $product['slot_has_quantity'] = 1;
    $product['show_map_loction'] = 1;
}
?>
<div class="field">
    <label class="label"><?= /* @noEscape */ __('Booking Information') ?>:</label>
    <div class="wk-border"></div>
</div>
<div class="field required">
    <label class="label" for="wk-slot-duration">
        <span>
            <?= /* @noEscape */ __('Slot Duration')?> (<?= /* @noEscape */ __('Mins')?>)
        </span>
    </label>
    <div class="control">
        <input class="input-text required-entry validate-digits" type="text" name="product[slot_duration]"
               value="<?= /* @noEscape */ $product['slot_duration']?>" id="wk-slot-duration">
    </div>
</div>
<div class="field required">
    <label class="label" for="wk-break-time-bw-slot">
        <span>
            <?= /* @noEscape */ __('Break Time b/w Slots')?> (<?= /* @noEscape */ __('Mins')?>)
        </span>
    </label>
    <div class="control">
        <input class="input-text required-entry validate-digits" type="text" name="product[break_time_bw_slot]"
               value="<?= /* @noEscape */ $product['break_time_bw_slot']?>" id="wk-break-time-bw-slot">
    </div>
</div>
<div class="field required" data-index="show_contact_btn">
    <label class="label" for="wk-prevent-scheduling-before">
        <span>
            <?= /* @noEscape */ __('Prevent Scheduling(Mins)')?>
        </span>
    </label>
    <div class="control">
        <input class="input-text required-entry validate-digits" type="text"
               name="product[prevent_scheduling_before]" id="wk-prevent-scheduling-before"
               value="<?= /* @noEscape */ $product['prevent_scheduling_before']?>">
    </div>
</div>
<div class="field toggle-field">
    <label class="label" for="wk-available-every-week">
        <span>
            <?= /* @noEscape */ __('Available Every Week')?>
        </span>
    </label>
    <div class="admin__field-control">
        <div class="admin__actions-switch" data-role="switcher">
            <input type="checkbox" class="admin__actions-switch-checkbox"
                   id="wk-available-every-week" name="product[available_every_week]" value="1">
            <label class="admin__actions-switch-label" for="wk-available-every-week">
                <span class="admin__actions-switch-text" data-text-on="Yes" data-text-off="No"></span>
            </label>
        </div>
    </div>
</div>
<div class="field required wk-booking-date-block"
        <?php if ($product['available_every_week']) { ?>style="display: none;"<?php }?>>
    <label class="label" for="wk-booking-available-from">
        <span>
            <?= /* @noEscape */ __('Available')?>
        </span>
    </label>
    <div class="control grouped-date grouped">
        <div class="date">
            <label class="label">
                <span><?= /* @noEscape */ __('From')?></span>
            </label>
            <div class="control">
                <input class="input-text required-entry"
                       id="wk-booking-available-from" type="text"
                       name="product[booking_available_from]"
                       value="<?= /* @noEscape */ $bookingAvailableFrom?>" readonly/>
            </div>
        </div>
        <div class="date">
            <label class="label">
                <span><?= /* @noEscape */ __('To')?></span>
            </label>
            <div class="control">
                <input class="input-text required-entry"
                       id="wk-booking-available-to" type="text"
                       name="product[booking_available_to]"
                       value="<?= /* @noEscape */ $bookingAvailableTo?>" readonly/>
            </div>
        </div>
    </div>
</div>
<div class="field toggle-field">
    <label class="label" for="wk-slot-all-days">
        <span>
            <?= /* @noEscape */ __('Same Slot for All Days')?>
        </span>
    </label>
    <div class="admin__field-control">
        <div class="admin__actions-switch" data-role="switcher">
            <input type="checkbox" class="admin__actions-switch-checkbox" id="wk-slot-all-days"
                   name="product[slot_for_all_days]" value="1">
            <label class="admin__actions-switch-label" for="wk-slot-all-days">
                <span class="admin__actions-switch-text" data-text-on="Yes" data-text-off="No"></span>
            </label>
        </div>
    </div>
</div>
<div class="field toggle-field" id="wk-slot-has-quantity-row">
    <label class="label" for="wk-slot-has-quantity">
        <span>
            <?= /* @noEscape */ __('Slot has Quantity')?>
        </span>
    </label>
    <div class="admin__field-control">
        <div class="admin__actions-switch" data-role="switcher">
            <input type="checkbox" class="admin__actions-switch-checkbox" id="wk-slot-has-quantity"
                   name="product[slot_has_quantity]" value="1">
            <label class="admin__actions-switch-label" for="wk-slot-has-quantity">
                <span class="admin__actions-switch-text" data-text-on="Yes" data-text-off="No"></span>
            </label>
        </div>
    </div>
</div>
<script id="wk-booking-same-slot-container-template" type="text/x-magento-template">
    <div class="field wk-booking-slot-row _show last">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Slot Information')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container wk-bk-hide" id="wk-bk-label-slot-box-container1">
        </div>
        <div class="collapsible-content _show">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container1">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="1">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
</script>
<script id="wk-booking-slot-container-template" type="text/x-magento-template">
    <div class="field wk-booking-slot-row">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Monday')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container1">
        </div>
        <div class="collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container1">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="1">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="field wk-booking-slot-row">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Tuesday')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container2">
        </div>
        <div class="collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container2">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="2">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="field wk-booking-slot-row">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Wednesday')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container3">
        </div>
        <div class="collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container3">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="3">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="field wk-booking-slot-row">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Thursday')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container4">
        </div>
        <div class="collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container4">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="4">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="field wk-booking-slot-row">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Friday')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container5">
        </div>
        <div class="collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container5">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="5">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="field wk-booking-slot-row">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Saturday')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container6">
        </div>
        <div class="collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container6">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="6">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="field wk-booking-slot-row last">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Sunday')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container7">
        </div>
        <div class="collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container7">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="7">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
</script>
<script id="wk-booking-slot-template" type="text/x-magento-template">
    <div class="field required wk-booking-slot-block" id="wk-booking-slot-block<%- data.id %><%- data.index %>">
        <label class="label">
            <span class="wk-booking-slot-label-span"><?= /* @noEscape */ __('Slot Span')?></span>
        </label>
        <div class="control grouped-date grouped">
            <div class="date">
                <label class="label">
                    <span><?= /* @noEscape */ __('From')?></span>
                </label>
                <div class="control">
                    <input class="input-text required-entry wk-booking-slot-picker" type="text"
                           name="product[slot_data][<%- data.id %>][<%- data.index %>][from]"
                           value="<%- data.from %>" readonly>
                </div>
            </div>
            <div class="date wk-booking-row-field-date">
                <label class="label">
                    <span><?= /* @noEscape */ __('To')?></span>
                </label>
                <div class="control">
                    <input class="input-text required-entry wk-booking-slot-picker" type="text"
                           name="product[slot_data][<%- data.id %>][<%- data.index %>][to]"
                           value="<%- data.to %>" readonly>
                </div>
            </div>
            <div class="date wk-booking-row-field-date wk-booking-row-field-qty <%- data.qtyclass %>">
                <label class="label">
                    <span><?= /* @noEscape */ __('Qty')?></span>
                </label>
                <div class="control">
                    <input class="input-text <%- data.qtyfieldclass %> wk-booking-qty-field" type="text"
                           name="product[slot_data][<%- data.id %>][<%- data.index %>][qty]" value="<%- data.qty %>">
                </div>
            </div>
            <div class="wk-booking-row-btn-container">
                <button type="button" class="action-basic wk-booking-row-remove-btn" data-index="button_related">
                    <span><?= /* @noEscape */ __('Remove')?></span>
                </button>
            </div>
        </div>
    </div>
</script>
<script id="wk-booking-label-slot-template" type="text/x-magento-template">
    <div class="wk-bk-label-slot-box" id="wk-bk-label-slot-box<%- data.id %><%- data.index %>">
        <%- data.from %> - <%- data.to %><span class="wk-span-label-qty">, QTY - <%- data.qty %></span>
        <span class="wk-bk-label-slot-box-close"></span>
    </div>
</script>
<?php
$jsData = [
    'slotDataType' => $product['slot_for_all_days'],
    'slotData' => $bookingSlotData,
    'availableEveryWeek' => $product['available_every_week'],
    'slotHasQuantity' => $product['slot_has_quantity'],
    'showMapLocation' => $product['show_map_loction']
];
$encodedJsData = $viewModel->getJsonHelper()->jsonEncode($jsData);
?>
<script type="text/x-magento-init">
    {
        "body": {
            "mpappointmentbooking": <?= /* @noEscape */ $encodedJsData; ?>
        }
    }
</script>