<?php
/**
 * Webkul Software
 * @category  Webkul
 * @package   Webkul_Affiliate
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div class="pp-buttons-container">
    <button id="<?= /* @noEscape */  $block->getId() ?>" onclick="return false;">
        <span><span><span><?= /* @noEscape */  $block->escapeHtml($block->getButtonLabel()); ?></span></span></span>
    </button>
</div>
<script>
require([
        "jquery",
        "mage/mage",
    ], function($){
        var alerttext = '';
         $("#<?= /* @noEscape */  $block->getId() ?>").on( "click", function() {
            var alerttext = '';
            new Ajax.Request('<?= /* @noEscape */  $block->getAjaxCheckUrl() ?>', {
                method: 'get',
                onSuccess: function(transport){
                    var response = $.parseJSON(transport.responseText);
                    if (response.msg){
                        $('<div />').html(response.msg)
                            .modal({
                                title: $.mage.__('Attention'),
                                autoOpen: true,
                                buttons: [{
                                 text: 'OK',
                                    attr: {
                                        'data-action': 'cancel'
                                    },
                                    'class': 'action-primary',
                                    click: function() {
                                            this.closeModal();
                                        }
                                }]
                             });
                    }else{
                        if(response.success){
                            alerttext = '<b>Modules added: </b>'+ response.success+'<br>';
                        }
                        $('<div />').html(alerttext)
                            .modal({
                                title: $.mage.__('Attention'),
                                autoOpen: true,
                                buttons: [{
                                 text: 'OK',
                                    attr: {
                                        'data-action': 'cancel'
                                    },
                                    'class': 'action-primary',
                                    click: function() {
                                            this.closeModal();
                                        }
                                }]
                        });
                    }
                }
            });
        });
       });                 
</script>