<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpRmaSystem
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php $url = $block->getUrl("mprmasystem/customer/newrma"); ?>
<div class="wk-mprma-container">
    <div class="wk-mp-rma-newrma">
        <a href="<?= $escaper->escapeUrl($url); ?>"><?= $escaper->escapeHtml(__("Request New RMA")); ?></a>
    </div>
</div>
</script>