<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAdvancedBookingSystem
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/** @var $block \Webkul\MpAdvancedBookingSystem\Block\Product\Bookinglist */

$viewModel = $block->getBookingViewModel();
if ($viewModel === null) {
    $viewModel = $block->getLayout()->createBlock(
        \Webkul\MpAdvancedBookingSystem\Block\GetViewModel::class
    )->getBookingViewModel();
}

$helper = $viewModel->getMpHelper();
$bookingHelper = $viewModel->getHelper();
$paramData = $block->getRequest()->getParams();
$filter = '';
$filterStatus = '';
$filterDateFrom = '';
$filterDateTo = '';
if (isset($paramData['s'])) {
    $filter = $paramData['s'] != '' ? $paramData['s'] : '';
}
if (isset($paramData['status'])) {
    $filterStatus = $paramData['status'] != '' ? $paramData['status'] : '';
}
if (isset($paramData['from_date'])) {
    $filterDateFrom = $paramData['from_date'] != '' ? $paramData['from_date'] : '';
}
if (isset($paramData['to_date'])) {
    $filterDateTo = $paramData['to_date'] != '' ? $paramData['to_date'] : '';
}
$_products_coll = $block->getAllProducts();
if ($helper->getIsProductApproval() || $helper->getIsProductEditApproval()) {
    $enabledStatusText = __('Approved');
    $disabledStatusText = __('Pending');
} else {
    $enabledStatusText = __('Enabled');
    $disabledStatusText = __('Disabled');
}
?>
<div class="wk-mp-design">
    <fieldset class="fieldset info wk-mp-fieldset">
        <legend class="legend">
            <span><?= /* @noEscape */ __('Booking Product List') ?></span>
        </legend>
        <div class="grid">
            <div class="hor-scroll">
                <form 
                    action="<?= /* @noEscape */ $block->getUrl(
                        'mpadvancebooking/product/bookinglist',
                        ['_secure' => $block->getRequest()->isSecure()]
                    )?>"
                    method="get" id="form-productlist-filter"
                    name="formProductlistFilter" data-mage-init='{"validation":{}}'>
                    <table cellspacing="0" class="border wk-mp-list-table">
                        <thead>
                            <tr id="wk-mp-tr-heading">
                                <th><span><?= /* @noEscape */ __('Product Name') ?></span></th>
                                <th><span><?= /* @noEscape */ __('Date') ?></span></th>
                                <th><span><?= /* @noEscape */ __('Product Status') ?></span></th>
                                <th><span>&nbsp;</span></th>
                            </tr>
                        </thead>
                        <tbody class="wk-mp-body" id="colender-check">
                            <tr>
                                <td>
                                    <input type="text" class="input-text" name="s"
                                        placeholder='<?= /* @noEscape */ __('Search by product name') ?>'
                                        value="<?= /* @noEscape */ $filter?>"/>
                                </td>
                                <td>
                                    <span class="wk-mp-td-span">
                                        <?= /* @noEscape */ __('From: ') ?>
                                        <input name="from_date" id="special-from-date" class="input-text"
                                            value="<?= /* @noEscape */ $filterDateFrom?>" />
                                    </span>                                
                                    <span class="wk-mp-td-span">
                                        <?= /* @noEscape */ __('To: ') ?>
                                        <input name="to_date" id="special-to-date" class="input-text"
                                            value="<?= /* @noEscape */ $filterDateTo?>" />
                                    </span>
                                </td>
                                <td>
                                    <select name="status" class="input-text">
                                        <option value=""><?= /* @noEscape */ __('All') ?></option>
                                        <option value="1" <?php if ($filterStatus==1) { echo 'selected="selected"'; }?>>
                                            <?= /* @noEscape */ $enabledStatusText ?>
                                        </option>
                                        <option value="2" <?php if ($filterStatus==2) { echo 'selected="selected"'; }?>>
                                            <?= /* @noEscape */ $disabledStatusText ?>
                                        </option>
                                    </select>
                                </td>
                                <td>
                                    <button class="button" title="Save" type="submit">
                                        <span><span><span><?= /* @noEscape */ __('Submit') ?></span></span></span>
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
                <div data-bind="scope: 'product-list-component'">    
                <?php if ($_products_coll && count($_products_coll)): ?>
                    <form action="<?= /* @noEscape */
                                    $block->getUrl(
                                        'mpadvancebooking/product/delete',
                                        ['_secure' => $block->getRequest()->isSecure()]
                                    ) ?>"
                        method="post" id="form-productlist-massdelete" name="formProductlistMassdelete"
                        data-mage-init='{"validation":{}}'>
                        <?= /* @noEscape */ $block->getBlockHtml('formkey')?>
                        <button class="button" title="<?= /* @noEscape */ __('Delete Products') ?>"
                                type="submit" style="float: left;"  id="mass-delete-butn">
                            <span><span><?= /* @noEscape */ __('Delete Products') ?></span></span>
                        </button>
                            <!-- ko template: getTemplate() --><!-- /ko -->
                        <table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
                            <thead>
                                <tr class="wk-content">
                                    <th class="wk-check-first-td">
                                        <span>
                                            <input type="checkbox" name="mpselecctall" value="all" id="mpselecctall"/>
                                        </span>
                                    </th>
                                    <th class="wk-first-td">
                                        <span class="label name">
                                            <?= /* @noEscape */ __('Product')?>
                                        </span>
                                    </th>
                                    <th>
                                        <span class="label pro-status">
                                            <?= /* @noEscape */ __('Type')?>
                                        </span>
                                    </th>
                                    <?php if ($bookingHelper->isMpMsiModuleInstalled()) { ?>
                                        <th class="wk-status-td">
                                            <span class="label pro-status">
                                                <?= $block->escapeHtml(__('Quantity Per Source'))?>
                                            </span>
                                        </th>
                                        <th class="wk-list-th-display">
                                            <span class="label qty">
                                                <?= $block->escapeHtml(__('Salable Quantity'))?>
                                            </span>
                                        </th>
                                    <?php } ?>
                                    <th>
                                        <span class="label pro-status">
                                            <?= /* @noEscape */ __('Status')?>
                                        </span>
                                    </th>
                                    <th class="wk-list-th-display">
                                        <span class="label qty">
                                            <?= /* @noEscape */ __('Qty. Confirmed')?>
                                        </span>
                                    </th>
                                    <th class="wk-list-th-display">
                                        <span class="label qty">
                                            <?= /* @noEscape */ __('Qty. Pending')?>
                                        </span>
                                    </th>    
                                    <th class="wk-list-th-display">
                                        <span class="label qty">
                                            <?= /* @noEscape */ __('Qty. Sold')?>
                                        </span>
                                    </th>
                                    <th class="wk-list-th-display1">
                                        <span class="label">
                                            <?= /* @noEscape */ __('Earned Amount')?>
                                        </span>
                                    </th>
                                    <th>
                                        <span class="label">
                                            <?= /* @noEscape */ __('Action')?>
                                        </span>
                                    </th>                        
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 0;
                                foreach ($block->getAllProducts() as $products) {
                                    $product = $block->getProductData($products->getMageproductId());
                                    $i++;
                                    $image_url = $block->imageHelperObj()->init($product, 'product_page_image_small')
                                                ->setImageFile($product->getImage())
                                                ->getUrl();
                                    $salesdetail=$block->getSalesdetail($products->getMageproductId());
                                    $isApprovedBefore = $products['is_approved'];
                                    ?>
                                    <tr class="wk-row-view <?= /* @noEscape */
                                                $class = ($i == count($block->getAllProducts()))? 'wk-last_tr':''?>">
                                        <td class="wk-check-first-td">
                                            <span>
                                                <input type="checkbox" name="product_mass_delete[]" class="mpcheckbox"
                                                    value="<?= /* @noEscape */ $products->getMageproductId(); ?>"/>
                                            </span>
                                        </td>
                                        <td class="wk-first_td">
                                            <input type="hidden" class="hidden-id"
                                                value="<?= /* @noEscape */ $products->getMageproductId(); ?>" />
                                            <div class="label name" title="<?= /* @noEscape */ $product->getName(); ?>">
                                                <div class="wk-pro-divide1">
                                                    <img src="<?= /* @noEscape */ $image_url?>" class="image" />
                                                </div>
                                                <div class="wk-pro-divide2">
                                                    <div style="width:100%;">
                                                        <?php if ($product->getStatus()==1
                                                            && $product->getVisibility()!=1
                                                        ) { ?>
                                                            <a href="<?= /* @noEscape */ $product->getProductUrl()?>"
                                                               target="blank">
                                                        <?php }?>
                                                            <?= /* @noEscape */ $product->getName();?>
                                                        <?php if ($product->getStatus()==1
                                                            && $product->getVisibility()!=1
                                                        ) { ?>
                                                            </a>
                                                        <?php }?>
                                                    </div>
                                                    <div style="width:100%;float:left;">
                                                        <?php
                                                        if ($product->getPrice()*1) {
                                                            /* @noEscape */ echo $block->getFormatedPrice(
                                                                $product->getPrice(),
                                                                $helper->getCurrencySymbol()
                                                            );
                                                        } else {
                                                            /* @noEscape */ echo $helper->getCurrencySymbol().'0.00';
                                                        }
                                                        ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td>        
                                            <span class="label pro-status">
                                                <?= /* @noEscape */ $block->getBookingType(
                                                    $product->getAttributeSetId()
                                                )?>
                                            </span>
                                        </td>
                                        <?php if ($bookingHelper->isMpMsiModuleInstalled()) {
                                            $msiHelper = $bookingHelper->getMpMSIDataHelper();
                                            ?>
                                            <td>
                                                <span class="label qty">
                                                    <?php
                                                        $stocks = $msiHelper->getSourceQtyBySku($product->getSku());

                                                    foreach ($stocks as $stock) {
                                                        /*@noEscape */ echo "<div>{$stock['name']} :
                                                        {$stock['quantity']}</div>";
                                                    }

                                                    ?>
                                                </span>
                                            </td>
                                            <td>
                                                <span class="label qty">
                                                    <?php
                                                        $stocks = $msiHelper->getSalableQtyBySku($product->getSku());
                                                    foreach ($stocks as $stock) {
                                                        /*@noEscape*/ echo "<div>{$stock['stock_name']} :
                                                        {$stock['qty']}</div>";
                                                    }
                                                    ?>
                                                </span>
                                            </td>
                                        <?php } ?>
                                        <?php
                                        if (($product->getStatus()==2 && !$isApprovedBefore)) {    ?>
                                            <td>        
                                                <span class="label pro-status">
                                                    <?= /* @noEscape */ $disabledStatusText ?>
                                                </span>
                                            </td>
                                            <td class="wk-list-th-display">
                                                <span class="label qty">
                                                    <?= /* @noEscape */ __('Pending')?>
                                                </span>
                                            </td>
                                            <td class="wk-list-th-display">
                                                <span class="label qty">
                                                    <?= /* @noEscape */ __('Pending')?>
                                                </span>    
                                            </td>
                                            <td class="wk-list-th-display">
                                                <span class="label qty">
                                                    <?= /* @noEscape */ __('Pending')?>
                                                </span>    
                                            </td>
                                            <td class="wk-list-th-display1">
                                                <span class="label qty">
                                                    <?= /* @noEscape */ __('Pending')?>
                                                </span>    
                                            </td>                                    
                                        <?php } else { ?>
                                            <?php if ($product->getStatus() == 2) { ?>
                                                <td>        
                                                    <span class="label pro-status">
                                                        <?= /* @noEscape */ $disabledStatusText ?>
                                                    </span>
                                                </td>
                                            <?php } else { ?>
                                                <td>        
                                                    <span class="label pro-status">
                                                        <?= /* @noEscape */ $enabledStatusText ?>
                                                    </span>
                                                </td>
                                            <?php } ?>
                                            <td class="wk-list-th-display">
                                                <span class="label qty">
                                                    <?= /* @noEscape */ $salesdetail['quantitysoldconfirmed']; ?>
                                                </span>
                                            </td>
                                            <td class="wk-list-th-display">
                                                <span class="label qty">
                                                    <?= /* @noEscape */ $salesdetail['quantitysoldpending']; ?>
                                                </span>    
                                            </td>
                                            <td class="wk-list-th-display1">
                                                <span class="label qty">
                                                    <a href="<?= /* @noEscape */
                                                                $block->getUrl(
                                                                    'marketplace/order/salesdetail/',
                                                                    ['id'=>$product->getId(),
                                                                    '_secure' => $block->getRequest()->isSecure()]
                                                                ); ?>">
                                                        <?= /* @noEscape */ $salesdetail['quantitysold']; ?>
                                                    </a>
                                                </span>    
                                            </td>
                                            <td class="wk-list-th-display">
                                                <span class="label price">
                                                    <?= /* @noEscape */ $block->getFormatedPrice(
                                                        $salesdetail['amountearned'],
                                                        $helper->getCurrencySymbol()
                                                    ); ?>
                                                </span>    
                                            </td>
                                            <?php
                                        }?>
                                        <td>
                                            <span class="label wk-action">
                                                <img
                                                    src="<?= /* @noEscape */
                                                            $block->getViewFileUrl(
                                                                'Webkul_Marketplace::images/icon-edit.png'
                                                            ); ?>"
                                                    data-url="<?= /* @noEscape */
                                                                $block->getUrl(
                                                                    'marketplace/product/edit',
                                                                    ['id'=>$product->getId(),
                                                                    '_secure' => $block->getRequest()->isSecure()]
                                                                ) ?>"
                                                    alt="<?= /* @noEscape */ __('Edit')?>"
                                                    title="<?= /* @noEscape */ __('Edit')?>"
                                                    class="mp-edit"/>
                                            </span>    
                                        </td>                        
                                    </tr>
                                    <?php
                                }?>
                            </tbody>
                        </table>
                    </form>
                    </div>                        
                <?php else: ?>
                    <div class="wk-emptymsg">
                        <?= /* @noEscape */ __('No Booking Product Available') ?>
                    </div>
                <?php endif ?>                    
            </div>
        </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom"><?= /* @noEscape */ $block->getPagerHtml(); ?></div>
        <?php endif ?>    
    </fieldset>    
    <div class="buttons-set">
        <p class="back-link">
            <a href="javascript:;" onclick="javascript: window.history.back();"
               class="left">&laquo; <?= /* @noEscape */ __('Back') ?></a>
        </p>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Webkul_Marketplace/js/product/product-date-range": {}
        }
    }
</script>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "product-list-component": {
                            "component": "sellerProductList",
                            "template" : "Webkul_Marketplace/product-list"
                        }
                    }
                }
            }
        }
</script>
