<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAdvancedBookingSystem
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/** @var $block \Webkul\Marketplace\Block\Product\Create */

$viewModel = $block->getBookingViewModel();
if ($viewModel === null) {
    $viewModel = $block->getLayout()->createBlock(
        \Webkul\MpAdvancedBookingSystem\Block\GetViewModel::class
    )->getBookingViewModel();
}

$helper = $viewModel->getHelper();
$allowedBookinTypes = $helper->getAllowedBookingProductTypes(); ?>
<form 
    action="<?= /* @noEscape */
        $block->getUrl('mpadvancebooking/product/create', ['_secure' => $block->getRequest()->isSecure()]) ?>"
    enctype="multipart/form-data" method="post" id="form-customer-product-new" data-mage-init='{"validation":{}}'>
    <div class="wk-mp-design">
        <fieldset class="fieldset info wk-mp-fieldset">
            <legend class="legend">
                <span><?= /* @noEscape */ __('Add New Booking Product') ?></span>
                <button class="button wk-mp-btn" title="Continue" type="submit">
                    <span><span><?= /* @noEscape */ __('Continue') ?></span></span>
                </button>
            </legend>
            <?= /* @noEscape */ $block->getBlockHtml('formkey')?>
            <?= /* @noEscape */ $block->getBlockHtml('seller.formkey')?>
            <?php if (count($allowedBookinTypes) > 1) { ?>
                <div class="field required">
                    <label class="label"><?= /* @noEscape */ __('Booking Product Type') ?>:</label>
                    <div class="control">
                        <select name="type" class="required-entry">
                        <?php foreach ($allowedBookinTypes as $type) {?>
                            <option value="<?= /* @noEscape */ $type['value'] ?>">
                                <?= /* @noEscape */ $type['label']?>
                            </option>
                        <?php } ?>
                        </select>
                    </div>
                </div>
            <?php } else { ?>
                <input type="hidden" name="type" value="<?= /* @noEscape */ $allowedBookinTypes[0]['value'] ?>" />
                <?php
            } ?>
            <?= /* @noEscape */ $block->getChildHtml(); ?>
        </fieldset>
    </div>        
</form>
<div class="buttons-set">
    <p class="required">* <?= /* @noEscape */ __('Required Fields') ?></p>        
    <p class="back-link">
        <a href="javascript:;" onclick="javascript: window.history.back();"
           class="left">&laquo; <?= /* @noEscape */ __('Back') ?></a>
    </p>
</div>