<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAdvancedBookingSystem
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?= /* @noEscape */ $block->getChildHtml("appointment-contact-info") ?>
<?= /* @noEscape */ $block->getChildHtml("appointment-booking-info") ?>
