<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/** @var $block \Webkul\Marketplace\Block\Product\Create */

$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$product_hint_status = $helper->getProductHintStatus();
$currency_code = $helper->getCurrentCurrencyCode();
$currency_symbol = $helper->getCurrencySymbol();
$set = $block->getRequest()->getParam('set');
$type = $block->getRequest()->getParam('type');
$skuType = $helper->getSkuType();
$skuPrefix = $helper->getSkuPrefix();
$data = $block->getPersistentData();
$weightUnit = $helper->getWeightUnit();
$allowProductType =$block->getAllowedProductType();

if (!empty($data['set'])) {
    $set = $data['set'];
}
?>
<form action="<?= $escaper->escapeUrl($block
->getUrl('marketplace/product/save', ['_secure' => $block->getRequest()->isSecure()])) ?>"
 enctype="multipart/form-data" method="post" id="edit-product" data-form="edit-product"
  data-mage-init='{"validation":{}}'>
    <div class="wk-mp-design" id="wk-bodymain">
        <fieldset class="fieldset info wk-mp-fieldset">
            <div data-mage-init='{"formButtonAction": {}}' class="wk-mp-page-title legend">
                <span><?= $escaper->escapeHtml(__('Add Product')) ?></span>
                <div class="tooltip d-lg-inline-block d-none">
                            
                            <img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/info.png'); ?>"  width="33px" height="33px"  />
                            <span class="tooltiptext">
                                <ol><strong> Product Category:</strong><br>
                                    We can assign the category to the Product under which it will be listed and displayed on the website and also can assign attributes to it.
                                              <li> <strong>SKU :</strong> The Stock keeping Unit of the product ( for tracking the inventory of your store )</li>
                                               <li><strong>Price :The price value of the product :</strong></li>
                                               <ul><li> <strong> Special Price:</strong> A special price is a discounted product price that can be scheduled for a pre-set period of time. It is displayed on both catalog listings and product pages. The regular price is shown as well, for the customer to see the difference.</li>
                                               <li><strong>Special Price From:</strong> It depends on the seller when he wants to start this offer.</li>
                                               <li><strong>Special Price To:</strong> It’s up to the seller when he wants to end the offer.</li></ul>
                                              
                                             
                                                <li><strong>Stock Availability :</strong>The setting up of the stock allows the shoppers to see the availability of the product   they are interested in 
                                                 quickly without having to ask the store. On the storefront, “In Stock” and “Out of Stock” will describe this availability.
                                                </li>
                                                   <li><strong>.Visibility : </strong>These are of four types.</li>
                                                   <ul><li><strong>Not Visible Individually :</strong> The product is not included in your storefront listings, although it might be available as 
                                                     a variation of another product. </li>
                                                     <li><strong>Catalog :</strong>For merchants, the catalog represents their product inventory. Architecture, the catalog consists of categories, products, and product 
                                                         attributes.</li>
                                                         <li><strong>Search :</strong>The search terms define the behavior of Magento 2 search when the customer enters a particular search query. Search query – defines a word 
                                                             or a phrase a customer should enter in the search field to get redirected to a particular page. Store – defines the store (s) view the search term 
                                                              is applied to</li>
                                                               <li><strong>Catalog Search:</strong>Catalog search is the basic means of catalog navigation . However, it is very powerful since it allows customers to find 
                                                                 products faster and easier, just by typing a few characters. Search terms and synonyms give you a little control over the customer search 
                                                                  queries since they allow you to optimize the search for them.
                                                               </li>
</ul>
                                                    
                                                       
                                                <li> <strong> .Weight (lbs) :</strong>Add the weight of the product. for shipping purposes and uses this information to calculate shipping during checkout. 
                                               </li> 
                                               <li><strong>Meta title:</strong> Meta title will be shown as the title of the product site in search results. You want this to be short but impactful. Make it 
                                                about your products and slip in trophy phrases. A good Magento SEO page title will ensure a better rank in search engine results.</li>
                                               <li><strong>Meta keywords:</strong> These keywords will help the search engines with indexing your product page</li>
                                               <li><strong>Meta Description:</strong>  Meta descriptions are snippets of text conveying a short summary of the page content. After reading your meta title, a 
                                                user scans your meta description. The best meta description length is considered to be about 160 characters. Not long ago, Google decided to increase snippets 
                                                 length to 230 characters, though its effect is not guaranteed.
                                                  </li>
                                                  <li><strong>Is Featured Products:</strong>
                                                  With the use of Featured Product, the store owner can display a specified number of products in a grid layout with thumbnails of the products. The store 
                                                   admin can set any product as a featured product very easily. When the store admin selects “Yes” in the “Featured” attribute, that product displays in a 
                                                    featured product page.
                                                </li>
                                                <li><strong> .Create Configurations:</strong>
                                                To create configurable products  means to create several different variations of the same simple product. Since configurable products consist of simple ones 
                                                 that have separate SKUs it's more convenient to track down every single product variation.
                                            </li>
                                 </ol>
                            </span>
                        </div> 
                <button class="button wk-mp-btn" title="<?= $escaper->escapeHtml(__('Save')) ?>"
                 type="submit" id="save-btn">
                    <span><span><?= $escaper->escapeHtml(__('Save')) ?></span></span>
                </button>
                <button class="button wk-mp-btn" 
                title="<?= $escaper->escapeHtml(__('Save & Duplicate')) ?>" 
                type="button" id="wk-mp-save-duplicate-btn">
                    <span><span><?= $escaper->escapeHtml(__('Save & Duplicate')) ?></span></span>
                </button>
            </div>
            <?= $block->getBlockHtml('formkey')?>
            <?= $block->getBlockHtml('seller.formkey')?>
            <input id="product_type_id" name="type" type="hidden"
             value="<?= $escaper->escapeHtml($type)?>" value="<?= $escaper->escapeHtml($data['type'])?>">
            <?php if (count($helper->getAllowedSets()) > 1): ?>
                <div class="field required">
                    <label class="label"><?= $escaper->escapeHtml(__('Attribute Set')) ?>:</label>
                    <div class="control">
                        <select name="set" id="attribute-set-id" class="required-entry">
                        <?php foreach ($helper->getAllowedSets() as $setval): ?>
                            <option value="<?= $escaper->escapeHtml($setval['value']) ?>"
                             <?php if ($set==$setval['value']) { ?> selected="selected" <?php } ?>>
                                <?= $escaper->escapeHtml($setval['label'])?>
                            </option>
                        <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            <?php else: ?>
                <?php $allowedSets = $helper->getAllowedSets(); ?>
                <input type="hidden" name="set" id="attribute-set-id" 
                value="<?= $escaper->escapeHtml($allowedSets[0]['value']) ?>" />
            <?php endif; ?>

            <div class="field">
                <label class="label"><?= $escaper->escapeHtml(__('Product Category')) ?>:</label>
                <?php if ($product_hint_status && $helper->getProductHintCategory()): ?>
                    <img src="<?= $escaper->escapeUrl($block
                    ->getViewFileUrl('Webkul_Marketplace::images/quest.png')); ?>"
                     class='questimg' title="<?= $escaper->escapeHtml($helper->getProductHintCategory()) ?>"/>
                <?php endif; ?>
                <?php if ($helper->getIsAdminViewCategoryTree()) { ?>
                    <div data-bind="scope: 'sellerCategory'">
                        <!-- ko template: getTemplate() --><!-- /ko -->
                    </div>
                    <script type="text/x-magento-init">
                        {
                            "*": {
                                "Magento_Ui/js/core/app": {
                                    "components": {
                                        "sellerCategory": {
                                            "component": "Webkul_Marketplace/js/product/seller-category-tree",
                                            "template" : "Webkul_Marketplace/seller-category-tree",
                                            "filterOptions": true,
                                            "levelsVisibility": "1",
                                            "options": <?= /* @noEscape */ $block->getCategoriesTree()?>,
                                            "value": <?= /* @noEscape */ json_encode($data['product']['category_ids'])?>
                                        }
                                    }
                                }
                            }
                        }
                    </script>
                <?php } else { ?>
                    <div class="wk-field wk-category">
                        <div class="wk-for-validation">
                            <div id="wk-category-label"><?= $escaper->escapeHtml(__("CATEGORIES")); ?></div>
                            <?php
                            $categories = $data['product']['category_ids'];
                            foreach ($categories as $value) { ?>
                                <input type="hidden" name="product[category_ids][]" 
                                value="<?= $escaper->escapeHtml($value); ?>"
                                 id="wk-cat-hide<?= $escaper->escapeHtml($value); ?>"/>
                            <?php } ?>
                            <?php
                            if ($helper->getAllowedCategoryIds()) {
                                $storeconfig_catids = explode(',', trim($helper->getAllowedCategoryIds()));
                                foreach ($storeconfig_catids as $storeconfig_catid) {
                                    $cat_model = $block->getCategory()->load($storeconfig_catid);
                                    if (isset($cat_model["entity_id"]) && $cat_model["entity_id"]) {
                                        ?>
                                        <div class="wk-cat-container">
                                            </span><span class="wk-foldersign"></span>
                                            <span class="wk-elements wk-cat-name">
                                                <?= $escaper->escapeHtml($cat_model->getName()) ?>
                                            </span>
                                            <?php
                                            if (in_array($cat_model["entity_id"], $categories)) {?>
                                                <input class="wk-elements" type="checkbox" 
                                                name="product[category_ids][]" 
                                                value=<?= $escaper->escapeHtml($cat_model['entity_id']) ?> checked />
                                                <?php
                                            } else { ?>
                                                <input class="wk-elements" type="checkbox" 
                                                name="product[category_ids][]" 
                                                value='<?= $escaper->escapeHtml($cat_model['entity_id']) ?>'/>
                                                <?php
                                            } ?>
                                        </div>
                                        <?php
                                    }
                                }
                            } else {
                                $count = 0;
                                $category_helper = $viewModel->getCategoryHelper();
                                $category_model = $block->getCategory();
                                $_categories = $category_helper->getStoreCategories();
                                foreach ($_categories as $_category) {
                                    $count++;
                                    if (count($category_model->getAllChildren($category_model
                                    ->load($_category['entity_id'])))-1 > 0) { ?>
                                        <div class="wk-cat-container" style="margin-left:0px;">
                                            <span class="wk-plus">
                                            </span><span class="wk-foldersign"></span>
                                            <span class="wk-elements wk-cat-name">
                                                <?= $escaper->escapeHtml($_category->getName()) ?>
                                            </span>
                                            <?php
                                            if (in_array($_category["entity_id"], $categories)) {?>
                                                <input class="wk-elements" type="checkbox" 
                                                name="product[category_ids][]"
                                                 value=<?= $escaper->escapeHtml($_category['entity_id']) ?> checked />
                                                <?php
                                            } else { ?>
                                                <input class="wk-elements" type="checkbox" 
                                                name="product[category_ids][]" 
                                                value='<?= $escaper->escapeHtml($_category['entity_id']) ?>'/>
                                                <?php
                                            } ?>
                                        </div>
                                        <?php
                                    } else { ?>
                                        <div class="wk-cat-container">
                                            </span><span class="wk-foldersign"></span>
                                            <span class="wk-elements wk-cat-name">
                                                <?= $escaper->escapeHtml($_category->getName()) ?></span>
                                            <?php
                                            if (in_array($_category["entity_id"], $categories)) {?>
                                                <input class="wk-elements" type="checkbox" 
                                                name="product[category_ids][]" 
                                                value=<?= $escaper->escapeHtml($_category['entity_id']) ?> checked />
                                                <?php
                                            } else { ?>
                                                <input class="wk-elements" type="checkbox"
                                                 name="product[category_ids][]" 
                                                 value='<?= $escaper->escapeHtml($_category['entity_id']) ?>'/>
                                                <?php
                                            } ?>
                                        </div>
                                        <?php
                                    }
                                }
                            } ?>
                        </div>
                    </div>
                <?php } ?>
            </div>
            <div class="field required">
                <label class="label"><?= $escaper->escapeHtml(__('Product Name')) ?>:</label>
                <?php
                if ($product_hint_status && $helper->getProductHintName()) {?>
                    <img src="<?= $escaper->escapeUrl($block
                    ->getViewFileUrl('Webkul_Marketplace::images/quest.png')); ?>"
                     class='questimg' title="<?= $escaper->escapeHtml($helper->getProductHintName()) ?>"/>
                    <?php
                } ?>
                <div class="control">
                    <input type="text" class="required-entry input-text" name="product[name]"
                     id="name" value="<?= $escaper->escapeHtml($data['product']['name'])?>"/>
                </div>
            </div>
            <div class="field required">
                <label class="label"><?= $escaper->escapeHtml(__('Description')) ?>:</label>
                <?php
                if ($product_hint_status && $helper->getProductHintDesc()) {?>
                    <img src="<?= $escaper->escapeUrl($block
                    ->getViewFileUrl('Webkul_Marketplace::images/quest.png')); ?>" class='questimg' 
                    title="<?=  $escaper->escapeHtml($helper->getProductHintDesc()) ?>"/>
                    <?php
                } ?>
                <div class="control wk-border-box-sizing">
                    <textarea name="product[description]" class="required-entry input-text" 
                    id="description" rows="5" cols="75" >
                    <?= /* @noEscape */  $data['product']['description']?></textarea>
                    <?php if ($helper->isWysiwygEnabled()): ?>
                        <script>
                            require([
                                "jquery",
                                "mage/translate",
                                "mage/adminhtml/events",
                                "mage/adminhtml/wysiwyg/tiny_mce/setup"
                            ], function(jQuery) {
                                wysiwygDescription = new wysiwygSetup("description", {
                                    "width" : "100%",
                                    "height" : "200px",
                                    "plugins" : [{"name":"image"}],
                                    "tinymce" : {
                                        "toolbar":"formatselect | bold italic underline | "+
                                        "alignleft aligncenter alignright |" + 
                                        "bullist numlist |"+
                                        "link table charmap","plugins":"advlist "+
                                        "autolink lists link charmap media noneditable table "+
                                        "contextmenu paste code help table",
                                    },
                                    files_browser_window_url: "<?= /* @noEscape */$block->getWysiwygUrl();?>"
                                });
                                wysiwygDescription.setup("exact");
                            });
                        </script>
                    <?php endif; ?>
                </div>
            </div>

            <div class="field">
                <label class="label"><?= $escaper->escapeHtml(__('Short Description')) ?>:</label>
                <?php if ($product_hint_status && $helper->getProductHintShortDesc()) { ?>
                    <img src="<?= $escaper->escapeUrl($block
                    ->getViewFileUrl('Webkul_Marketplace::images/quest.png')); ?>"
                     class='questimg' title="<?= $escaper->escapeHtml($helper->getProductHintShortDesc()) ?>"/>
                <?php } ?>
                <div class="control wk-border-box-sizing">
                    <textarea name="product[short_description]" class="input-text"
                     id="short_description" rows="5" cols="75" >
                     <?= /* @noEscape */ $data['product']['short_description']?></textarea>
                    <?php if ($helper->isWysiwygEnabled()): ?>
                        <script>
                            require([
                                "jquery",
                                "mage/translate",
                                "mage/adminhtml/events",
                                "mage/adminhtml/wysiwyg/tiny_mce/setup"
                            ], function(jQuery) {
                                wysiwygShortDescription = new wysiwygSetup("short_description", {
                                    "width" : "100%",
                                    "height" : "200px",
                                    "plugins" : [{"name":"image"}],
                                    "tinymce" : {
                                        "toolbar":"formatselect | bold italic underline | "+
                                        "alignleft aligncenter alignright |" + 
                                        "bullist numlist |"+
                                        "link table charmap","plugins":"advlist "+
                                        "autolink lists link charmap media noneditable table "+
                                        "contextmenu paste code help table",
                                    },
                                    files_browser_window_url: "<?= /* @noEscape */$block->getWysiwygUrl();?>"
                                });
                                wysiwygShortDescription.setup("exact");
                            });
                        </script>
                    <?php endif; ?>
                </div>
            </div>
            <?php if ($skuType == 'static'): ?>
                <div class="field required">
                    <label class="label"><?= $escaper->escapeHtml(__('SKU')) ?>:</label>
                    <?php
                    if ($skuPrefix && $skuType == 'dynamic') {
                        /* @noEscape */ echo "(Prefix - ".$skuPrefix.")";
                    }
                    ?>
                    <?php if ($product_hint_status && $helper->getProductHintSku()): ?>
                        <img src="<?= $escaper->escapeUrl($block
                        ->getViewFileUrl('Webkul_Marketplace::images/quest.png')); ?>" class='questimg' 
                        title="<?= $escaper->escapeHtml($helper->getProductHintSku()) ?>"/>
                    <?php endif; ?>
                    <div class="control">
                        <input name="product[sku]" id="sku" 
                        class="required-entry validate-length maximum-length-64 input-text" type="text" 
                        value="<?= $escaper->escapeHtml($data['product']['sku'])?>"/>
                    </div>
                    <div id="skuavail" >
                        <span class="success-msg skuavailable"><?= $escaper->escapeHtml(__('SKU Available')) ?></span>
                    </div>
                    <div id="skunotavail" >
                        <span class="error-msg skunotavailable">
                            <?= $escaper->escapeHtml(__('SKU Already Exist')) ?></span>
                    </div>
                </div>
            <?php endif; ?>
            <div class="field required">
                <label class="label"><?= $escaper->escapeHtml(__('Price')) ?><b>
                    <?= /* @noEscape */ " (".$currency_symbol.")"; ?></b>:</label>
                <?php if ($product_hint_status && $helper->getProductHintPrice()): ?>
                    <img src="<?= $escaper->escapeUrl($block
                    ->getViewFileUrl('Webkul_Marketplace::images/quest.png')); ?>" class='questimg' 
                    title="<?= $escaper->escapeHtml($helper->getProductHintPrice()) ?>"/>
                <?php endif; ?>
                <div class="control">
                    <input type="text" class="required-entry validate-zero-or-greater input-text" 
                    name="product[price]" id="price" value="<?= /* @noEscape */ $data['product']['price']?>"/>
                </div>
            </div>
            <div class="field">
                <label class="label"><?= $escaper->escapeHtml(__('Special Price')) ?><b>
                    <?= /* @noEscape */ " (".$currency_symbol.")"; ?></b>:</label>
                <?php if ($product_hint_status && $helper->getProductHintSpecialPrice()): ?>
                    <img src="<?= $escaper->escapeUrl($block
                    ->getViewFileUrl('Webkul_Marketplace::images/quest.png')); ?>" class='questimg' 
                    title="<?= $escaper->escapeHtml($helper->getProductHintSpecialPrice()) ?>"/>
                <?php endif; ?>
                <div class="control">
                    <input type="text" class="widthinput input-text validate-zero-or-greater"
                     name="product[special_price]" id="special-price" 
                     value="<?= /* @noEscape */ $data['product']['special_price']?>"/>
                </div>
            </div>
            <div class="field">
                <label class="label"><?= $escaper->escapeHtml(__('Special Price From')) ?>:</label>
                <?php if ($product_hint_status && $helper->getProductHintStartDate()): ?>
                    <img src="<?= $escaper->escapeUrl($block
                    ->getViewFileUrl('Webkul_Marketplace::images/quest.png')); ?>" class='questimg' 
                    title="<?= $escaper->escapeHtml($helper->getProductHintStartDate()) ?>"/>
                <?php endif; ?>
                <div class="control">
                    <input type="text" name="product[special_from_date]" id="special-from-date" 
                    class="input-text" value="<?= /* @noEscape */ $data['product']['special_from_date']?>"/>
                </div>
            </div>
            <div class="field">
                <label class="label"><?= $escaper->escapeHtml(__('Special Price To')) ?>:</label>
                <?php if ($product_hint_status && $helper->getProductHintEndDate()): ?>
                    <img src="<?= $escaper->escapeUrl($block
                    ->getViewFileUrl('Webkul_Marketplace::images/quest.png')); ?>" class='questimg' 
                    title="<?= $escaper->escapeHtml($helper->getProductHintEndDate()) ?>"/>
                <?php endif; ?>
                <div class="control">
                    <input type="text" name="product[special_to_date]" id="special-to-date" 
                    class="input-text" value="<?= /* @noEscape */ $data['product']['special_to_date']?>"/>
                </div>
            </div>
            <input id="inventory_manage_stock" type="hidden" name="product[stock_data][manage_stock]" value="1">
            <input type="hidden" value="1" name="product[stock_data][use_config_manage_stock]" 
            id="inventory_use_config_manage_stock">
            <div class="field required">
                <label class="label"><?= $escaper->escapeHtml(__('Stock')) ?>:</label>
                <?php if ($product_hint_status && $helper->getProductHintQty()): ?>
                    <img src="<?= $escaper->escapeUrl($block
                    ->getViewFileUrl('Webkul_Marketplace::images/quest.png')); ?>" class='questimg' 
                    title="<?= $escaper->escapeHtml($helper->getProductHintQty()) ?>"/>
                <?php endif; ?>
                <div class="control">
                    <input type="text" class="required-entry validate-number input-text" 
                    name="product[quantity_and_stock_status][qty]" id="qty" 
                    value="<?= /* @noEscape */ $data['product']['quantity_and_stock_status']['qty']?>"/>
                </div>
            </div>
            <div class="field required">
                <label class="label"><?= $escaper->escapeHtml(__('Stock Availability')) ?>:</label>
                <?php if ($product_hint_status && $helper->getProductHintStock()): ?>
                    <img src="<?= $escaper->escapeUrl($block
                    ->getViewFileUrl('Webkul_Marketplace::images/quest.png')); ?>" 
                    class='questimg' title="<?= $escaper->escapeHtml($helper->getProductHintStock()) ?>"/>
                <?php endif; ?>
                <div class="control">
                    <select id="" class="select" name="product[quantity_and_stock_status][is_in_stock]">
                        <option value="1" <?php if ($data['product']['quantity_and_stock_status']['is_in_stock'] == 1) {
                             echo "selected='selected'";}?>><?= $escaper->escapeHtml(__("In Stock")); ?></option>
                        <option value="0" <?php if ($data['product']['quantity_and_stock_status']['is_in_stock'] == 0) {
                             echo "selected='selected'";}?>><?= $escaper->escapeHtml(__("Out of Stock")); ?></option>
                    </select>
                </div>
            </div>
            <div class="field required">
                <label class="label"><?= $escaper->escapeHtml(__('Visibility')) ?>:</label>
                <div class="control">
                    <select id="visibility" class=" required-entry required-entry select" name="product[visibility]">
                        <option value=""><?= $escaper->escapeHtml(__('Please Select'))?></option>
                        <?php $product_visibility = $helper->getVisibilityOptionArray(); ?>
                        <?php foreach ($product_visibility as $key => $value): ?>
                            <option value="<?= /* @noEscape */ $key ?>"
                             <?php if ($key==$data['product']['visibility']) {
                                    echo "selected='selected'";}?>><?=  /* @noEscape */ $value?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="field required">
                <label class="label"><?= $escaper->escapeHtml(__('Tax Class')) ?>:</label>
                <?php if ($product_hint_status && $helper->getProductHintTax()): ?>
                    <img src="<?= $escaper->escapeUrl($block
                    ->getViewFileUrl('Webkul_Marketplace::images/quest.png')); ?>"
                     class='questimg' title="<?= $escaper->escapeHtml($helper->getProductHintTax()) ?>"/>
                <?php endif; ?>
                <div class="control">
                    <select id="tax-class-id" class=" required-entry required-entry select" 
                    name="product[tax_class_id]">
                        <option value="0"><?= $escaper->escapeHtml(__('None'))?></option>
                        <?php $taxes = $helper->getTaxClassModel(); ?>
                        <?php foreach ($taxes as $tax): ?>
                            <option value="<?= $escaper->escapeHtml($tax->getId()) ?>" 
                            <?php if ($tax->getId()==$data['product']['tax_class_id']) { echo "selected='selected'";}?>>
                            <?= $escaper->escapeHtml($tax->getClassName())?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="field required">
                <label class="label"><?= $escaper->escapeHtml(__('Weight')) ?> (<?= $escaper
                ->escapeHtml($weightUnit)?>):</label>
                <?php if ($product_hint_status && $helper->getProductHintWeight()): ?>
                    <img src="<?= $escaper->escapeUrl($block
                    ->getViewFileUrl('Webkul_Marketplace::images/quest.png')); ?>" class='questimg' 
                    title="<?= $escaper->escapeHtml($helper->getProductHintWeight()) ?>"/>
                <?php endif; ?>
                <div data-role="weight-switcher">
                    <label data-ui-id="product-tabs-attributes-tab-element-radios-product-product-has-weight-label"
                     for="weight-switcher">
                        <span><?= $escaper->escapeHtml(__('Does this have a weight?'))?></span>
                    </label>
                    <div class="control">
                        <div class="control">
                            <input type="radio" <?php if ($type!='virtual' || $type!='downloadable' ||
                             $data['product']['product_has_weight']==1) { ?> checked="checked" <?php } ?>
                              class="weight-switcher" id="weight-switcher1" value="1" 
                              name="product[product_has_weight]">
                            <label for="weight-switcher1">
                                <span><?= $escaper->escapeHtml(__('Yes'))?></span>
                            </label>
                        </div>
                        <div class="control">
                            <input type="radio" class="weight-switcher" id="weight-switcher0" value="0" 
                            name="product[product_has_weight]" <?php if ($type=='virtual' || $type=='downloadable' ||
                             $data['product']['product_has_weight']==0) { ?> checked="checked" <?php } ?>>
                            <label for="weight-switcher0">
                                <span><?= $escaper->escapeHtml(__('No'))?></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="control">
                    <input type="text" class="validate-zero-or-greater input-text" name="product[weight]" 
                    id="weight" value="<?= /* @noEscape */ $data['product']['weight']?>"/>
                </div>
            </div>

            <div class="field">
                <label class="label"><?= $escaper->escapeHtml(__('Url Key')) ?>:</label>
                <div class="control">
                    <input type="text" class="input-text" name="product[url_key]" id="meta_title" 
                     value="<?= /* @noEscape */ $data['product']['url_key']?>"/>
                </div>
            </div>
            <?php if (!$helper->getCustomerSharePerWebsite()): ?>
                <div class="field required">
                    <label class="label"><?= $escaper->escapeHtml(__('Product in Websites')) ?>:</label>
                    <div class="control">
                        <select id="websites" class="required-entry select" name="product[website_ids][]" multiple>
                            <?php $websites = $helper->getAllWebsites(); ?>
                            <?php foreach ($websites as $website): ?>
                                <option value="<?= /* @noEscape */ $website->getWebsiteId() ?>">
                                <?=  /* @noEscape */ $website->getName()?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            <?php endif; ?>
            <div class="field">
                <label class="label"><?= $escaper->escapeHtml(__('Meta Title')) ?>:</label>
                <div class="control">
                    <input type="text" class="input-text" name="product[meta_title]" id="meta_title" 
                     value="<?= /* @noEscape */ $data['product']['meta_title']?>"/>
                </div>
            </div>
            <div class="field">
                <label class="label"><?= $escaper->escapeHtml(__('Meta Keywords')) ?>:</label>
                <div class="control">
                    <textarea class="textarea" id="meta_keyword"
                     name="product[meta_keyword]"><?= /* @noEscape */ $data['product']['meta_keyword']?></textarea>
                </div>
            </div>
            <div class="field">
                <label class="label"><?= $escaper->escapeHtml(__('Meta Description')) ?>:</label>
                <div class="control">
                    <textarea class="textarea" id="meta_description" name="product[meta_description]">
                        <?= /* @noEscape */ $data['product']['meta_description']?></textarea>
                </div>
            </div>
            <?= $block->getChildHtml(); ?>
        </fieldset>
    </div>
</form>
<?php
$formData = [
    'countryPicSelector' => '#country-pic',
    'verifySkuAjaxUrl' => $block->getUrl('marketplace/product/verifysku', ['_secure' => $block
    ->getRequest()->isSecure()]),
    'categoryTreeAjaxUrl' => $block->getUrl('marketplace/product/categorytree/', ['_secure' => $block
    ->getRequest()->isSecure()])
];
$serializedFormData = $viewModel->getJsonHelper()->jsonEncode($formData);
?>

<script type="text/x-magento-init">
    {
        "*": {
            "sellerAddProduct": <?= /* @noEscape */ $serializedFormData; ?>
        }
    }
</script>
<script type='text/javascript'>
    require(['jquery', 'prototype', 'domReady!'], function($) {
        var qty = $('#qty'),
            productType = $('#product_type_id').val(),
            stockAvailabilityField = $('#quantity_and_stock_status'),
            manageStockField = $('#inventory_manage_stock'),
            useConfigManageStockField = $('#inventory_use_config_manage_stock'),
            fieldsAssociations = {
                'qty': 'inventory_qty',
                'quantity_and_stock_status': 'inventory_stock_availability'
            };

        var qtyDefaultValue = qty.val();
    })
</script>
<script>
    require([
        "jquery",
        "Webkul_Marketplace/catalog/type-events"
    ], function($, TypeSwitcher){
        var $form = $('[data-form=edit-product]');
        $form.data('typeSwitcher', TypeSwitcher.init());
    });
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Webkul_Marketplace/js/product/weight-handler": {},
            "Webkul_Marketplace/catalog/apply-to-type-switcher": {}
        }
    }
</script>


<style>

    /* ToolTip classses */ 
/* .tooltip {
    display: inline-block;    
}
.tooltip .tooltiptext {
    margin-left:9px;
    width : 570px;
    visibility: hidden;
    background-color: #FFF;
    border-radius:4px;
    border: 1px solid #aeaeae;
    position: absolute;
    z-index: 9999!important;
    padding: 5px;
    margin-top : -15px; 
    opacity: 0;
    transition: opacity 0.5s;
   font-size: small;
    font-family: 'Poppins';
    text-transform: none;
    font-style: normal;
}
.tooltip .tooltiptext::after {
    content: " ";
    position: absolute;
    top: 5%;
    right: 100%;  
    margin-top: -5px;
    border-width: 5px;
    border-style: solid;
    border-color: transparent #aeaeae transparent transparent;
}
.tooltip:hover .tooltiptext {
    visibility: visible;
    opacity: 1;
} */

/* .tooltip {
  position: relative;
  display: inline-block;
  border-bottom: 1px dotted black;
  cursor: pointer;
}

.tooltip .tooltiptext {
  visibility: hidden;
  width: 920px;
  background-color:white ;
  color: #0088cc;
  text-align: center;
  border-radius: 6px;
  padding: 5px 5px;
  font-size:14px;
  text-align:left;


  /* Position the tooltip */
  /* position: absolute;
  z-index: 9999;
  overflow-y: auto;
    max-height: 520px;
}

.tooltip.active .tooltiptext {
  visibility: visible;
  
}


    </style>
    <script>
var tooltip = document.querySelector('.tooltip')

tooltip.addEventListener('click', function() {
  if (this.classList.contains('active')) {
    this.classList.remove('active');
  } else {
    this.classList.add('active');
  }
  
}); 
        </script> */

        <style>
        @media (max-width:600px)
        {
      

body .wk-mp-column .wk-mp-fixed {
    width: calc(100% - 0px)!important;
        }
}
        </style>