<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAdvancedBookingSystem
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

?>
<?php /** @var $block \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Options\Option */ ?>
<?= $block->getTemplatesHtml() ?>
<?php $params = $block->getRequest()->getParams(); ?>
<script id="custom-option-base-template" type="text/x-magento-template">
    <div class="fieldset-wrapper admin__collapsible-block-wrapper opened" id="option_<%- data.id %>">
        <div class="fieldset-wrapper-content in collapse" id="<%- data.id %>-content">
            <fieldset class="fieldset">
                <fieldset class="fieldset-alt wk-bk-hide"
                        id="<?= /* @noEscape */ $block->getFieldId() ?>_<%- data.id %>">
                    <input id="<?= /* @noEscape */ $block->getFieldId() ?>_<%- data.id %>_is_delete"
                        name="<?= /* @noEscape */ $block->getFieldName() ?>[<%- data.id %>][is_delete]"
                        type="hidden" value=""/>
                    <!-- <input id="<?= /* @noEscape */ $block->getFieldId() ?>_<%- data.id %>_previous_type"
                        name="<?= /* @noEscape */ $block->getFieldName() ?>[<%- data.id %>][previous_type]"
                        type="hidden" value="<%- data.type %>"/> -->
                    <!-- <input id="<?= /* @noEscape */ $block->getFieldId() ?>_<%- data.id %>_previous_group"
                        name="<?= /* @noEscape */ $block->getFieldName() ?>[<%- data.id %>][previous_group]"
                        type="hidden" value=""/> -->
                    <input id="<?= /* @noEscape */ $block->getFieldId() ?>_<%- data.id %>_id"
                        name="<?= /* @noEscape */ $block->getFieldName() ?>[<%- data.id %>][data-id]"
                        type="hidden" value="<%- data.id %>"/>
                    <input id="<?= /* @noEscape */ $block->getFieldId() ?>_<%- data.id %>_option_id"
                        name="<?= /* @noEscape */ $block->getFieldName() ?>[<%- data.id %>][option_id]"
                        type="hidden" value="<%- data.option_id %>"/>
                    <input id="<?= /* @noEscape */ $block->getFieldId() ?>_<%- data.id %>_record_id"
                        name="<?= /* @noEscape */ $block->getFieldName() ?>[<%- data.id %>][record_id]"
                        type="hidden" value="<%- data.option_id %>"/>
                    <input name="<?= /* @noEscape */ $block->getFieldName() ?>[<%- data.id %>][sort_order]"
                        type="hidden" value="<%- data.sort_order %>"/>
                    <input name="<?= /* @noEscape */ $block->getFieldName() ?>[<%- data.id %>][product_id]"
                        type="hidden" value="<?= /* @noEscape */ $block->getCurrentProductId(); ?>"/>
                    <input name="<?= /* @noEscape */ $block->getFieldName() ?>[<%- data.id %>][sku]"
                        type="hidden" value=""/>
                    <input name="<?= /* @noEscape */ $block->getFieldName() ?>[<%- data.id %>][price]"
                        type="hidden" value=""/>
                    <input name="<?= /* @noEscape */ $block->getFieldName() ?>[<%- data.id %>][price_type]"
                        type="hidden" value="fixed"/>
                    <input name="<?= /* @noEscape */ $block->getFieldName() ?>[<%- data.id %>][is_use_default]"
                        type="hidden" value="false"/>
                    <div class="field field-option-title required">
                        <label class="label" for="<?= /* @noEscape */ $block->getFieldId() ?>_<%- data.id %>_title">
                            <?= /* @noEscape */ __('Option Title') ?>
                        </label>
                        <div class="control">
                            <input id="<?= /* @noEscape */ $block->getFieldId() ?>_<%- data.id %>_title"
                                name="<?= /* @noEscape */ $block->getFieldName() ?>[<%- data.id %>][title]"
                                class="required-entry input-text"
                                type="text"
                                value="Event Tickets"
                                data-store-label="<%- data.title %>"
                                <% if (typeof data.scopeTitleDisabled != 'undefined'
                                    && data.scopeTitleDisabled != null) { %> disabled="disabled" <% } %>
                                >
                            <%- data.checkboxScopeTitle %>
                        </div>
                    </div>

                    <div class="field field-option-input-type required">
                        <label class="label" for="<?= /* @noEscape */ $block->getFieldId() ?>_<%- data.id %>_title">
                            <?= /* @noEscape */ __('Input Type') ?>
                        </label>
                        <div class="control opt-type">
                            <?= $block->getTypeSelectHtml() ?>
                        </div>
                    </div>

                    <div class="field field-option-req">
                        <div class="control">
                            <input id="<?= /* @noEscape */ $block->getFieldId() ?>_<%- data.id %>_required"
                                class="is-required" type="checkbox" checked="checked"/>
                            <label for="field-option-req">
                                <?= /* @noEscape */ __('Required') ?>
                            </label>
                            <span style="display:none"><?= $block->getRequireSelectHtml() ?></span>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
        </div>
    </div>
</script>

<div id="import-container" style="display: none;"></div>

<?php if (!$block->isReadonly()): ?>
    <div><input type="hidden" name="affect_product_custom_options" value="1"/></div>
<?php endif; ?>

<script>
    require([
        "jquery",
        "Webkul_MpAdvancedBookingSystem/js/product/event/custom-options"
    ], function(jQuery){

        jQuery(function ($) {
            var fieldSet = $('[data-block=booking-product-custom-options]');
            fieldSet.customOptions(<?= /* @noEscape */
                $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode(
                    [
                        'fieldId' => $block->getFieldId(),
                        'productGridUrl' => $block->getProductGridUrl(),
                        'formKey' => $block->getFormKey(),
                        'customOptionsUrl' => $block->getCustomOptionsUrl(),
                        'isReadonly' => $block->isReadonly(),
                        'itemCount' => $block->getItemCount(),
                        'optItemCount' => $block->getItemCount(),
                        'currentProductId' => $block->getCurrentProductId(),
                    ]
                )?>);
            //adding data to templates
            <?php /** @var $_value \Magento\Framework\DataObject */ ?>
            <?php foreach ($block->getOptionValues() as $_value): ?>
                fieldSet.customOptions('addOption', <?= /* @noEscape */ $_value->toJson() ?>);
            <?php endforeach; ?>
        });
    });
</script>



