<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpRmaSystem
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    $helper = $block->helper();
?>
<?php if ($helper->isGuestLoggedIn()): ?>
    <div class="wk-guest-logout">
        <a href="<?= $escaper->escapeUrl($block->getUrl('mprmasystem/guest/logout')); ?>">
            <?= $escaper->escapeHtml(__("Log Out")); ?>
        </a>
    </div>
<?php endif; ?>