<?php
/**
 * Webkul Software.
 *
 * @category Webkul
 * @package Webkul_MpStripe
 * @author Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license https://store.webkul.com/license.html
 */
$marketplaceHelper = $block->marketplaceHelper();
$helper = $block->getStripeHelper();
$class = "savempstripedata";

    /**
     * $seller seller data
     * @var Magento\Customer\Model\Customer
     */
    $seller = $block->getCurrentCustomer();
    
    $integrationType = $block->getIntegration();

    /**
     * $selleremail seller email
     * @var string
     */
    $selleremail = $seller->getEmail();

    /**
     * $sellerid seller id
     * @var int
     */
    $sellerid = $seller->getId();

    /**
     * $partner get Seller Profile Details
     * @var Webkul\Marketplace\Model\Seller
     */
    $partner = $block->getSellerDataBySellerId();

    /**
     * $request request data
     * @var array
     */
    $request = $block->getRequestData();

    $shopName = $partner['shop_title'];
    $customerFname = $seller->getFirstName();
    $customerLname = $seller->getLastName();

    $storeUrl = $block->getUrl('marketplace/seller/profile/'.$partner['shop_url']);
    $baseurl = $block->getUrl('mpstripe/seller/connect');

    $contactEmail = $selleremail;
    $storePhone = $seller['phone'];
    $storeCity = $seller['city'];
    $storeStreet = $seller['street'];
    $storeZip = $seller['postcode'];
    $accessToken = '';
    $refreshToken = '';
    $stripeUserId = '';
    $stripePublishableKey = '';
    $stripeClientId = $helper->getConfigValue('client_secret');
    $stripeClientSecret = $helper->getConfigValue('api_key');
    $sellerCollection = $block->getStripeSellerFactory();
foreach ($sellerCollection as $value) {
    $accessToken = $value['access_token'];
    $stripeUserId = $value['stripe_user_id'];
}
?>
<?php
// stripe connect integration
if ($integrationType) {
    if ($accessToken != '') {
        $flag = $block->checkValidAccount();
        if ($flag == 2) { ?>
            <div class="fieldset">
                <h4 class="legend"><?= /*@noEscape*/ __('Remove Previous Details & Reconnect') ?></h4>
                <p>
                <?= /*@noEscape*/
                __("Application access may have been revoked. ").
                __("Please remove the previous connection and reauthorize using the Stripe system.");
                ?>
                </p>
                <div class="row">
                    <form action="<?= $block
                    ->escapeUrl($block->getUrl("mpstripe/seller/remove/"));?>" method="post">
                        <?= /*@noEscape*/ $block->getBlockHtml('formkey')?>
                        <button type="submit" title="Save" class="button">
                            <span>
                                <span><?= /*@noEscape*/ __('Remove Previous Details') ?></span>
                            </span>
                        </button>
                    </form>
                </div>
            </div>
        <?php } else { ?>
            <div class="fieldset">
                <h4 class="legend"><?= /*@noEscape*/__('Update Account Information') ?></h4>
                <p>
                <?= /*@noEscape*/
                __("Save your bank account information using stripe connect if not added. ").
                __("If routing number or any other information changes please reauthorize using the Stripe system");
                ?>
                </p>
                <div class="row">
                    <a href="https://dashboard.stripe.com/account/transfers">
                        <button type="submit" title="Save" class="button">
                            <span>
                                <span><?= /*@noEscape*/__('Update Account Information') ?></span>
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        <?php } ?>
        <?php
    } else {
        if (isset($request['code']) && $request['code']) {
            $code = $request['code'];
            $tokenRequestBody = [
                'grant_type' => 'authorization_code',
                'client_id' => $stripeClientId,
                'code' => $code,
                'client_secret' => $stripeClientSecret
            ];

            $resp = $block->getStripeTokens($tokenRequestBody);

            if (isset($resp['error_description'])
                && $resp['error_description'] != ''
            ) { ?>
                <ul class="messages" id="mpstripe_msg" style="display:none;">
                    <li class="error-msg">
                        <span id="paymenterrors">
                            <?= $block->escapeHtml($resp['error_description']);
                            ?>
                        </span>
                    </li>
                </ul>
                <?php
            } else {
                $accessToken = $resp['access_token'];
                $refreshToken = $resp['refresh_token'];
                $stripePublishableKey = $resp['stripe_publishable_key'];
                $stripeUserId = $resp['stripe_user_id'];
            }
        } elseif (isset($request['error'])) {
            $error = $request['error_description'];
            if ($error != '') { ?>
                <ul class="messages" id="mpstripe_msg">
                    <li class="error-msg">
                        <span id="paymenterrors">
                            <?= $block->escapeHtml($error); ?>
                        </span>
                    </li>
                </ul>
                <?php
            }
        }
        $data='&response_type=code&stripe_landing=register&scope=read_write&';
        $errorValue = $block->checkKeys(
            $stripeClientId,
            $contactEmail,
            $data,
            $storeUrl,
            $partner['country_pic'],
            $seller->getId(),
            $customerFname,
            $customerLname,
            $storePhone,
            $shopName,
            $block->getUrl('mpstripe/seller/connect')
        );
        if ($errorValue) {
            $class = "";
            ?>
            <p id="danger"><?=/*@noEscape*/ __("Invalid credentials. Please contact admin to correct them");?></p>
            <?php
        }
        ?>
        <div class="fieldset">
            <h4 class="legend"><?= /*@noEscape*/ __('Connect to Stripe') ?></h4>
            <form enctype="multipart/form-data" method="post" id="mpstrip_payment_form">
                <input
                type="hidden"
                name="client_id"
                id="client_id"
                title="client_id"
                value="<?= $block->escapeHtml($stripeClientId);?>"
                />
                <input
                type="hidden"
                name="response_type"
                id="response_type"
                title="response_type"
                value="code"
                />
                <input
                type="hidden"
                name="stripe_landing"
                id="stripe_landing"
                title="stripe_landing"
                value="register"
                />
                <input
                type="hidden"
                name="scope"
                id="scope"
                title="scope"
                value="read_write"
                />
                <input
                type="hidden"
                name="stripe_user[email]"
                id="stripe_user[email]"
                title="stripe_user[email]"
                value="<?= $block->escapeHtml($contactEmail) ?>"
                />
                <input
                type="hidden"
                name="stripe_user[url]"
                id="stripe_user[url]"
                title="stripe_user[url]"
                value="<?= $block->escapeHtml($storeUrl) ?>"
                />
                <input
                type="hidden"
                name="stripe_user[country]"
                id="stripe_user[country]"
                value="<?= $block->escapeHtml($partner['country_pic'])?>"
                />
                <input
                type="hidden"
                name="stripe_user[currency]"
                id="stripe_user[currency]"
                value="<?= $block->escapeHtml('usd') ?>"
                />
                <input
                type="hidden"
                name="userid"
                id="userid"
                value="<?= $block->escapeHtml($seller->getId()); ?>"
                title="userid"
                />
                <input
                type="hidden"
                name="stripe_user[first_name]"
                id="stripe_user[first_name]"
                value="<?= $block->escapeHtml($customerFname) ?>"
                />
                <input
                type="hidden"
                name="stripe_user[last_name]"
                id="stripe_user[last_name]"
                value="<?= $block->escapeHtml($customerLname) ?>"
                />
                <input
                type="hidden"
                name="stripe_user[phone_number]"
                id="stripe_user[phone_number]"
                value="<?= $block->escapeHtml($storePhone) ?>"
                />
                <input
                type="hidden"
                name="stripe_user[business_name]"
                id="stripe_user[business_name]"
                value="<?= $block->escapeHtml($shopName) ?>"
                />
                <input
                type="hidden"
                name="stripe_user[redirect_uri]"
                id="stripe_user[redirect_uri]"
                value="<?= $block->escapeUrl($block->getUrl('mpstripe/seller/connect'));?>"
                />

                <img
                style="cursor:pointer;"
                class="<?= $block->escapeHtml($class); ?>"
                src="
                <?= $block->escapeUrl($block
                ->getViewFileUrl('Webkul_MpStripe::images/blue-on-light.png'))
                ?>"
                title="<?= /*@noEscape*/ __('Connect to Stripe') ?>"/>
            </form>

            <form
            enctype="multipart/form-data"
            method="post"
            id="form-mpstripepayment-save"
            style="display: hidden"
            >
                <?= $block->getBlockHtml('seller.formkey')?>
                <?= $block->getBlockHtml('formkey') ?>
                <input
                type="hidden"
                name="user_id"
                id="userid"
                value="<?= $block->escapeHtml($seller->getId()); ?>"
                title="userid"
                />
                <input
                type="hidden"
                name="stripe_user_id"
                id="stripe_user_id"
                value="<?= $block->escapeHtml($stripeUserId);?>"
                title="access"
                />
                <input
                type="hidden"
                name="access_token"
                id="access"
                value="<?= $block->escapeHtml($accessToken);?>"
                title="access"
                />
                <input
                type="hidden"
                name="refresh_token"
                id="refresh"
                value="<?= $block->escapeHtml($refreshToken) ?>"
                title="refresh"
                />
                <input
                type="hidden"
                name="key"
                id="key"
                value="<?= $block->escapeHtml($stripePublishableKey); ?>"
                title="key"
                />
                <input
                type="hidden"
                name="user_type"
                id="user_type"
                value="seller"
                title="user_type"
                />
                <input
                type="hidden"
                name="integration_type"
                id="integration_type"
                value="1"
                title="integration_type"
                />
                <input
                type="hidden"
                name="isverified"
                id="isverified"
                value=""
                title="key"
                />
            </form>
        </div>

        <?php
            $code = 0;
        if (isset($request['code']) && $request['code']) {
            $code = $request['code'];
        }
        ?>

        
        <script type="text/x-magento-init">
        {
            ".savempstripedata":{
                "stripeConnectJs":{
                    "connectData": {
                        "mpstrip_payment_form":"#mpstrip_payment_form",
                        "code": "<?= $block->escapeHtml($code); ?>",
                        "postUrl": "<?= $block->escapeUrl($block->getUrl('mpstripe/seller_connect/save')) ?>",
                        "formId": "#form-mpstripepayment-save",
                        "homeUrl": "<?= $block->escapeUrl($block->getUrl('mpstripe/seller/connect')) ?>"
                    }
                }
            }
        }
        </script>
        <?php
    }
} else {
    // stripe custom accounts integration
    $countryList = $block->getCountries();
    $businessType = $block->getBusinessType();
    $currencyList = $block->getCurrencyList();
    $allowManagement = $helper->getConfigValue('allow_management');
    
    if ($stripeUserId != '') {

        $accountLink = $block->getAccountLink();

        $stripeAccount = $block->getStripeCustomAccount($stripeUserId);
        ?>
        <div class="wk-mp-design" id="wk-bodymain">
            <?php
            $status = __("Not Connected");
            $message = __('Connect to Stripe via the button below');
            $showConnectButton = true;
            if (!empty($stripeAccount['requirements']['eventually_due'])) {
                $status = __("More Information Required");
                $message = __('Complete your details via the button below');
            } else {
                $status = __("Connected");
                $showConnectButton = false;
                $message = __('Success! You are connected to receive payments');
            }
            ?>
            <?php if (isset($accountLink['url'])) {
                ?>
                <div class="wk-mp-design" id="wk-bodymain">
                    <p><?= /*@noEscape*/ __('Status') ?> : <b> <?= $block->escapeHtml($status) ?> </b></p>
                    <i>
                        <?=  $block->escapeHtml($message) ?>
                    </i>
                </div>
                <?php if ($showConnectButton): ?>
                    <div class="wk-mp-design" id="wk-bodymain">
                        <a href="<?= $block->escapeUrl($accountLink['url']) ?>">
                            <button type="button" class="action primary">
                                <span><span><?= /*@noEscape*/ __('CONNECT TO STRIPE') ?></span></span>
                            </button>
                        </a>
                    </div>
                <?php endif; ?>
                <div class="wk-mp-design" id="wk-bodymain">
                    <?= /*@noEscape*/ $block->getConsentMessage() ?>
                    </div>
                <?php
            } else {
                if (isset($accountLink['error_message'])) {
                    ?>
                    <div class="message error empty">
                        <div><?= /*@noEscape*/ $accountLink['error_message'] ?></div>
                    </div>
                    <?php
                }
            } ?>
        </div>
        <?php
    } elseif (!$allowManagement) {
        ?>
        <div class="wk-mp-design" id="wk-bodymain">
            <p>
                <?= /*@noEscape*/ __('Please Contact admin for any discussion on Stripe Accounts'); ?>
            </p>
        </div>
        <?php
    } else {
        ?>
        <form action="<?= $block->escapeUrl($block
        ->getUrl('mpstripe/seller_connect/account', ['_secure' => $block->getRequest()->isSecure()])) ?>"
        enctype="multipart/form-data" method="post" id="edit-custom-accounts"
        data-form="edit-custom-accounts" data-mage-init='{"validation":{}}'>
            <div class="wk-mp-design" id="wk-bodymain">
                <fieldset class="fieldset info wk-mp-fieldset">
                    <div data-mage-init='{"formButtonAction": {}}' class="wk-mp-page-title legend">
                        <span><?=  /*@noEscape*/ __('Create Stripe Account') ?></span>
                        <button class="button wk-mp-btn"
                        title="<?=  /*@noEscape*/ __('Create Stripe Account') ?>" type="submit" id="save-btn">
                            <span><span><?=  /*@noEscape*/ __('Create Stripe Account') ?></span></span>
                        </button>
                    </div>
                    <?= $block->getBlockHtml('formkey')?>
                    <input
                    type="hidden"
                    name="stripe_user[user_id]"
                    id="userid"
                    value="<?= $block->escapeHtml($seller->getId()); ?>"
                    title="userid"
                    />
                    <div class="field required">
                        <label class="label"><?=  /*@noEscape*/ __('Country') ?>:</label>
                        <div class="control">
                            <select id="Country" class=" required-entry select" name="stripe_user[country]">
                                <option value=""><?=  /*@noEscape*/ __('Please Select')?></option>
                                <?php foreach ($countryList as $value):
                                    if ($value['value'] != '') { ?>
                                    <option value="<?= $block->escapeHtml($value['value']) ?>">
                                        <?= $block->escapeHtml($value['label']) ?></option>
                                <?php } endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="field required">
                        <label class="label"><?=  /*@noEscape*/ __('Email') ?>:</label>
                        <div class="control">
                            <input type="email" name="stripe_user[email]" id="stripe_user[email]"
                            title="stripe_user[email]" class="required-entry validate-email select"
                            value="<?= $block->escapeHtml($contactEmail) ?>" readonly="true"/>
                        </div>
                    </div>

                    <!-- bank account details -->
                    <input type="hidden" value="bank_account" name="stripe_user[external_accounts][object]">
                    <div class="field required">
                        <label class="label"><?=  /*@noEscape*/ __('Bank Account Country') ?>:</label>
                        <div class="control">
                            <select id="Country" class=" required-entry select"
                            name="stripe_user[external_accounts][country]">
                                <option value=""><?=  /*@noEscape*/ __('Please Select')?></option>
                                <?php foreach ($countryList as $value):
                                    if ($value['value'] != '') { ?>
                                    <option value="<?= $block->escapeHtml($value['value']) ?>">
                                        <?= $block->escapeHtml($value['label']) ?></option>
                                <?php } endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="field required">
                        <label class="label"><?=  /*@noEscape*/ __('Bank Account Currency') ?>:</label>
                        <div class="control">
                            <select id="currency" class=" required-entry select"
                            name="stripe_user[external_accounts][currency]">
                                <option value=""><?=  /*@noEscape*/ __('Please Select')?></option>
                                <?php foreach ($currencyList as $value):
                                    if ($value['value'] != '') { ?>
                                    <option value="<?= $block->escapeHtml($value['value']) ?>">
                                        <?= $block->escapeHtml($value['label']) ?></option>
                                <?php } endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="field required">
                        <label class="label"><?=  /*@noEscape*/ __('Bank Account Holder Type') ?>:</label>
                        <div class="control">
                            <select id="account_holder_type" class=" required-entry select"
                            name="stripe_user[external_accounts][account_holder_type]">
                                <option value=""><?=  /*@noEscape*/ __('Please Select')?></option>
                                <?php foreach ($businessType as $value):
                                    if ($value['value'] != '') { ?>
                                    <option value="<?= $block->escapeHtml($value['value']) ?>">
                                        <?= $block->escapeHtml($value['label']) ?></option>
                                <?php } endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="field required">
                        <label class="label"><?=  /*@noEscape*/ __('Bank Account Holder Name') ?>:</label>
                        <div class="control">
                        <input type="text" name="stripe_user[external_accounts][account_holder_name]"
                        value="" id="account_holder_name" class="input-text required-entry" />
                        </div>
                    </div>
                    <div class="field business_routing_number required">
                        <label class="label" for="business_routing_number">
                        <span><?= /*@noEscape*/ __('Bank Account Routing Number') ?></span></label>
                        <div class="control">
                            <input type="text" name="stripe_user[external_accounts][routing_number]" value=""
                            id="business_routing_number" class="input-text required-entry validate-digits" />
                        </div>
                        <?= /*@noEscape*/ $block->getPreviousMessage(); ?>
                    </div>
                    <div class="field business_account_number required">
                        <label class="label" for="business_account_number">
                        <span><?= /*@noEscape*/ __('Bank Account Number') ?></span></label>
                        <div class="control">
                            <input type="text" name="stripe_user[external_accounts][account_number]" value=""
                            id="business_account_number" class="input-text required-entry validate-digits" />
                        </div>
                        <?= /*@noEscape*/
                        __("The account number for the bank account, in string form. Must be a checking account.")
                        ?>
                    </div>
                    <div>
                    <?= /*@noEscape*/ $block->getConsentMessage() ?>
                    </div>
                </fieldset>
            </div>
        </form>
        <script type="text/x-magento-init">
            {
                "*": {
                    "customAccount": {
                            "accountType": ""
                    }
                }
            }
        </script>

        <?php
    }
}
