<!-- 
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Stripe
 * @author    Webkul Software Private Limited
 * @copyright Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
 -->
<?= $block->getButtonHtml() ?>

<script type="text/x-magento-init">
    {
        "*": {
            "webhooksGenerate" : {
                "url" : "<?= $escaper->escapeUrl($block->getAjaxUrl()) ?>"
            }
        }
    }
</script>