<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAdvancedBookingSystem
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$viewModel = $block->getBookingViewModel();
if ($viewModel === null) {
    $viewModel = $block->getLayout()->createBlock(
        \Webkul\MpAdvancedBookingSystem\Block\GetViewModel::class
    )->getBookingViewModel();
}

$helper = $viewModel->getHelper();
$productSetId = '';
$bookingSlotData = $helper->getJsonEcodedString([]);
$params = $block->getRequest()->getParams();

if (!empty($params['id'])) {
    $product = $block->getProduct($params['id']);
    if (!empty($product)) {
        $bookingInfo = $helper->getBookingInfo($product->getId());
        if (!empty($bookingInfo['info'])) {
            $bookingSlotData = $bookingInfo['info'];
        }
        $productSetId = $product->getAttributeSetId();
        $tableType = $helper->getProductAttributeSetIdByLabel('Table Booking');
        if ($productSetId != $tableType) {
            $bookingSlotData = [];
            $bookingSlotData = $helper->getJsonEcodedString($bookingSlotData);
        }
    }
} else {
    $product['price_charged_per_table'] = "";
    $product['no_of_guests'] = "";
    $product['max_capacity'] = "";
    $product['slot_duration'] = "";
    $product['break_time_bw_slot'] = "";
    $product['prevent_scheduling_before'] = "";
    $product['slot_for_all_days'] = 1;
    $product['show_map_loction'] = 1;
}
?>
<div class="field required">
    <label class="label" for="wk-booking-price_charged_per_table">
        <span>
            <?= /* @noEscape */ __('Charged Per')?>
        </span>
    </label>
    <?php $charges = $helper->getTableChargedPer(); ?>
    <div class="control">
        <select class="select wk-select-wide required-select price_charged_per_table"
                name="product[price_charged_per_table]" id="wk-booking-price_charged_per_table">
            <?php foreach ($charges as $key => $charge): ?>
                <option data-title="<?= /* @noEscape */ $charge ?>"
                        value="<?= /* @noEscape */ $key ?>" 
                        <?php if ($product['price_charged_per_table'] == $key) {?> selected="selected" <?php } ?>>
                    <?= /* @noEscape */ $charge?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
<div class="field" id="wk-guests_per_table">
    <label class="label" for="wk-no_of_guests">
        <span>
            <?= /* @noEscape */ __('Number Of Guests per Table')?>
        </span>
    </label>
    <div class="control">
        <input class="input-text validate-digits validate-greater-than-zero" type="number"
            name="product[no_of_guests]" value="<?= /* @noEscape */ $product['no_of_guests'] ?>"
            id="wk-no_of_guests" max="<?= /* @noEscape */ $product['max_capacity']?>" min="1">
    </div>
</div>
<div class="field required">
    <label class="label" for="wk-max_capacity">
        <span>
            <?= /* @noEscape */ __('Maximum Guests Capacity')?>
        </span>
    </label>
    <div class="control">
        <input class="input-text required-entry validate-digits validate-greater-than-zero" type="text"
            name="product[max_capacity]" value="<?= /* @noEscape */ $product['max_capacity']?>" id="wk-max_capacity">
    </div>
</div>
<div class="field required">
    <label class="label" for="wk-slot-duration">
        <span>
            <?= /* @noEscape */ __('Slot Duration')?> (<?= /* @noEscape */ __('Mins')?>)
        </span>
    </label>
    <div class="control">
        <input class="input-text required-entry validate-digits" type="text" name="product[slot_duration]"
            value="<?= /* @noEscape */ $product['slot_duration']?>" id="wk-slot-duration">
    </div>
</div>
<div class="field required">
    <label class="label" for="wk-break-time-bw-slot">
        <span>
            <?= /* @noEscape */ __('Break Time b/w Slots')?> (<?= /* @noEscape */ __('Mins')?>)
        </span>
    </label>
    <div class="control">
        <input class="input-text required-entry validate-digits" type="text"
            name="product[break_time_bw_slot]" value="<?= /* @noEscape */ $product['break_time_bw_slot']?>"
            id="wk-break-time-bw-slot">
    </div>
</div>
<div class="field required" data-index="show_contact_btn">
    <label class="label" for="wk-prevent-scheduling-before">
        <span>
            <?= /* @noEscape */ __('Prevent Scheduling Before')?>
        </span>
    </label>
    <div class="control">
        <input class="input-text required-entry validate-digits" type="text"
            name="product[prevent_scheduling_before]" id="wk-prevent-scheduling-before"
            value="<?= /* @noEscape */ $product['prevent_scheduling_before']?>">
    </div>
</div>
<div class="field toggle-field" id="wk-slot-for-all-days-wrapper">
    <label class="label" for="wk-slot-all-days">
        <span>
            <?= /* @noEscape */ __('Same Slot for All Days')?>
        </span>
    </label>
    <!-- <div class="control">
        <div class="switch" data-role="switcher">
            <input type="checkbox" class="switch-checkbox" id="wk-slot-all-days"
                name="product[slot_for_all_days]" value="1">
        </div>
    </div> -->
    <div class="admin__field-control">
        <div class="admin__actions-switch" data-role="switcher">
            <input type="checkbox" class="admin__actions-switch-checkbox"
                id="wk-slot-all-days" name="product[slot_for_all_days]" value="1">
            <label class="admin__actions-switch-label" for="wk-slot-all-days">
                <span class="admin__actions-switch-text" data-text-on="Yes" data-text-off="No"></span>
            </label>
        </div>
    </div>
</div>
<script id="wk-booking-same-slot-container-template" type="text/x-magento-template">
    <div class="field wk-booking-slot-row _show">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Slot Information')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container wk-bk-hide" id="wk-bk-label-slot-box-container1">
        </div>
        <div class="collapsible-content _show">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container1">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="1">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
</script>
<script id="wk-booking-slot-container-template" type="text/x-magento-template">
    <div class="field wk-booking-slot-row">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Monday')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container1">
        </div>
        <div class="collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container1">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="1">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="field wk-booking-slot-row">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Tuesday')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container2">
        </div>
        <div class="collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container2">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="2">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="field wk-booking-slot-row">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Wednesday')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container3">
        </div>
        <div class="collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container3">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="3">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="field wk-booking-slot-row">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Thursday')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container4">
        </div>
        <div class="collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container4">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="4">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="field wk-booking-slot-row">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Friday')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container5">
        </div>
        <div class="collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container5">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="5">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="field wk-booking-slot-row">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Saturday')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container6">
        </div>
        <div class="collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container6">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="6">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="field wk-booking-slot-row">
        <label class="label wk-booking-slot-container-label">
            <span>
                <?= /* @noEscape */ __('Sunday')?>
            </span>
        </label>
        <div class="wk-bk-label-slot-box-container" id="wk-bk-label-slot-box-container7">
        </div>
        <div class="collapsible-content wk-bk-hide">
            <div class="wk-booking-slot-container fieldset" id="wk-booking-slot-container7">
            </div>
            <div class="wk-booking-page-actions">
                <button class="action-primary wk-booking-row-add-btn" type="button"
                        data-role="action" data-day-type="7">
                    <span><?= /* @noEscape */ __('Add Slot')?></span>
                </button>
            </div>
        </div>
    </div>
</script>
<script id="wk-booking-slot-template" type="text/x-magento-template">
    <div class="field required wk-booking-slot-block" id="wk-booking-slot-block<%- data.id %><%- data.index %>">
        <label class="label">
            <span class="wk-booking-slot-label-span"><?= /* @noEscape */ __('Slot Span')?></span>
        </label>
        <div class="control grouped-date grouped">
            <div class="date">
                <label class="label">
                    <span><?= /* @noEscape */ __('From')?></span>
                </label>
                <div class="control">
                    <input class="input-text required-entry wk-booking-slot-picker" type="text"
                        name="product[slot_data][<%- data.id %>][<%- data.index %>][from]"
                        value="<%- data.from %>" readonly>
                </div>
            </div>
            <div class="date wk-booking-row-field-date">
                <label class="label">
                    <span><?= /* @noEscape */ __('To')?></span>
                </label>
                <div class="control">
                    <input class="input-text required-entry wk-booking-slot-picker" type="text"
                        name="product[slot_data][<%- data.id %>][<%- data.index %>][to]"
                        value="<%- data.to %>" readonly>
                </div>
            </div>
            <div class="wk-booking-row-btn-container">
                <button type="button" class="action-basic wk-booking-row-remove-btn" data-index="button_related">
                    <span><?= /* @noEscape */ __('Remove')?></span>
                </button>
            </div>
        </div>
    </div>
</script>
<script id="wk-booking-label-slot-template" type="text/x-magento-template">
    <div class="wk-bk-label-slot-box" id="wk-bk-label-slot-box<%- data.id %><%- data.index %>">
        <%- data.from %> - <%- data.to %>
        <span class="wk-bk-label-slot-box-close"></span>
    </div>
</script>
<?php
$jsData = [
    'slotDataType' => $product['slot_for_all_days'],
    'showMapLocation' => $product['show_map_loction'],
    'slotData' => $bookingSlotData
];
$encodedJsData = $viewModel->getJsonHelper()->jsonEncode($jsData);
?>
<script type="text/x-magento-init">
    {
        "body": {
            "mptablebooking": <?= /* @noEscape */ $encodedJsData; ?>
        }
    }
</script>
