<?php
/**
 * Webkul Software
 *
 * @category  Webkul
 * @package   Webkul_Mpquotesystem
 * @author    Webkul
 * @copyright Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Webkul_Mpquotesystem/js/wk-quote": {
                "minQtyVal": <?= /* @noEscape */ $block->getMinQty(); ?>
            }
        }
    }
</script>