<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0 ,shrink-to-fit=no">

</head>
<div class="container-fluid ">
<?php  $url = '/static/frontend/Smartwave/porto_child/en_US/Mageplaza_Ambasdor/images/background-ambasdor-new.png';?>
    <div class="row  m-2 ambasdor-row-1" style="background-image: url('<?php echo $url ?>'); background-repeat:no-repeat; ">
        <div class="col-sm-6  ambasdor-col-1">
                    <h3 class="join-us"> Join with us!</h3><br>
                    <h1 class="influencer">Become a valuable part of
                        our influencer network!</h1>
                        <span class="ambasdor-button py-5">
                                        <a href="/b2bmarketplace/supplier/create/">  
                                            <button class="btn btn-success btn-1 m-2"> Register </button>
                                        </a> 
                                        <a href="">  
                                            <button class="btn btn-secondary  btn-2 m-2" > How It works </button>
                                        </a> 
                        </span>
        </div>
        <div class="col-sm-5  ambasdor-col-2">
        <img src="<?php echo $this->getViewFileUrl('Mageplaza_Ambasdor::images/ambassador-header-image.png'); ?>" />
        </div>  
    </div>    
        
        <h2 class="py-3 text-center part-of-us">How to be a part of us?</h2>
    <div class="row py-5  ambasdor-row-2">
      
                        <div class="col-sm-4 ambasdor-col-3">
                                    <div class="card">
                                       
                                       <img  src="<?php echo $this->getViewFileUrl('Mageplaza_Ambasdor::images/ambassador.svg'); ?>"  class="card-img-top"/>
                                       
                                       
                                        <div class="card-body">
                                                    <h4 class="card-title mt-5">Register as ambassador</h4>
                                                    <p class="card-text" >
                                                    Join tens of thousands of creators, publishers and bloggers who are earning with the EnjoyP Associates Program.
                                                </p> 
                                                <img  src="<?php echo $this->getViewFileUrl('Mageplaza_Ambasdor::images/arrow-down.png'); ?>"  class="mobile"/>
                                        </div>
                                    </div>
                        </div>
                        <div class="col-sm-4 ambasdor-col-4">
                                    <div class="card">
                                    <img  class="desktop" src="<?php echo $this->getViewFileUrl('Enjoyp_Seller::images/arrow.png'); ?>"  style="text-center;"/>
                                    <img src="<?php echo $this->getViewFileUrl('Mageplaza_Ambasdor::images/product.svg'); ?>"  class="card-img-top"/>
                                        <div class="card-body">
                                                <h4 class="card-title  mt-5">Recommend our products</h4>
                                                <p class="card-text" >
                                                Share millions of products with your audience. We have customized linking tools for large publishers, individual bloggers and social media influencers.
                                            </p> 
                                            <img  src="<?php echo $this->getViewFileUrl('Mageplaza_Ambasdor::images/arrow-down.png'); ?>"  class="mobile"/>
                                        </div>
                                       
                                    </div>
                        </div>
                        <div class="col-sm-4 ambasdor-col-5">
                                    <div class="card">
                                        <img  class="desktop " src="<?php echo $this->getViewFileUrl('Mageplaza_Ambasdor::images/arrow.png'); ?>"  />

                                        <img src="<?php echo $this->getViewFileUrl('Mageplaza_Ambasdor::images/point.svg'); ?>"  class="card-img-top"/>
                                        
                                        <div class="card-body">
                                                <h4 class="card-title  mt-5">Earn Wageb points</h4>
                                                <p class="card-text" >
                                                Support our initiativ and earn points that you can convert in products. Wageb is an initiative to strengthen the Palestinian identity.
                                                </p> 
                                    
                                        </div>
                                    </div>
                        </div>
                            
                        <div class="col-sm-12 text-center m-5 join-us">
                            <a href="/b2bmarketplace/supplier/login/">  
                                <button class="btn btn-success  center-btn" > Join Us </button>
                            </a> 
                        </div>


    </div>
    <div class="row py-5 mt-4 ambasdor-row-3"  style="background:black;">
                  <div class="col-sm-6 ambasdor-col-6">
                  <img src="<?php echo $this->getViewFileUrl('Mageplaza_Ambasdor::images/social-media-reels.png'); ?>" />
                </div>
                <div class="col-sm-6 ambasdor-col-7">
                  <h1 class="share-product">Share products on social media reel</h1>
                  <p class="share-product-text">Create a Reel that shows off the most important features of your product in a way that's visually engaging and easy to understand. Join us as a social media 
                     reel sharing partner, to join first you need to fill up a form then we contact with you and make a business deal with you.</p>
                    <span class="join-us-btn">
                    <a href="/b2bmarketplace/supplier/login/">  
                        <button class="btn btn-success btn-1 ml-3"> Join Us </button>
                    </a> 
                   </span>
                </div>


   </div>     
   <div class="row py-5  mt-4 ambasdor-row-4"  style="background:black;">
                  <div class="col-sm-6 ambasdor-col-8">
                  <img src="<?php echo $this->getViewFileUrl('Mageplaza_Ambasdor::images/influencer.png'); ?>" />
                </div>
                <div class="col-sm-6 ambasdor-col-9">
                  <h1 class="become-influencer">Become an influencer of our products</h1>
                  <p class="become-influencer-text">Create a Reel that shows off the most important features of your product in a way that's visually engaging and easy to understand. Join us as a social 
                     media reel sharing partner, to join first you need to fill up a form then we contact with you and make a business deal with you.</p>
                     <span class="join-us-btn">
                    <a href="/b2bmarketplace/supplier/login/">  
                        <button class="btn btn-success btn-1 ml-3"> Join Us </button>
                    </a> 
                   </span>
                </div>
    </div>     
    <div class="row py-5  mt-4 ambasdor-row-5" style="background:black;">
                  <div class="col-sm-6 ambasdor-col-10">
                  <img src="<?php echo $this->getViewFileUrl('Mageplaza_Ambasdor::images/affiliate.png'); ?>" />
                </div>
                <div class="col-sm-6 ambasdor-col-11">
                  <h1 class="become-affliate">Become an affiliate and get  percentage from sell</h1>
                  <p class="become-affliate-text">Create a Reel that shows off the most important features of your product in a way that's visually engaging and easy to understand. Join us as a social media 
                     reel sharing partner, to join first you need to fill up a form then we contact with you and make a business deal with you.</p>
                     <span class="join-us-btn">
                    <a href="/b2bmarketplace/supplier/login/">  
                        <button class="btn btn-success btn-1 ml-3"> Join Us </button>
                    </a> 
                   </span>
                </div>
    </div>     
                  
    <div class="row py-5  mt-4 ambasdor-row-6"  style="background: #F2F6F5;">
            <div class="col-sm-12 ambasdor-center  d-none d-lg-block">
                     <h3 class="text-center join-of-us">Join with us</h3>
                               
                    <span class="choose-btn ">
                    <button type="submit"> <input type="radio" id="one" name="first_item" value="1" /> <label for="one">I will share reel</label></button>
                    <button type="submit"><input type="radio" id="two" name="first_item" value="1" />  <label for="two">I’m an Influencer</label></button>
                        <button type="submit"> <input type="radio" id="three" name="first_item" value="1" /><label for="one">I’m an Affiliate</label></button>
                    </span>
           </div>
           <div class="col-sm-12 ambasdor-center  d-block d-lg-none">
                     <h3 class="text-center join-of-us">Join with us</h3>
                               
                    <div class="choose-btn">
                    <button type="submit"> <input type="radio" id="one" name="first_item" value="1" /> <label for="one">I will share reel</label></button>
                    <button type="submit"><input type="radio" id="two" name="first_item" value="1" />  <label for="two">I’m an Influencer</label></button>
                        <button type="submit"> <input type="radio" id="three" name="first_item" value="1" /><label for="one">I’m an Affiliate</label></button>
                    </div>
           </div>
                    
            <div class="col-sm-5 py-5 ambasdor-col-12 d-none d-lg-flex" >
                    <img src="<?php echo $this->getViewFileUrl('Mageplaza_Ambasdor::images/join-us-ambasdor.png'); ?>" />
            </div>
            <div class="col-sm-6 py-5 ambasdor-col-13">
                 <?php echo $this->getLayout()->createBlock('Mageplaza\Ambasdor\Block\Form\Register')->setTemplate('Mageplaza_Ambasdor::form/register.phtml')->toHtml();
                //$block = $this->getLayout()->getBlock('customer_form_register');

                
                          ?>

         </div>
             

    </div> 
    <div class="row py-5  mt-4 ambasdor-row-7" style="background:black;" >
         <div class="col-sm-4 p-2">
         <img  class="ceo" src="<?php echo $this->getViewFileUrl('Mageplaza_Ambasdor::images/ambasdor-ceo.png'); ?>" /><br>
           <strong class="ambasdor-ceo-title">Leslie Alexander</strong><br>
           <strong class="follower"> 432K followers</strong>
            
           
          </div>

        <div class="col-sm-7 p-3">
               <div class="text">
              
              <p class="ambasdor-text" style="background: #E6FCF4;"> <img  class="comma" src="<?php echo $this->getViewFileUrl('Enjoyp_Seller::images/comma.png'); ?>"  style="max-width:25px;"/>
              B2B e-commerce platforms like Wholesale Channel, Technology Manager, and B2B Self Service Portal offer powerful tools to increase 
               efficiency and  ultimately lead to greater success. These platforms are essential for sellers to transact with buyers and access a vast pool of potential customers.</p>
                       <div class="arrow"  style="display:flex;">
                          <a href="#" "> <img src="<?php echo $this->getViewFileUrl('Enjoyp_Seller::images/backword.png'); ?>" /></a> 
                           <a href="#" "> <img src="<?php echo $this->getViewFileUrl('Enjoyp_Seller::images/forward.png'); ?>" /></a> 
                          
                </div>         
                        </div>
        </div>
                      

    </div>
      



</div>


<style>
    .ambasdor-index-index.layout-1220.mobile-sticky.page-layout-1column.wide .footer
    {
        display:none;
    }

    /* .required:after {
    content:" *";
    color: red;
       } */
       .col-sm-12.ambasdor-center span.choose-btn button:hover {
    color: unset!important;
    background-color: unset!important;
    border-color: #046F4F;
}
.text .arrow {
    display: flex;
    justify-content: space-around;
    margin-top: 65px;
}
    @media only screen and (min-width: 992px) {
    .row.py-5.mt-4.ambasdor-row-7 .col-sm-4.p-2 img.ceo {
    margin: 58px;
}
strong.ambasdor-ceo-title {
    margin-left: 65px;
    font-size: 29px;
    font-weight: 600;
    line-height: 32px;
    font-family: 'POPPINS';
    font-style: normal;
}
.col-sm-7.p-3 p.ambasdor-text {
    margin-top: 144px;
    margin-left: 40px;
    font-size: 16px;
    line-height: 28px;
    font-weight: 400;
    font-family: 'Poppins';
    font-style: normal;
    padding: 15px;
}

.text p.ambasdor-text img.comma {
    margin-top: -61px;
}
 
.col-sm-4.p-2 strong.follower {
    margin-left: 115px;
    font-size: 21px;
    font-weight: 400;
    font-family: 'Poppins';
    font-style: normal;
    line-height: 21px;
}
 /* .row.py-5.ambasdor-row-2 .col-sm-4.ambasdor-col-5 span.earnb{
        display:inline-table;

    } */
    /* .row.m-2.ambasdor-row-1 .col-sm-6.mt-5.ambasdor-col-1 {
    margin-left: 101px;
    } */
    
  span.earnb img.dollor{
    border-radius: 50%;
    width: 23px;
    height: 23px;
    margin-left: -17px;
    border: 2px solid red;
}

span.ambasdor-button.py-5 button.btn.btn-success.btn-1.m-2 {
    background: #046F4F;
    color: white;
    min-width: 170px;
}
span.ambasdor-button.py-5 button.btn.btn-secondary.btn-2.m-2 {
    background: #046F4F;
    color: white;
}
.row.m-2.ambasdor-row-1 .col-sm-6.ambasdor-col-1 {
    padding-left: 59px;
    padding-top: 102px;
}
.col-sm-5.ambasdor-col-2 img {
    min-width: 520px;
    min-height: 462px;
}
.col-sm-6.ambasdor-col-1 h3.join-us {
    font-size: 24px;
    line-height: 32px;
    font-weight: 500;
    font-family: 'Poppins';
    font-style: normal;
}
.col-sm-6.ambasdor-col-1 h1.influencer {
    font-size: 31px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    line-height: 120%;
}

h2.py-3.text-center.part-of-us {
    font-size: 40px;
    font-weight: 600;
    line-height: 48px;
    font-family: 'Poppins';
    font-style: normal;
    margin-top: 48px;
}
.row.py-5.ambasdor-row-2 h4.card-title.mt-5 {
    font-size: 24px;
    line-height: 32px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
}
.row.py-5.ambasdor-row-2 p.card-text {
    font-size: 16px;
    font-weight: 400;
    line-height: 24px;
    font-family: 'Poppins';
    font-style: normal;
}


.col-sm-12.text-center.m-5.join-us a button.btn.btn-success.center-btn {
    background: #046F4F;
    min-width: 200px;
    color: white;
    font-size: 16px;
    line-height: 16px;
    font-family: 'POPPINS';
    font-style: normal;
}
.col-sm-6.ambasdor-col-7 h1.share-product {
    font-size: 36px;
    line-height: 48px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    color: #E3E8EF;
}
span.join-us-btn button.btn.btn-success.btn-1.ml-3 {
    background: #046F4F;
    color: #E3E8EF;
}
.col-sm-6.ambasdor-col-7 p.share-product-text {
    font-size: 16px;
    line-height: 24px;
    font-family: 'POPPINS';
    font-style: normal;
    font-weight: 400;
    color: #CDD5DF;
}
.col-sm-6.ambasdor-col-6 {
   
    padding-top: 30px;
    padding-bottom: 30px;
    padding-left: 100px;
}
.col-sm-6.ambasdor-col-7 {
    padding: 51px;
}
.col-sm-6.ambasdor-col-8 {
    padding-top: 30px;
    padding-bottom: 30px;
    padding-left: 100px;
}
.col-sm-6.ambasdor-col-9 {
    padding: 51px;
}

.col-sm-6.ambasdor-col-9 h1.become-influencer{
    font-size: 36px;
    line-height: 48px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    color: #E3E8EF;

}
.col-sm-6.ambasdor-col-9 p.become-influencer-text{
   font-size: 16px;
    line-height: 24px;
    font-family: 'POPPINS';
    font-style: normal;
    font-weight: 400;
    color: #CDD5DF;

}
.col-sm-6.ambasdor-col-10{
    padding-top: 30px;
    padding-bottom: 30px;
    padding-left: 100px;

}
.col-sm-6.ambasdor-col-11
{
 padding: 51px;
}

.col-sm-6.ambasdor-col-11 h1.become-affliate
{
 font-size: 36px;
    line-height: 48px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    color: #E3E8EF;
}

.col-sm-6.ambasdor-col-11 p.become-affliate-text{
 font-size: 16px;
    line-height: 24px;
    font-family: 'POPPINS';
    font-style: normal;
    font-weight: 400;
    color: #CDD5DF;

}
.col-sm-12.ambasdor-center span.choose-btn {
    margin-left: 297px;
    margin-top: 20px;
}
.col-sm-5.py-5.ambasdor-col-12 {
    padding: 63px;
}

   .col-sm-6.py-5.ambasdor-col-13 div#fullAddress {
    display: flex;
    justify-content: space-between;
   
}
.col-sm-6.py-5.ambasdor-col-13 div#fullname {
    display: flex;
    justify-content: space-between;
}
.col-sm-6.py-5.ambasdor-col-13 div#socialaddress {
    display: flex;
    justify-content: space-between;
}
.col-sm-6.py-5.ambasdor-col-13 button.btn.btn-success.center-form-btn {
    
    margin-top: 33px;
    margin-left: 204px;
    width: 201px;
    background: #046F4F;
    color: white;
}
.col-sm-6.py-5.ambasdor-col-13 input.form-control.form-control-lg.phoneno {
    width: 643px;
    font-size: 20px;
}
.col-sm-12.ambasdor-center h3.text-center.join-of-us {
    font-size: 40px;
    line-height: 48px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
}
.col-sm-12.ambasdor-center span.choose-btn button {
    font-size: 18px;
    font-weight: 400;
    font-style: normal;
    line-height: 16px;
}
.col-sm-4.ambasdor-col-3 .card img.card-img-top {
    margin-left: 54px;
}
.col-sm-4.ambasdor-col-5 .card img.arrowtwo {
    margin-right: 36px;
}
.col-sm-4.ambasdor-col-3 .card img.arrowone {
    margin-left: 280px;
}
span.choose-btn input {
    margin-bottom: -5px;
}
.row.py-5.ambasdor-row-2 img.mobile {
 display: none;

}
.row.py-5.ambasdor-row-2 img.desktop {
    margin-right: 52px;
 
}


    }
    @media only screen and (max-width: 600px) { 
    .col-sm-6.ambasdor-col-1 h3.join-us {
    flex-flow: 1;
    font-size: 14px;
    font-style: normal;
    font-family: 'Poppins';
    line-height: 32px;
    display: flex;
    margin-top: 40px;
}
.col-sm-6.ambasdor-col-1 h1.influencer {
    font-size: 27px;
    line-height: 130%;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    margin-top: -32px;
}
span.ambasdor-button.py-5 {
    display: flex;
    justify-content: center;
    margin-top: -67px;
}
span.ambasdor-button.py-5 button.btn.btn-success.btn-1.m-2 {
    width: 130px;
    font-size: 10px;
    background: #046F4F;
    color: white;
}
span.ambasdor-button.py-5 button.btn.btn-secondary.btn-2.m-2 {
    width: 130px;
    font-size: 10px;
    background: border-box;
    color: #046F4F;
}
h2.py-3.text-center.part-of-us {
    font-size: 24px;
    line-height: 32px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;

    margin-top: 20px;
}
.col-sm-6.ambasdor-col-6 img {
    height: 140px;
    width: 140px;
}
.col-sm-6.ambasdor-col-7 h1.share-product {
    font-size: 20px;
    line-height: 28px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    color: #E3E8EF;
    margin-top:20px;
}
.col-sm-6.ambasdor-col-7 p.share-product-text {
    font-size: 14px;
    font-weight: 400;
    font-family: 'Poppins';
    font-style: normal;
    line-height: 20px;
    color: #CDD5DF;
}
span.join-us-btn {
    margin-left: -8px;
}
span.join-us-btn button.btn.btn-success.btn-1.ml-3 {
    background: #046F4F;
    color: white;
    
}

.col-sm-6.ambasdor-col-8 img {
    width: 140px;
    height: 140px;
}
.col-sm-6.ambasdor-col-9 h1.become-influencer {

    font-size: 20px;
    line-height: 28px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    color: #E3E8EF;
	margin-top:20px;
	}
	
	.col-sm-6.ambasdor-col-9 p.become-influencer-text
	{
	 font-size: 14px;
    font-weight: 400;
    font-family: 'Poppins';
    font-style: normal;
    line-height: 20px;
    color: #CDD5DF;
	}
	
	.col-sm-6.ambasdor-col-11 h1.become-affliate {
	  font-size: 20px;
    line-height: 28px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
    color: #E3E8EF;
	margin-top:20px;
}

.col-sm-6.ambasdor-col-11 p.become-affliate-text
{
 font-size: 14px;
    font-weight: 400;
    font-family: 'Poppins';
    font-style: normal;
    line-height: 20px;
    color: #CDD5DF;

}
.choose-btn button {
    width: 100%;
    text-align: inherit;
}
.col-sm-12.ambasdor-center.d-block.d.lg-none h3.text-center.join-of-us {
    font-size: 24px;
    font-weight: 600;
    font-style: normal;
    line-height: 32px;
    font-family: 'Poppins';
    margin-top: -22px;
}
.col-sm-6.ambasdor-col-10 img {
    width: 140px;
    height: 140px;
}
.row.py-5.ambasdor-row-2 img.desktop {
    display: none;
}
.row.py-5.ambasdor-row-2 img.card-img-top {
    margin-left: 93px;
}

.row.py-5.ambasdor-row-2 img.mobile {
   
    margin-left: 100px;
    margin-bottom: 26px;
	}
    .row.py-5.ambasdor-row-2 h4.card-title.mt-5 {
    font-size: 20px;
    line-height: 32px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
	 color: #222529;
}
.row.py-5.ambasdor-row-2 p.card-text {
    font-size: 14px;
    line-height: 20px;
    font-weight: 400;
    font-style: normal;
    font-family: 'Poppins';
    color: #4B5565;
}
.col-sm-12.text-center.m-5.join-us button.btn.btn-success.center-btn {
    background: #046F4F;
    color: white;
    font-size: 14px;
    line-height: 11px;
    font-style: normal;
    font-weight: 500;
    font-family: 'Poppins';
    }
    .col-sm-6.py-5.ambasdor-col-13 button.btn.btn-success.center-form-btn {
    display: flex;
    margin-left: 97px;
    margin-top: 23px;
    margin-bottom: -66px;
    background: #046F4F;
    color: white;
}
.col-sm-4.p-2 img.ceo {
    width: 166px;
    height: 208px;
    margin: 15px;
}
.col-sm-4.p-2 strong.follower {
    font-size: 18px;
    line-height: 20px;
    font-weight: 500;
    font-family: 'Poppins';
    font-style: normal;
    margin-left: 27px;
	color:#F0F0F0;
}
.col-sm-4.p-2 strong.ambasdor-ceo-title {
    font-size: 18px;
    line-height: 20px;
    font-weight: 500;
    font-family: 'Poppins';
    font-style: normal;
    margin-left: 20px;
	color:#F0F0F0;
}
.text p.ambasdor-text {
    font-size: 14px;
    line-height: 21px;
    font-weight: 400;
    font-family: 'Poppins';
    font-style: normal;
	    padding: 5px;
}
.text p.ambasdor-text img.comma {
    margin-top: -28px;
    margin-left: 12px;
}

    }
    </style>