<?php  $url = '/static/frontend/Smartwave/porto_child/en_US/Enjoyp_Seller/images/background.png';?>
<div class="container-fluid ">
    <div class="all-content"  style="background-image: url('<?php echo $url ?>'); background-repeat:no-repeat; height:800px;">
         <div class="row  m-2 prelaunch-row-1">  
                <div class="col-sm-12"  style="display: inline-flex; justify-content: space-between;">
                                
                                <img src="<?php echo $this->getViewFileUrl('Mageplaza_HelloWorld::images/Logo-green.png'); ?>"  width="100px" height="60px" />
                              <span class ="top" style="display:flex;     align-items: center;">
                                <strong class="merchant-title mr-5">Become a merchant</strong>
                                <strong class="ambassdor-title ml-5">Become a Ambassdor</strong>
                             </span>
                                <span class="quote-button">
                                        <a href="http://20.91.187.25/b2bmarketplace/supplier/login/">  
                                            <button class="btn btn-success btn-1 ml-3"> Get a Quote </button>
                                        </a> 
                                </span>

                </div> 
        </div>    
                <div class="row prelaunch-row-2"> 
                   
                    <div class="col-sm-12 ml-5"  style="display: inline-flex; justify-content:center;">
                        <img src="<?php echo $this->getViewFileUrl('Mageplaza_HelloWorld::images/announce.png'); ?>"  class="m-2" width="50px" height="50px"  style="background:#046F4F; border-radius:50%; ">
                             <h3 class="soon-live ml-3"> We are coming  on live Soon!</h3>
                            </div>
                                

                         


                      
                    <div class="col-sm-5 prelaunch-col">
                        <h2 class="coming-soon">We are coming soon!</h2>
                        <h1 class="enjoyp">Welcome to<br>
                          Enjoy Palestine!</h1>
                         <p class="enjoyp-text">Signup for our newsletter and be the first to know when our website launches. Enter your email below to stay updated on our progress and receive exclusive 
                             offers.</p>
                          <div class="subscribe"> 
                          <input type="email" data-validate="{required:true, 'validate-email':true}"  placeholder="Enter email">
                          <a href="http://20.91.187.25/b2bmarketplace/supplier/login/">   <button class="btn btn-success btn-1 ml-3"> Subscribe </button></a> 
                        </div>
                    </div>
                    <div class="col-sm-6">
                    <img src="<?php echo $this->getViewFileUrl('Mageplaza_HelloWorld::images/pre-launch-1.png'); ?>"  width="600px" height="270px" class="mr-2 prelaunch " />
                    </div> 
               </div>
        </div>
        <div class="row prelaunch-row-3  py-5">
        <div class="col-sm-5 prelaunch-col-3 m-3"> 

        <img src="<?php echo $this->getViewFileUrl('Mageplaza_HelloWorld::images/ambas-1.png'); ?>" />

         </div>
         <div  class="col-sm-5 prelaunch-col-4">
            <h1 class="merchant">Become a merchant</h1>
            <p class="mechant-text">Attention merchants! Get ready to launch your online business with us. Sign up now to become a merchant on our platform and unlock exclusive perks and benefits. Be the 
                 first to access our ecommerce tools and start selling your products online. Don't wait any longer, register now and stay ahead of the competition.</p>
                 <span class="register-button">
                    <a href="http://20.91.187.25/b2bmarketplace/supplier/login/">  
                        <button class="btn btn-success btn-1 ml-3"> Register </button>
                    </a> 
                </span>


         </div>
         <div class="row prelaunch-row-4  py-5">
            <div  class="col-sm-5 prelaunch-col-5">
                    <h1 class="ambassdor">Become an ambassdor</h1>
                    <p class="ambassdor-text">Be the first to access our ambassador tools and start making a difference in your community. Don't wait any longer, register now and be part of the Wageb 
                         movement. Support our initiativ and earn points that you can convert in products. Wageb is an initiative to strengthen the Palestinian identity..</p>
                        <span class="register-button">
                                                <a href="http://20.91.187.25/b2bmarketplace/supplier/login/">  
                                                    <button class="btn btn-success btn-1 ml-3"> Register </button>
                                                </a> 
                                        </span>
           </div>
           <div class="col-sm-5 prelaunch-col-6 m-3"> 

        <img src="<?php echo $this->getViewFileUrl('Mageplaza_HelloWorld::images/become-ambassdor.png'); ?>" />

         </div>
      </div>  
      <?php  $url = '/static/frontend/Smartwave/porto_child/en_US/Enjoyp_Seller/images/BG-black.png';?>
      <div class="row prelaunch-row-5  py-5" style="background-image: url('<?php echo $url ?>');" >
            <div  class="col-sm-5 prelaunch-col-7 m-2 ">
            <img src="<?php echo $this->getViewFileUrl('Mageplaza_HelloWorld::images/rocket-launch.jpg'); ?>" />

             </div>
             <div  class="col-sm-5 prelaunch-col-8">
                <h1 class="launch-coming">Coming Soon</h1>
                <p class="ready">Are you ready to get something new from us. Then subscribe the news latter to get latest updates?</p>
                
                <div class="subscribe"> 
                          <input type="email" data-validate="{required:true, 'validate-email':true}"  placeholder="Enter email">
                          <a href="http://20.91.187.25/b2bmarketplace/supplier/login/">   <button class="btn btn-success btn-1 ml-3"> Subscribe </button></a> 
                        </div>
            </div>
      </div>
</div>
<style>
    .row.prelaunch-row-2 .col-sm-5.prelaunch-col {
    margin: 46px;
}
    .row.m-2.prelaunch-row-1 span.quote-button {
        margin-top:24px;
    }
    .row.m-2.prelaunch-row-1 span.quote-button button.btn.btn-success.btn-1.ml-3 {
    color: white;
    background: #046F4F;
}
.col-sm-5.prelaunch-col h2.coming-soon {
    font-size: 24px;
    font-weight: 500;
    line-height: 32px;
    font-family: 'Poppins';
    font-style: normal;
}
.row.prelaunch-row-2 .col-sm-5.prelaunch-col h1.enjoyp {
    font-size: 50px;
    line-height: 114%;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
}
.row.prelaunch-row-2 h3.soon-live.ml-3 {
    font-size: 24px;
    line-height: 26px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
}
input[type="email"] {
    color: white;
    width: 281px;
   height: 50px;
    border: 1px solid #046F4F;
    background: #EBF3F1;
    color:#046F4F;
    border-radius: 11px;

}
.subscribe {
    display: flex;
}
.subscribe button.btn.btn-success.btn-1.ml-3 {
    width: 163px;
    background: #046F4F;
    color: white;
    border-radius: 11px;
}
input[type="email"]::placeholder {
    color: #046F4F;
    font-size: 16px;
    font-weight: 500;
    
}
.col-sm-5.prelaunch-col p.enjoyp-text {
    font-size: 17px;
    line-height: 28px;
    font-weight: 400;
    font-family: 'Poppins';
    font-style: normal;
}
.col-sm-5.prelaunch-col h1.enjoyp {
    margin: -14px 0 32px 0;
}
.col-sm-5.prelaunch-col h2.coming-soon {
    margin: -41px 0 32px 0;
}
.row.prelaunch-row-5.py-5 {
    background: black;
    width: 1326px;
}
.col-sm-5.prelaunch-col-8 h1 {
    color: white;
}
.row.prelaunch-row-5.py-5 .col-sm-5.prelaunch-col-8 {
    margin-right: 167px;
}
.row.prelaunch-row-4.py-5 .col-sm-5.prelaunch-col-5 {
    margin-right: 188px;
}
.row.prelaunch-row-3.py-5 .col-sm-5.prelaunch-col-4 {
    margin-inline-start: 160px;
}

.col-sm-5.prelaunch-col-7.m-2 img {
    border-radius: 50%;
    width: 350px;
    height: 350px;
    margin: 14px;
}

.col-sm-5.prelaunch-col-8 p.ready {
    font-size: 18px;
    line-height: 30px;
    font-family: 'POPPINS';
    font-style: normal;
    font-weight: 400;
    color: white;
}
.col-sm-5.prelaunch-col-8 h1.launch-coming {
    font-size: 40px;
    line-height: 48px;
    font-weight: 600;
    font-family: 'Poppins';
    font-style: normal;
}
.col-sm-5.prelaunch-col-5 h1.ambassdor {
    font-size: 32px;
    line-height: 36px;
    font-weight: 600;
    font-family: 'POPPINS';
    font-style: normal;
}
.col-sm-5.prelaunch-col-5 p.ambassdor-text {
    font-size: 16px;
    font-weight: 400;
    font-style: normal;
    line-height: 26px;
    font-family: 'Poppins';
}
span.register-button button.btn.btn-success.btn-1.ml-3 {
    background: #046F4F;
    color: white;
}
.col-sm-5.prelaunch-col-4 h1.merchant {
    font-style: normal;
    font-weight: 600;
    line-height: 36px;
    font-family: 'Poppins';
}
.col-sm-5.prelaunch-col-4 p.mechant-text {
    font-weight: font-si;
    font-size: 16px;
    font-weight: 400;
    font-family: 'Poppins';
    line-height: 26px;
    font-style: normal;
}
.col-sm-12 span.top {
    font-size: 18px;
    font--we: 600;
    font-weight: 600;
    line-height: 120%;
    font-family: 'Poppins';
    font-style: normal;
}
.row.m-2.prelaunch-row-1 .col-sm-12 img {
    margin-top: 15px;
}
    </style>