
<?php  $url = '/static/frontend/Smartwave/porto_child/en_US/Enjoyp_Seller/images/background.png';?>
<div class="container-fluid ">
    <div class="all-content-desktop d-none d-lg-block bg-grey">
		<div class="container">
          <div class="row  m-2 prelaunch-row-1">  
                <div class="col-sm-12"  style="display: inline-flex; justify-content: space-between;">
                        <img src="<?php echo $this->getViewFileUrl('Consultera_Prelaunch::images/Logo-green.png'); ?>"  width="100px" height="60px" />
                            <span class ="top" style="display:flex;     align-items: center;">
                               <a href="/marketplace/"> <strong class="merchant-title mr-5">Become a merchant</strong></a>
                               <a href="/ambasdor" ><strong class="ambassdor-title ml-5">Become a Ambassdor</strong> </a>
                            </span>
                          

                </div> 
        </div>    
        <div class="row prelaunch-row-2 launching-soon"> 
                <div class="col-sm-12 ml-5 img-wrapper">
                                <img src="<?php echo $this->getViewFileUrl('Consultera_Prelaunch::images/announce.png'); ?>"  class="m-2" width="50px" height="50px"  style="background:#046F4F; border- 
                                radius:50%; ">
                                <h3 class="soon-live ml-3"> We are coming  on live Soon!!</h3>
                </div>
                <div class="col-sm-6 prelaunch-col">
                                <h2 class="small-title">Welcome to</h2>
                                <h1>Enjoy Palestine!</h1>
                                <p class="enjoyp-text">Signup for our newsletter and be the first to know when our website launches. Enter your email below to stay updated on our progress and receive 
                                exclusive offers.</p>
                                <div class="subscribe"> 
                                <?php echo $this->getLayout()->createBlock('Consultera\Prelaunch\Block\Subscribe')->setTemplate('Consultera_Prelaunch::subscribe.phtml')->toHtml(); ?>
                         
                              </div>
                </div>
                <div class="col-sm-6">
                               <img src="<?php echo $this->getViewFileUrl('Consultera_Prelaunch::images/header image.png'); ?>"   class="mr-2 prelaunch-1 "/ >
                </div> 
        </div>
		</div>
    </div>
    <div class="all-content-mobile d-block d-lg-none bg-grey">
	<div class="container">
    <div class="row prelaunch-row-2"> 
            <div class="col-md-6 col-sm-12 prelaunch-col">
                                <h1 class="enjoyp">Welcome to<br>
                                Enjoy Palestine!</h1>
                                <p class="enjoyp-text">The online marketplace where you can discover and buy high quality products from Palestinian producers! Our platform is designed to connect you with unique and authentic Palestinian products, while also supporting Palestinian producers and promoting Palestinian culture.</p>
                                <div class="subscribe"> 
                                <?php echo $this->getLayout()->createBlock('Consultera\Prelaunch\Block\Subscribe')->setTemplate('Consultera_Prelaunch::subscribe.phtml')->toHtml(); ?>
                         
                              </div>
                </div>
                <div class="col-md-6 col-sm-12">
                               <img src="<?php echo $this->getViewFileUrl('Consultera_Prelaunch::images/header image.png'); ?>"   class="mr-2 prelaunch-1 "/ >
                </div> 
        </div>
		</div>
    </div>
		<div class="container">
        <div class="row prelaunch-row-3  py-5 margin-80">
			<?php  $url = '/static/frontend/Smartwave/porto_child/en_US/Consultera_Prelaunch/images/prelaunch-small-bg.png';?>
			   <div class="col-md-6 col-sm-12 prelaunch-col-3"> 
			   <!-- style="background-image: url('<?php echo $url ?>'); background-repeat:no-repeat;" -->
						   
					   <img class="merchant-img" src="<?php echo $this->getViewFileUrl('Consultera_Prelaunch::images/Become a merchant.png'); ?>" />

			 </div>
			 <div  class="offset-1 col-md-5 col-sm-12 prelaunch-col-4">
				<h2 class="merchant">Become a merchant</h2>
				<p class="mechant-text">Join the Global Marketplace and Boost Your Sales with Enjoy Palestine.</p>
				<p>Are you looking for an effective way to expand your reach to the European market and increase your sales? Look no further than Enjoy Palestine, the leading online marketplace for high-quality Palestinian products!  By registering with Enjoy Palestine, you'll gain access to our unparalleled co-distribution, co-marketing, and after-sales services, which are designed to help you succeed in the competitive European market. Our team of experienced marketing professionals will work closely with you to develop a customized marketing plan that will help you promote your products to a wider audience and increase your sales.</p>
					 <span class="register-button">
											<a href="/marketplace/">  
												<button class="btn btn-success btn-1 ml-3"> How It Works </button>
											</a> 
									</span>


			 </div>
		 </div>
		 </div>
		 <div class="container">
         <div class="row prelaunch-row-4  py-5 ambassador-section">
         <div class="col-md-6 col-sm-12 prelaunch-col-6 d-block d-lg-none"> 
            <!--  style="background-image: url('<?php echo $url ?>'); background-repeat:no-repeat; -->
                <img class="ambasdor-img" src="<?php echo $this->getViewFileUrl('Consultera_Prelaunch::images/Become an ambassador.png'); ?>" />
            </div>
            <div  class="col-md-5 col-sm-12 prelaunch-col-5">
                    <h2 class="ambassdor">Become an ambassdor</h2>
                    <p class="ambassdor-text">Are you passionate about promoting authentic and high-quality products to your followers? Do you want to make a positive impact by supporting Palestinian producers and promoting Palestinian culture? Then you'll want to join Enjoy Palestine, the leading online marketplace for Palestinian products!</p>
                        <span class="register-button">
                                                <a href="/ambasdor">  
                                                    <button class="btn btn-success btn-1 ml-3"> Register </button>
                                                </a> 
                                        </span>
           
            </div>
             <div class="offset-1 col-md-6 col-sm-12 prelaunch-col-6 d-none d-lg-block" > 
                <!--  style="background-image: url('<?php echo $url ?>'); background-repeat:no-repeat;" -->
                <img  class="ambasdor-img" src="<?php echo $this->getViewFileUrl('Consultera_Prelaunch::images/Become an ambassador.png'); ?>" />
            </div>
		</div>
      </div>  
      <?php  $urlb = '/static/frontend/Smartwave/porto_child/en_US/Consultera_Prelaunch/images/BG-black-prelaunch.png';?>
		<div class="container fullwidth-container">
		<div class="row prelaunch-row-5 coming-soon">
            <div  class="col-md-5 col-sm-12 prelaunch-col-7">
            <img  class="launch" src="<?php echo $this->getViewFileUrl('Consultera_Prelaunch::images/launch-image.png'); ?>" />

             </div>
             <div  class="col-md-6 col-sm-12 prelaunch-col-8">
                <h2 class="launch-coming">Coming Soon</h2>
                <p class="ready">Are you ready to get something new from us. Then subscribe the news latter to get latest updates?</p>
                
                <div class="subscribe"> 
                <?php echo $this->getLayout()->createBlock('Consultera\Prelaunch\Block\Subscribe')->setTemplate('Consultera_Prelaunch::subscribe.phtml')->toHtml(); ?>
                          <!-- <input type="email" data-validate="{required:true, 'validate-email':true}"  placeholder="Enter email">
                          <a href="/b2bmarketplace/supplier/login/">   <button class="btn btn-success btn-1 ml-3"> Subscribe </button></a>  -->
                        </div>
            </div>
		</div>
		</div>
</div>
<style>
.prelaunch-row-1 {display:none;}
.bg-grey {background-color: #F3F7F6;}
.layout-1220 .block.category.event, .layout-1220 .footer.content, .layout-1220 .header.content, .layout-1220 .navigation, 
.layout-1220 .page-main, .layout-1220 .page-wrapper>.breadcrumbs >ul, .layout-1220 .page-wrapper>.page-bottom, 
.layout-1220 .page-wrapper>.widget,.page-header.type15 .header-main .header.content {max-width: 100%;}
.container-fluid {padding:0;}
#maincontent {padding: 0;}
.m-2 {margin:0!important;}
.ml-5, .mx-5 {margin-left: 0!important;}
.coming-soon {padding:80px 180px; background-color:#000; margin-bottom:80px; color:#fff;}
input#newsletter {
	border: 1px solid #FFFFFF;
    border-radius: 0;
    background-color: transparent;
    padding-left: 15px;
    font-family: 'Poppins';
    font-style: normal;
    font-weight: 500;
    font-size: 16px;
    line-height: 26px;
    color: #fff;
    margin-right: 15px;
	height:64px;
	width: 300px;
}
button.subscribe {
	padding: 19px 47px;
	height: 64px;
	background: #046F4F;
	border: 1px solid #046F4F;
}
button.subscribe span {
	text-align: center;
    color: #FFFFFF;
    text-transform: none;
    letter-spacing: 0;
	font-size: 16px;
	font-weight:400;
}
#maincontent .btn-success {
    background: #046F4F;
    font-weight: 500;
    font-size: 16px;
    line-height: 26px;
    text-align: center;
    color: #FFFFFF;
    height: 54px;
    padding: 13px 50px;
    text-transform: none;
    letter-spacing: 0;
}
.coming-soon p.ready {margin-bottom: 40px;}
.coming-soon .newsletter .control:before {content: ''!important;}
.launching-soon .img-wrapper img {height: 52px;	width: 52px;background: #046F4F;box-shadow: -6px 12px 40px rgba(33, 24, 0, 0.1);border-radius: 52px;padding: 13px;}
.launching-soon {padding-top: 75px;}
.launching-soon .img-wrapper {margin: 0 auto 30px auto;display: block;text-align: center;}
h3.soon-live {vertical-align: middle;display: inline-block;font-size: 20px;line-height: 26px;margin: 0;}
h2.small-title , h2 {font-weight: 600;font-size: 32px;line-height:42px;}
h2.small-title {margin-bottom: 10px;}
h1 {font-size: 50px;line-height: 120%;letter-spacing: -0.01em;color: #222529;}
.block.newsletter .field .control:before {display:none;}
#maincontent .block.newsletter .field {display:inline-block; margin-right:15px;}
#maincontent .block.newsletter .actions {display: inline-block;}
#maincontent input {border: 1px solid #4B5565; height:52px;}
.block.newsletter .action.subscribe {height:52px;background: #046F4F;border:1px solid #046F4F}
p {font-size:16px;line-height: 26px;}
p.enjoyp-text {max-width:512px; margin-bottom:40px;}
.margin-80 {margin-top:80px;}
.mechant-text {font-size: 20px;line-height: 28px;color: #4B5565;}
input[type="email"]::placeholder {color: #4B5565;font-size: 16px;font-weight: 500;}
.coming-soon h2 {color:#fff;}
.coming-soon input[type="email"]::placeholder {color:#fff;}
#maincontent .coming-soon input[type="email"] {border:1px solid #fff;}
body .footer-top {background: #409975;}
body .footer-top input#newsletter {background: #FFFFFF; border-radius: 27px; max-width: 596px; width: 100%; height: 50px; padding-right: 60px;}
body .footer-top .single-subscribe .newsletter .control {position: relative; display: block;}
body .footer .newsletter .action.subscribe {position: absolute; right: 0; top: 0; height: 50px;}
body .footer .newsletter .action.subscribe span {
	font-size: 14px;
    line-height: 18px;
    display: flex;
    align-items: center;
    letter-spacing: -0.02em;
    color: #222529;
    text-transform: uppercase;
    font-weight: 600;
}
.footer .follow-us .share-links a:not(:hover) {color: #333;}
.footer-top input[type="email"]::placeholder {color: #D6D6D6;}
.footer-middle, .footer-bottom {background: linear-gradient(284.11deg, #181F1D 2.74%, #0D1412 98.44%);}
body .footer .follow-us .share-links a:not(:hover) {color: #0B1A14;}
.prelaunch-index-index .porto-block-html-top {display: none;}
.page-header .header-main {max-width: 88%; margin: 0 auto;}
.page-header.sticky-header .header-main {max-width: 100%;}
body .page-wrapper .page-header.sticky-header .header-main .header {max-width: 88%;}
footer .single-subscribe .newsletter .input-text {z-index:1!important;}

@media only screen and (max-width:1299px) {
	.coming-soon {padding: 80px 100px;}
	input#newsletter {width: 250px;}
}


@media only screen and (max-width: 991px) { 
	.all-content-mobile h1.enjoyp {font-size: 32px; line-height: 130%;}
	.all-content-mobile {padding-top:50px;}
	#maincontent .block.newsletter .field {width:65%; margin-right: 0;}
	#maincontent .block.newsletter .actions {width:35%}
	.block.newsletter .action.subscribe {width:100%; padding:15px;}
	input#newsletter {width: calc(100% - 15px);}
	p.enjoyp-text {margin-bottom:30px;}
	.all-content-mobile .col-md-6:nth-chil(2) {margin-top:30px;}
	.margin-80 {margin-top: 10px;}
	h2.small-title, h2 {font-size: 24px; line-height: 32px; margin-bottom:15px;}
	.merchant-img {margin-bottom:30px;}
	.mechant-text {font-size: 16px; line-height: 24px; margin-bottom: 10px; font-weight: 500; color:#23262F;}
	.offset-1 {margin:0;}
	#maincontent .btn-success {margin-left:0!important;}
	.ambassador-section {padding-top: 20px!important;}
	.ambassador-section .ambassdor {margin-top:30px;}
	.coming-soon {display: block; padding: 40px 20px; margin-bottom:0;}
	.coming-soon .prelaunch-col-8 {margin-top: 40px; padding: 0;}
	#maincontent .fullwidth-container {padding:0!important;max-width:95%;}
	.page-header .header-main {padding: 0 20px;}
	header.page-header.sticky-header .header-main {padding:10px 20px;}
	.prelaunch-index-index .header-right {display:none;}
	.prelaunch-index-index .logo img {width: 50px;}
	.prelaunch-index-index .header-left,.prelaunch-index-index .header-left span.action.nav-toggle {margin:0 auto;}
	.prelaunch-index-index .header-left a.logo {margin-left: 0!important;}
	.footer-middle > .container {padding-top:40px;}
	.footer-middle img {width: 72px;}
	footer .porto-block {padding-bottom: 50px;}
	.footer-top .footer-top-bottom .widget.follow-us {position: absolute; top: 88px; margin-bottom: 0;}
	footer .porto-sicon-header {margin-top:10px;}
	footer .porto-sicon-header p {line-height:16px;} 	
	.prelaunch-index-index footer .porto-block {display:none;}
	.prelaunch-index-index h6.text-uppercase.mb-0 , .prelaunch-index-index .textwidget .text-xl, .prelaunch-index-index .widget_custom_html {display: none;}
	.prelaunch-index-index .nav-toggle {position:absolute; left:0;}
	.prelaunch-index-index .footer-top .footer-top-bottom .widget.widget_text {display: none;}
	.prelaunch-index-index .footer .footer-top .widget:last-child {margin:0;}
	.prelaunch-index-index .footer .widget .textwidget p.mb-4:nth-child(2) {display: none;}
	.prelaunch-index-index .footer-top .footer-top-bottom .widget.follow-us {position: absolute;display: block;top: 60px;left: auto;width: auto;right: 20px;}
	.prelaunch-index-index .footer .follow-us .share-links a {margin-right:10px;}
	.prelaunch-index-index .footer .widget {margin-bottom:0;}
	body.prelaunch-index-index .footer .widget p.mb-4 {margin-bottom: 0!important;}
	.all-content-mobile img {margin-top:35px;}
}
    </style>